import type { ContentItem } from '@/types/game'

export const CONJUGATION_ITEMS: ContentItem[] = [
  // ── Past Simple (irregular) ───────────────────────────────
  {
    id: 'c1',
    type: 'verb_conjugation',
    difficulty: 380,
    skill: 'past_simple',
    tags: ['irregular-verbs', 'beginner'],
    data: {
      verb_base: 'go',
      target_tense: 'Past Simple',
      target_person: 'she / he / it',
      context_sentence: 'Yesterday, she ___ to the market.',
      context_translation: 'אתמול, היא ___ לשוק.',
      correct_answer: 'went',
      common_mistake: '"Go" is irregular. Past Simple: go → went. Never "goed."',
    },
  },
  {
    id: 'c2',
    type: 'verb_conjugation',
    difficulty: 390,
    skill: 'past_simple',
    tags: ['irregular-verbs', 'beginner'],
    data: {
      verb_base: 'buy',
      target_tense: 'Past Simple',
      target_person: 'they',
      context_sentence: 'They ___ a new car last month.',
      context_translation: 'הם ___ מכונית חדשה בחודש שעבר.',
      correct_answer: 'bought',
      common_mistake: '"Buy" is irregular. Past Simple: buy → bought. Rhymes with "thought" and "caught."',
    },
  },
  {
    id: 'c3',
    type: 'verb_conjugation',
    difficulty: 400,
    skill: 'past_simple',
    tags: ['irregular-verbs', 'beginner'],
    data: {
      verb_base: 'write',
      target_tense: 'Past Simple',
      target_person: 'I',
      context_sentence: 'I ___ a letter to my friend.',
      context_translation: 'כתבתי מכתב לחברי.',
      correct_answer: 'wrote',
      common_mistake: '"Write" is irregular: write → wrote → written. Past Simple is "wrote" (no "d" or "ed").',
    },
  },
  {
    id: 'c4',
    type: 'verb_conjugation',
    difficulty: 410,
    skill: 'past_simple',
    tags: ['irregular-verbs', 'beginner'],
    data: {
      verb_base: 'take',
      target_tense: 'Past Simple',
      target_person: 'we',
      context_sentence: 'We ___ the train to the city centre.',
      context_translation: 'לקחנו את הרכבת למרכז העיר.',
      correct_answer: 'took',
      common_mistake: '"Take" is irregular: take → took → taken. Past Simple is "took."',
    },
  },
  {
    id: 'c5',
    type: 'verb_conjugation',
    difficulty: 430,
    skill: 'past_simple',
    tags: ['irregular-verbs', 'beginner'],
    data: {
      verb_base: 'speak',
      target_tense: 'Past Simple',
      target_person: 'he',
      context_sentence: 'He ___ to the manager about the problem.',
      context_translation: 'הוא ___ עם המנהל על הבעיה.',
      correct_answer: 'spoke',
      common_mistake: '"Speak" is irregular: speak → spoke → spoken. Do not say "speaked."',
    },
  },
  // ── Present Perfect ───────────────────────────────────────
  {
    id: 'c6',
    type: 'verb_conjugation',
    difficulty: 450,
    skill: 'present_perfect',
    tags: ['present-perfect', 'beginner'],
    data: {
      verb_base: 'see',
      target_tense: 'Present Perfect',
      target_person: 'I',
      context_sentence: 'I ___ that film three times already.',
      context_translation: 'כבר ___ את הסרט הזה שלוש פעמים.',
      correct_answer: 'have seen',
      common_mistake: '"See" irregular past participle: see → saw → seen. Present Perfect: have/has + seen.',
    },
  },
  {
    id: 'c7',
    type: 'verb_conjugation',
    difficulty: 470,
    skill: 'present_perfect',
    tags: ['present-perfect'],
    data: {
      verb_base: 'eat',
      target_tense: 'Present Perfect',
      target_person: 'she',
      context_sentence: 'She ___ sushi many times — she loves Japanese food.',
      context_translation: 'היא ___ סושי הרבה פעמים — היא אוהבת אוכל יפני.',
      correct_answer: 'has eaten',
      common_mistake: '"Eat" irregular: eat → ate → eaten. With "she/he/it" use "has eaten", not "have eaten."',
    },
  },
  {
    id: 'c8',
    type: 'verb_conjugation',
    difficulty: 490,
    skill: 'present_perfect',
    tags: ['present-perfect', 'intermediate'],
    data: {
      verb_base: 'break',
      target_tense: 'Present Perfect',
      target_person: 'they',
      context_sentence: 'They ___ the record for the fastest marathon time.',
      context_translation: 'הם ___ את השיא לזמן המרתון המהיר ביותר.',
      correct_answer: 'have broken',
      common_mistake: '"Break" irregular: break → broke → broken. Present Perfect uses "broken" (past participle), not "broke."',
    },
  },
  // ── Present Simple (3rd person) ───────────────────────────
  {
    id: 'c9',
    type: 'verb_conjugation',
    difficulty: 360,
    skill: 'present_simple',
    tags: ['present-simple', 'beginner'],
    data: {
      verb_base: 'study',
      target_tense: 'Present Simple',
      target_person: 'she / he / it',
      context_sentence: 'She ___ English every evening.',
      context_translation: 'היא ___ אנגלית כל ערב.',
      correct_answer: 'studies',
      common_mistake: 'Verbs ending in consonant + y: change "y" to "i" and add "-es". study → studies, carry → carries.',
    },
  },
  {
    id: 'c10',
    type: 'verb_conjugation',
    difficulty: 370,
    skill: 'present_simple',
    tags: ['present-simple', 'beginner'],
    data: {
      verb_base: 'watch',
      target_tense: 'Present Simple',
      target_person: 'he',
      context_sentence: 'He ___ the news every morning before breakfast.',
      context_translation: 'הוא ___ חדשות כל בוקר לפני ארוחת הבוקר.',
      correct_answer: 'watches',
      common_mistake: 'Verbs ending in -ch, -sh, -x, -ss, -o add "-es": watch → watches, finish → finishes.',
    },
  },
  // ── Future (will / going to) ──────────────────────────────
  {
    id: 'c11',
    type: 'verb_conjugation',
    difficulty: 440,
    skill: 'future_will',
    tags: ['future', 'intermediate'],
    data: {
      verb_base: 'be',
      target_tense: 'Future Simple (will)',
      target_person: 'they',
      context_sentence: 'The results ___ announced at the end of the week.',
      context_translation: 'התוצאות ___ יוכרזו בסוף השבוע.',
      correct_answer: 'will be',
      common_mistake: 'This is passive future: "will be + past participle (announced)." Just conjugate "be" with "will" here.',
    },
  },
  {
    id: 'c12',
    type: 'verb_conjugation',
    difficulty: 460,
    skill: 'future_going_to',
    tags: ['future', 'intermediate'],
    data: {
      verb_base: 'travel',
      target_tense: 'Future (going to)',
      target_person: 'we',
      context_sentence: 'We ___ to Argentina next spring.',
      context_translation: 'אנחנו ___ לארגנטינה באביב הבא.',
      correct_answer: 'are going to travel',
      common_mistake: '"Going to" + base verb. With "we": "we are going to travel." Indicates a planned decision.',
    },
  },
  // ── Past Continuous ───────────────────────────────────────
  {
    id: 'c13',
    type: 'verb_conjugation',
    difficulty: 500,
    skill: 'past_continuous',
    tags: ['past-continuous', 'intermediate'],
    data: {
      verb_base: 'work',
      target_tense: 'Past Continuous',
      target_person: 'she',
      context_sentence: 'She ___ on the presentation when the power cut off.',
      context_translation: 'היא ___ על המצגת כשהחשמל נכבה.',
      correct_answer: 'was working',
      common_mistake: 'Past Continuous: was/were + verb-ing. Describes an ongoing past action interrupted by another event.',
    },
  },
  {
    id: 'c14',
    type: 'verb_conjugation',
    difficulty: 520,
    skill: 'past_continuous',
    tags: ['past-continuous', 'intermediate'],
    data: {
      verb_base: 'listen',
      target_tense: 'Past Continuous',
      target_person: 'they',
      context_sentence: 'They ___ to music when I arrived.',
      context_translation: 'הם ___ למוזיקה כשהגעתי.',
      correct_answer: 'were listening',
      common_mistake: 'With "they/we/you", use "were + -ing". With "I/she/he/it", use "was + -ing."',
    },
  },
  // ── Present Continuous ────────────────────────────────────
  {
    id: 'c15',
    type: 'verb_conjugation',
    difficulty: 390,
    skill: 'present_continuous',
    tags: ['present-continuous', 'beginner'],
    data: {
      verb_base: 'run',
      target_tense: 'Present Continuous',
      target_person: 'he',
      context_sentence: 'Look! He ___ towards the finish line.',
      context_translation: 'תסתכל! הוא ___ לקראת קו הסיום.',
      correct_answer: 'is running',
      common_mistake: 'Double the final consonant before adding -ing for short vowel + consonant verbs: run → running, sit → sitting.',
    },
  },
  // ── Beginner (Tier 1) ─────────────────────────────────────
  {
    id: 'c16',
    type: 'verb_conjugation',
    difficulty: 350,
    skill: 'present_simple',
    tags: ['present-simple', 'beginner'],
    data: {
      verb_base: 'be',
      target_tense: 'Present Simple',
      target_person: 'I',
      context_sentence: 'I ___ a student.',
      context_translation: 'אני ___ תלמיד.',
      correct_answer: 'am',
      common_mistake: 'Use "am" with "I", "is" with he/she/it, "are" with you/we/they.',
    },
  },
  {
    id: 'c17',
    type: 'verb_conjugation',
    difficulty: 370,
    skill: 'present_simple',
    tags: ['present-simple', 'beginner'],
    data: {
      verb_base: 'like',
      target_tense: 'Present Simple',
      target_person: 'she',
      context_sentence: 'She ___ chocolate.',
      context_translation: 'היא ___ שוקולד.',
      correct_answer: 'likes',
      common_mistake: 'Add -s for he/she/it in Present Simple: "She likes" not "She like".',
    },
  },
  {
    id: 'c18',
    type: 'verb_conjugation',
    difficulty: 390,
    skill: 'present_simple',
    tags: ['present-simple', 'beginner'],
    data: {
      verb_base: 'go',
      target_tense: 'Present Simple',
      target_person: 'they',
      context_sentence: 'They ___ to the park on Sundays.',
      context_translation: 'הם ___ לפארק בימי ראשון.',
      correct_answer: 'go',
      common_mistake: 'With they/we/you/I, use the base verb: "They go" — no -s.',
    },
  },
  // ── Advanced (Tier 9–10) ────────────────────────────────────
  {
    id: 'c19',
    type: 'verb_conjugation',
    difficulty: 790,
    skill: 'past_perfect',
    tags: ['past-perfect', 'advanced'],
    data: {
      verb_base: 'finish',
      target_tense: 'Past Perfect',
      target_person: 'they',
      context_sentence: 'They ___ the project before the deadline was moved forward.',
      context_translation: 'הם ___ את הפרויקט לפני שהדדליין הוקדם.',
      correct_answer: 'had finished',
      common_mistake: 'Past Perfect: had + past participle. Use when one past action happened before another.',
    },
  },
  {
    id: 'c20',
    type: 'verb_conjugation',
    difficulty: 860,
    skill: 'passive_voice',
    tags: ['passive', 'advanced'],
    data: {
      verb_base: 'consider',
      target_tense: 'Present Perfect Passive',
      target_person: 'it',
      context_sentence: 'It ___ that the policy will be revised next quarter.',
      context_translation: '___ שהמדיניות תתוקן ברבעון הבא.',
      correct_answer: 'is considered',
      common_mistake: 'Passive reporting structure: "It is considered that…" = people consider that…',
    },
  },
  // ── Expanded pool (c21+) — was / were / had / has / have / is / are ──
  {
    id: 'c21',
    type: 'verb_conjugation',
    difficulty: 355,
    skill: 'past_simple',
    tags: ['be-verbs', 'beginner'],
    data: {
      verb_base: 'be',
      target_tense: 'Past Simple',
      target_person: 'she / he / it',
      context_sentence: 'She ___ at home yesterday evening.',
      context_translation: 'היא ___ בבית אתמול בערב.',
      correct_answer: 'was',
      common_mistake: 'Past Simple of "be": I/he/she/it → was. We/you/they → were.',
    },
  },
  {
    id: 'c22',
    type: 'verb_conjugation',
    difficulty: 365,
    skill: 'past_simple',
    tags: ['be-verbs', 'beginner'],
    data: {
      verb_base: 'be',
      target_tense: 'Past Simple',
      target_person: 'they',
      context_sentence: 'They ___ very happy at the party last night.',
      context_translation: 'הם ___ מאוד שמחים במסיבה אתמול בלילה.',
      correct_answer: 'were',
      common_mistake: 'With they/we/you use "were" in the past — never "was".',
    },
  },
  {
    id: 'c23',
    type: 'verb_conjugation',
    difficulty: 375,
    skill: 'present_simple',
    tags: ['have-verbs', 'beginner'],
    data: {
      verb_base: 'have',
      target_tense: 'Present Simple',
      target_person: 'she / he / it',
      context_sentence: 'She ___ two brothers and one sister.',
      context_translation: 'יש ___ שני אחים ואחות אחת.',
      correct_answer: 'has',
      common_mistake: '"Have" for possession: I/you/we/they → have. She/he/it → has.',
    },
  },
  {
    id: 'c24',
    type: 'verb_conjugation',
    difficulty: 385,
    skill: 'past_simple',
    tags: ['have-verbs', 'beginner'],
    data: {
      verb_base: 'have',
      target_tense: 'Past Simple',
      target_person: 'he',
      context_sentence: 'He ___ a headache yesterday, so he stayed home.',
      context_translation: 'היה ___ לו כאב ראש אתמול, אז הוא נשאר בבית.',
      correct_answer: 'had',
      common_mistake: 'Past of "have" (possession or experience) = "had" for all persons.',
    },
  },
  {
    id: 'c25',
    type: 'verb_conjugation',
    difficulty: 395,
    skill: 'past_continuous',
    tags: ['be-verbs', 'intermediate'],
    data: {
      verb_base: 'be',
      target_tense: 'Past Continuous',
      target_person: 'I',
      context_sentence: 'I ___ cooking dinner when the doorbell rang.',
      context_translation: '___ מבשל ארוחת ערב כשצלצל פעמון הדלת.',
      correct_answer: 'was',
      common_mistake: 'Past Continuous: was/were + verb-ing. With "I" use "was" — then add the main verb (-ing form follows "was").',
    },
  },
  {
    id: 'c26',
    type: 'verb_conjugation',
    difficulty: 405,
    skill: 'past_continuous',
    tags: ['be-verbs', 'intermediate'],
    data: {
      verb_base: 'be',
      target_tense: 'Past Continuous',
      target_person: 'they',
      context_sentence: 'They ___ playing football when it started to rain.',
      context_translation: 'הם ___ משחקים כדורגל כשהתחיל לרדת גשם.',
      correct_answer: 'were',
      common_mistake: 'Past Continuous with they: "were" + verb-ing. "They was playing" is wrong.',
    },
  },
  {
    id: 'c27',
    type: 'verb_conjugation',
    difficulty: 415,
    skill: 'present_perfect',
    tags: ['have-verbs', 'beginner'],
    data: {
      verb_base: 'have',
      target_tense: 'Present Perfect',
      target_person: 'I',
      context_sentence: 'I ___ finished my work for today.',
      context_translation: '___ סיימתי את העבודה שלי להיום.',
      correct_answer: 'have',
      common_mistake: 'Present Perfect auxiliary: I/you/we/they → have. She/he/it → has.',
    },
  },
  {
    id: 'c28',
    type: 'verb_conjugation',
    difficulty: 425,
    skill: 'present_perfect',
    tags: ['have-verbs', 'beginner'],
    data: {
      verb_base: 'have',
      target_tense: 'Present Perfect',
      target_person: 'she',
      context_sentence: 'She ___ never tried sushi before.',
      context_translation: 'היא ___ מעולם לא ניסתה סושי קודם.',
      correct_answer: 'has',
      common_mistake: 'With she/he/it use "has" + past participle. "Never" goes between has and the verb.',
    },
  },
  {
    id: 'c29',
    type: 'verb_conjugation',
    difficulty: 435,
    skill: 'past_perfect',
    tags: ['have-verbs', 'intermediate'],
    data: {
      verb_base: 'have',
      target_tense: 'Past Perfect',
      target_person: 'he',
      context_sentence: 'He ___ already left when I called him.',
      context_translation: 'הוא ___ כבר עזב כשהתקשרתי אליו.',
      correct_answer: 'had',
      common_mistake: 'Past Perfect: had + past participle for the earlier of two past events.',
    },
  },
  {
    id: 'c30',
    type: 'verb_conjugation',
    difficulty: 445,
    skill: 'present_simple',
    tags: ['be-verbs', 'beginner'],
    data: {
      verb_base: 'be',
      target_tense: 'Present Simple',
      target_person: 'they',
      context_sentence: 'They ___ both from the same city.',
      context_translation: 'שניהם ___ מאותה עיר.',
      correct_answer: 'are',
      common_mistake: 'Present Simple of "be": they/we/you → are. I → am. He/she/it → is.',
    },
  },
  {
    id: 'c31',
    type: 'verb_conjugation',
    difficulty: 455,
    skill: 'present_continuous',
    tags: ['be-verbs', 'beginner'],
    data: {
      verb_base: 'be',
      target_tense: 'Present Continuous',
      target_person: 'he',
      context_sentence: 'He ___ reading a book in the library right now.',
      context_translation: 'הוא ___ קורא ספר בספרייה עכשיו.',
      correct_answer: 'is',
      common_mistake: 'Present Continuous auxiliary: is/am/are + verb-ing. He → "is reading".',
    },
  },
  {
    id: 'c32',
    type: 'verb_conjugation',
    difficulty: 465,
    skill: 'present_simple',
    tags: ['have-verbs', 'beginner'],
    data: {
      verb_base: 'have',
      target_tense: 'Present Simple',
      target_person: 'we',
      context_sentence: 'We ___ a meeting every Monday morning.',
      context_translation: 'יש ___ לנו פגישה כל יום שני בבוקר.',
      correct_answer: 'have',
      common_mistake: 'With we/I/they/you use "have". "We has" is always wrong.',
    },
  },
  // ── Expanded pool (c33+) — more verbs & tenses ──
  {
    id: 'c33',
    type: 'verb_conjugation',
    difficulty: 352,
    skill: 'present_simple',
    tags: ['be-verbs', 'beginner'],
    data: {
      verb_base: 'be',
      target_tense: 'Present Simple',
      target_person: 'he / she / it',
      context_sentence: 'She ___ a doctor at the local hospital.',
      context_translation: 'היא ___ רופאה בבית החולים המקומי.',
      correct_answer: 'is',
      common_mistake: 'I → am. He/she/it → is. We/you/they → are.',
    },
  },
  {
    id: 'c34',
    type: 'verb_conjugation',
    difficulty: 358,
    skill: 'present_simple',
    tags: ['present-simple', 'beginner'],
    data: {
      verb_base: 'do',
      target_tense: 'Present Simple',
      target_person: 'he',
      context_sentence: 'He ___ his homework every evening after dinner.',
      context_translation: 'הוא ___ שיעורי בית כל ערב אחרי ארוחת הערב.',
      correct_answer: 'does',
      common_mistake: 'Irregular 3rd person: do → does. "He do" is always wrong.',
    },
  },
  {
    id: 'c35',
    type: 'verb_conjugation',
    difficulty: 362,
    skill: 'present_simple',
    tags: ['present-simple', 'beginner'],
    data: {
      verb_base: 'play',
      target_tense: 'Present Simple',
      target_person: 'she',
      context_sentence: 'She ___ tennis every Saturday with her friends.',
      context_translation: 'היא ___ טניס כל יום שבת עם החברים שלה.',
      correct_answer: 'plays',
      common_mistake: 'Regular verbs: add -s for he/she/it. play → plays.',
    },
  },
  {
    id: 'c36',
    type: 'verb_conjugation',
    difficulty: 368,
    skill: 'present_simple',
    tags: ['present-simple', 'beginner'],
    data: {
      verb_base: 'eat',
      target_tense: 'Present Simple',
      target_person: 'they',
      context_sentence: 'They ___ lunch at the café near the office.',
      context_translation: 'הם ___ צהריים בבית הקפה ליד המשרד.',
      correct_answer: 'eat',
      common_mistake: 'With they/we/you/I use the base verb — no -s.',
    },
  },
  {
    id: 'c37',
    type: 'verb_conjugation',
    difficulty: 372,
    skill: 'present_continuous',
    tags: ['present-continuous', 'beginner'],
    data: {
      verb_base: 'eat',
      target_tense: 'Present Continuous',
      target_person: 'we',
      context_sentence: 'We ___ dinner right now — can I call you back?',
      context_translation: '___ אוכלים ארוחת ערב עכשיו — אפשר שאחזור אליך?',
      correct_answer: 'are eating',
      common_mistake: 'Present Continuous: am/is/are + verb-ing. We → "are eating".',
    },
  },
  {
    id: 'c38',
    type: 'verb_conjugation',
    difficulty: 378,
    skill: 'present_continuous',
    tags: ['present-continuous', 'beginner'],
    data: {
      verb_base: 'write',
      target_tense: 'Present Continuous',
      target_person: 'she',
      context_sentence: 'She ___ an email to her manager at the moment.',
      context_translation: 'היא ___ אימייל למנהל שלה כרגע.',
      correct_answer: 'is writing',
      common_mistake: 'Drop the silent "e" before -ing: write → writing, not "writeing".',
    },
  },
  {
    id: 'c39',
    type: 'verb_conjugation',
    difficulty: 382,
    skill: 'past_simple',
    tags: ['irregular-verbs', 'beginner'],
    data: {
      verb_base: 'come',
      target_tense: 'Past Simple',
      target_person: 'he',
      context_sentence: 'He ___ home late last night.',
      context_translation: 'הוא ___ הביתה מאוחר אתמול בלילה.',
      correct_answer: 'came',
      common_mistake: 'Irregular: come → came. Never "comed".',
    },
  },
  {
    id: 'c40',
    type: 'verb_conjugation',
    difficulty: 388,
    skill: 'past_simple',
    tags: ['irregular-verbs', 'beginner'],
    data: {
      verb_base: 'drink',
      target_tense: 'Past Simple',
      target_person: 'I',
      context_sentence: 'I ___ two cups of coffee this morning.',
      context_translation: '___ שתי כוסות קפה הבוקר.',
      correct_answer: 'drank',
      common_mistake: 'Irregular: drink → drank → drunk. Past Simple is "drank".',
    },
  },
  {
    id: 'c41',
    type: 'verb_conjugation',
    difficulty: 392,
    skill: 'past_simple',
    tags: ['irregular-verbs', 'beginner'],
    data: {
      verb_base: 'think',
      target_tense: 'Past Simple',
      target_person: 'they',
      context_sentence: 'They ___ the movie was too long.',
      context_translation: 'הם ___ שהסרט היה ארוך מדי.',
      correct_answer: 'thought',
      common_mistake: 'Irregular: think → thought. Same form for all persons in Past Simple.',
    },
  },
  {
    id: 'c42',
    type: 'verb_conjugation',
    difficulty: 398,
    skill: 'past_simple',
    tags: ['irregular-verbs', 'beginner'],
    data: {
      verb_base: 'know',
      target_tense: 'Past Simple',
      target_person: 'she',
      context_sentence: 'She ___ the answer immediately.',
      context_translation: 'היא ___ את התשובה מיד.',
      correct_answer: 'knew',
      common_mistake: 'Irregular: know → knew → known. Past Simple is "knew".',
    },
  },
  {
    id: 'c43',
    type: 'verb_conjugation',
    difficulty: 402,
    skill: 'past_simple',
    tags: ['irregular-verbs', 'beginner'],
    data: {
      verb_base: 'make',
      target_tense: 'Past Simple',
      target_person: 'we',
      context_sentence: 'We ___ a cake for her birthday party.',
      context_translation: '___ עוגה למסיבת יום ההולדת שלה.',
      correct_answer: 'made',
      common_mistake: 'Irregular: make → made. Never "maked".',
    },
  },
  {
    id: 'c44',
    type: 'verb_conjugation',
    difficulty: 408,
    skill: 'past_simple',
    tags: ['irregular-verbs', 'beginner'],
    data: {
      verb_base: 'give',
      target_tense: 'Past Simple',
      target_person: 'he',
      context_sentence: 'He ___ me a book for my birthday.',
      context_translation: 'הוא ___ לי ספר ליום ההולדת.',
      correct_answer: 'gave',
      common_mistake: 'Irregular: give → gave → given. Past Simple is "gave".',
    },
  },
  {
    id: 'c45',
    type: 'verb_conjugation',
    difficulty: 412,
    skill: 'past_simple',
    tags: ['irregular-verbs', 'beginner'],
    data: {
      verb_base: 'find',
      target_tense: 'Past Simple',
      target_person: 'I',
      context_sentence: 'I ___ my keys under the sofa.',
      context_translation: '___ את המפתחות שלי מתחת לספה.',
      correct_answer: 'found',
      common_mistake: 'Irregular: find → found. Never "finded".',
    },
  },
  {
    id: 'c46',
    type: 'verb_conjugation',
    difficulty: 418,
    skill: 'past_simple',
    tags: ['irregular-verbs', 'beginner'],
    data: {
      verb_base: 'leave',
      target_tense: 'Past Simple',
      target_person: 'she',
      context_sentence: 'She ___ the office at five o\'clock yesterday.',
      context_translation: 'היא ___ מהמשרד בשעה חמש אתמול.',
      correct_answer: 'left',
      common_mistake: 'Irregular: leave → left. Never "leaved".',
    },
  },
  {
    id: 'c47',
    type: 'verb_conjugation',
    difficulty: 422,
    skill: 'past_simple',
    tags: ['irregular-verbs', 'beginner'],
    data: {
      verb_base: 'tell',
      target_tense: 'Past Simple',
      target_person: 'they',
      context_sentence: 'They ___ us about their trip to Italy.',
      context_translation: 'הם ___ לנו על הטיול שלהם לאיטליה.',
      correct_answer: 'told',
      common_mistake: 'Irregular: tell → told. Same form for all persons.',
    },
  },
  {
    id: 'c48',
    type: 'verb_conjugation',
    difficulty: 428,
    skill: 'past_continuous',
    tags: ['past-continuous', 'intermediate'],
    data: {
      verb_base: 'sleep',
      target_tense: 'Past Continuous',
      target_person: 'he',
      context_sentence: 'He ___ when the phone rang at midnight.',
      context_translation: 'הוא ___ כשהטלפון צלצל בחצות.',
      correct_answer: 'was sleeping',
      common_mistake: 'Past Continuous: was/were + verb-ing. He → "was sleeping".',
    },
  },
  {
    id: 'c49',
    type: 'verb_conjugation',
    difficulty: 432,
    skill: 'past_continuous',
    tags: ['past-continuous', 'intermediate'],
    data: {
      verb_base: 'wait',
      target_tense: 'Past Continuous',
      target_person: 'we',
      context_sentence: 'We ___ for the bus when it started to rain.',
      context_translation: '___ מחכים לאוטובוס כשהתחיל לרדת גשם.',
      correct_answer: 'were waiting',
      common_mistake: 'We/they/you → "were waiting". Drop silent "e": wait → waiting.',
    },
  },
  {
    id: 'c50',
    type: 'verb_conjugation',
    difficulty: 438,
    skill: 'past_continuous',
    tags: ['past-continuous', 'intermediate'],
    data: {
      verb_base: 'read',
      target_tense: 'Past Continuous',
      target_person: 'I',
      context_sentence: 'I ___ a novel when you knocked on the door.',
      context_translation: '___ קורא רומן כשדפקת בדלת.',
      correct_answer: 'was reading',
      common_mistake: 'Present "read" /riːd/ vs past "read" /red/ — same spelling, different sound.',
    },
  },
  {
    id: 'c51',
    type: 'verb_conjugation',
    difficulty: 442,
    skill: 'present_perfect',
    tags: ['present-perfect', 'intermediate'],
    data: {
      verb_base: 'do',
      target_tense: 'Present Perfect',
      target_person: 'I',
      context_sentence: 'I ___ my homework already — can we go out?',
      context_translation: '___ כבר את שיעורי הבית — אפשר לצאת?',
      correct_answer: 'have done',
      common_mistake: 'Irregular past participle: do → did → done. Present Perfect: have done.',
    },
  },
  {
    id: 'c52',
    type: 'verb_conjugation',
    difficulty: 448,
    skill: 'present_perfect',
    tags: ['present-perfect', 'intermediate'],
    data: {
      verb_base: 'go',
      target_tense: 'Present Perfect',
      target_person: 'she',
      context_sentence: 'She ___ to Paris three times this year.',
      context_translation: 'היא ___ לפריז שלוש פעמים השנה.',
      correct_answer: 'has gone',
      common_mistake: 'go → went → gone. Present Perfect uses "gone", not "went".',
    },
  },
  {
    id: 'c53',
    type: 'verb_conjugation',
    difficulty: 452,
    skill: 'present_perfect',
    tags: ['present-perfect', 'intermediate'],
    data: {
      verb_base: 'be',
      target_tense: 'Present Perfect',
      target_person: 'they',
      context_sentence: 'They ___ to this restaurant before — the food is great.',
      context_translation: 'הם ___ במסעדה הזו קודם — האוכל מעולה.',
      correct_answer: 'have been',
      common_mistake: 'Present Perfect of "be": have/has been. "Have been to" = visited a place.',
    },
  },
  {
    id: 'c54',
    type: 'verb_conjugation',
    difficulty: 458,
    skill: 'present_perfect',
    tags: ['present-perfect', 'intermediate'],
    data: {
      verb_base: 'write',
      target_tense: 'Present Perfect',
      target_person: 'he',
      context_sentence: 'He ___ three emails but has not received a reply yet.',
      context_translation: 'הוא ___ שלושה אימיילים אבל עדיין לא קיבל תשובה.',
      correct_answer: 'has written',
      common_mistake: 'write → wrote → written. Present Perfect: has written.',
    },
  },
  {
    id: 'c55',
    type: 'verb_conjugation',
    difficulty: 462,
    skill: 'past_perfect',
    tags: ['past-perfect', 'intermediate'],
    data: {
      verb_base: 'see',
      target_tense: 'Past Perfect',
      target_person: 'I',
      context_sentence: 'I ___ that film before, so I knew the ending.',
      context_translation: '___ את הסרט הזה קודם, אז ידעתי את הסוף.',
      correct_answer: 'had seen',
      common_mistake: 'Past Perfect: had + past participle. Earlier past event before "knew".',
    },
  },
  {
    id: 'c56',
    type: 'verb_conjugation',
    difficulty: 468,
    skill: 'past_perfect',
    tags: ['past-perfect', 'intermediate'],
    data: {
      verb_base: 'finish',
      target_tense: 'Past Perfect',
      target_person: 'she',
      context_sentence: 'She ___ the report before the meeting started.',
      context_translation: 'היא ___ את הדוח לפני שהפגישה התחילה.',
      correct_answer: 'had finished',
      common_mistake: 'Finishing happened BEFORE the meeting started — use Past Perfect.',
    },
  },
  {
    id: 'c57',
    type: 'verb_conjugation',
    difficulty: 472,
    skill: 'future_will',
    tags: ['future', 'intermediate'],
    data: {
      verb_base: 'call',
      target_tense: 'Future Simple (will)',
      target_person: 'I',
      context_sentence: 'I ___ you as soon as I arrive at the airport.',
      context_translation: '___ אותך ברגע שאגיע לשדה התעופה.',
      correct_answer: 'will call',
      common_mistake: 'Future Simple: will + base verb. Same form for all persons.',
    },
  },
  {
    id: 'c58',
    type: 'verb_conjugation',
    difficulty: 478,
    skill: 'future_going_to',
    tags: ['future', 'intermediate'],
    data: {
      verb_base: 'rain',
      target_tense: 'Future (going to)',
      target_person: 'it',
      context_sentence: 'Look at those clouds — it ___ soon.',
      context_translation: 'תסתכל על העננים האלה — ___ לרדת גשם בקרוב.',
      correct_answer: 'is going to rain',
      common_mistake: 'Going to + base verb. With "it": "it is going to rain".',
    },
  },
  {
    id: 'c59',
    type: 'verb_conjugation',
    difficulty: 482,
    skill: 'modal_verbs',
    tags: ['modals', 'beginner'],
    data: {
      verb_base: 'can',
      target_tense: 'Modal (ability)',
      target_person: 'she',
      context_sentence: 'She ___ speak three languages fluently.',
      context_translation: 'היא ___ לדבר שלוש שפות בצורה שוטפת.',
      correct_answer: 'can',
      common_mistake: 'Modal verbs are followed by base verb — no "to": "can speak" not "can to speak".',
    },
  },
  {
    id: 'c60',
    type: 'verb_conjugation',
    difficulty: 488,
    skill: 'modal_verbs',
    tags: ['modals', 'intermediate'],
    data: {
      verb_base: 'can',
      target_tense: 'Modal (past ability)',
      target_person: 'he',
      context_sentence: 'When he was young, he ___ swim very well.',
      context_translation: 'כשהיה צעיר, הוא ___ לשחות מאוד טוב.',
      correct_answer: 'could',
      common_mistake: 'Past ability: "could" (not "can"). "Could swim" = was able to swim.',
    },
  },
  {
    id: 'c61',
    type: 'verb_conjugation',
    difficulty: 492,
    skill: 'past_simple',
    tags: ['regular-verbs', 'beginner'],
    data: {
      verb_base: 'walk',
      target_tense: 'Past Simple',
      target_person: 'they',
      context_sentence: 'They ___ to school every day last year.',
      context_translation: 'הם ___ לבית הספר כל יום בשנה שעברה.',
      correct_answer: 'walked',
      common_mistake: 'Regular verbs: add -ed for Past Simple. walk → walked.',
    },
  },
  {
    id: 'c62',
    type: 'verb_conjugation',
    difficulty: 498,
    skill: 'past_simple',
    tags: ['regular-verbs', 'beginner'],
    data: {
      verb_base: 'help',
      target_tense: 'Past Simple',
      target_person: 'she',
      context_sentence: 'She ___ her mother cook dinner yesterday.',
      context_translation: 'היא ___ לאמא שלה לבשל ארוחת ערב אתמול.',
      correct_answer: 'helped',
      common_mistake: 'Regular verbs ending in -p: add -ed → helped.',
    },
  },
  {
    id: 'c63',
    type: 'verb_conjugation',
    difficulty: 505,
    skill: 'present_perfect',
    tags: ['present-perfect', 'intermediate'],
    data: {
      verb_base: 'live',
      target_tense: 'Present Perfect',
      target_person: 'we',
      context_sentence: 'We ___ in this neighbourhood for ten years.',
      context_translation: '___ בשכונה הזו כבר עשר שנים.',
      correct_answer: 'have lived',
      common_mistake: '"For ten years" + still living there → Present Perfect: have lived.',
    },
  },
  {
    id: 'c64',
    type: 'verb_conjugation',
    difficulty: 512,
    skill: 'passive_voice',
    tags: ['passive', 'intermediate'],
    data: {
      verb_base: 'build',
      target_tense: 'Past Simple Passive',
      target_person: 'it',
      context_sentence: 'The bridge ___ in nineteen eighty-five.',
      context_translation: 'הגשר ___ ב-1985.',
      correct_answer: 'was built',
      common_mistake: 'Past passive: was/were + past participle. build → built (irregular).',
    },
  },
  {
    id: 'c65',
    type: 'verb_conjugation',
    difficulty: 518,
    skill: 'past_simple',
    tags: ['irregular-verbs', 'intermediate'],
    data: {
      verb_base: 'feel',
      target_tense: 'Past Simple',
      target_person: 'I',
      context_sentence: 'I ___ nervous before the job interview.',
      context_translation: '___ לחוץ לפני ראיון העבודה.',
      correct_answer: 'felt',
      common_mistake: 'Irregular: feel → felt. Never "feeled".',
    },
  },
  {
    id: 'c66',
    type: 'verb_conjugation',
    difficulty: 525,
    skill: 'past_simple',
    tags: ['irregular-verbs', 'intermediate'],
    data: {
      verb_base: 'get',
      target_tense: 'Past Simple',
      target_person: 'they',
      context_sentence: 'They ___ lost on the way to the museum.',
      context_translation: 'הם ___ אבודים בדרך למוזיאון.',
      correct_answer: 'got',
      common_mistake: 'Irregular: get → got → gotten/got. Past Simple is "got" (UK also uses "gotten" in US).',
    },
  },
  {
    id: 'c67',
    type: 'verb_conjugation',
    difficulty: 532,
    skill: 'present_continuous',
    tags: ['present-continuous', 'beginner'],
    data: {
      verb_base: 'sit',
      target_tense: 'Present Continuous',
      target_person: 'they',
      context_sentence: 'They ___ in the front row at the concert.',
      context_translation: 'הם ___ בשורה הראשונה בקונצרט.',
      correct_answer: 'are sitting',
      common_mistake: 'Double the consonant: sit → sitting. They → "are sitting".',
    },
  },
  {
    id: 'c68',
    type: 'verb_conjugation',
    difficulty: 538,
    skill: 'past_perfect',
    tags: ['past-perfect', 'intermediate'],
    data: {
      verb_base: 'eat',
      target_tense: 'Past Perfect',
      target_person: 'they',
      context_sentence: 'They ___ already eaten when we arrived for dinner.',
      context_translation: 'הם ___ כבר כשהגענו לארוחת הערב.',
      correct_answer: 'had eaten',
      common_mistake: 'Eating finished before arrival — Past Perfect: had eaten.',
    },
  },
]
