import type { ContentItem } from '@/types/game'

export const CONJUGATION_ITEMS: ContentItem[] = [
  // ── Past Simple (irregular) ───────────────────────────────
  {
    id: 'c1',
    type: 'verb_conjugation',
    difficulty: 380,
    skill: 'past_simple',
    tags: ['irregular-verbs', 'beginner'],
    data: {
      verb_base: 'go',
      target_tense: 'Past Simple',
      target_person: 'she / he / it',
      context_sentence: 'Yesterday, she ___ to the market.',
      context_translation: 'אתמול, היא ___ לשוק.',
      correct_answer: 'went',
      common_mistake: '"Go" is irregular. Past Simple: go → went. Never "goed."',
    },
  },
  {
    id: 'c2',
    type: 'verb_conjugation',
    difficulty: 390,
    skill: 'past_simple',
    tags: ['irregular-verbs', 'beginner'],
    data: {
      verb_base: 'buy',
      target_tense: 'Past Simple',
      target_person: 'they',
      context_sentence: 'They ___ a new car last month.',
      context_translation: 'הם ___ מכונית חדשה בחודש שעבר.',
      correct_answer: 'bought',
      common_mistake: '"Buy" is irregular. Past Simple: buy → bought. Rhymes with "thought" and "caught."',
    },
  },
  {
    id: 'c3',
    type: 'verb_conjugation',
    difficulty: 400,
    skill: 'past_simple',
    tags: ['irregular-verbs', 'beginner'],
    data: {
      verb_base: 'write',
      target_tense: 'Past Simple',
      target_person: 'I',
      context_sentence: 'I ___ a letter to my friend.',
      context_translation: 'כתבתי מכתב לחברי.',
      correct_answer: 'wrote',
      common_mistake: '"Write" is irregular: write → wrote → written. Past Simple is "wrote" (no "d" or "ed").',
    },
  },
  {
    id: 'c4',
    type: 'verb_conjugation',
    difficulty: 410,
    skill: 'past_simple',
    tags: ['irregular-verbs', 'beginner'],
    data: {
      verb_base: 'take',
      target_tense: 'Past Simple',
      target_person: 'we',
      context_sentence: 'We ___ the train to the city centre.',
      context_translation: 'לקחנו את הרכבת למרכז העיר.',
      correct_answer: 'took',
      common_mistake: '"Take" is irregular: take → took → taken. Past Simple is "took."',
    },
  },
  {
    id: 'c5',
    type: 'verb_conjugation',
    difficulty: 430,
    skill: 'past_simple',
    tags: ['irregular-verbs', 'beginner'],
    data: {
      verb_base: 'speak',
      target_tense: 'Past Simple',
      target_person: 'he',
      context_sentence: 'He ___ to the manager about the problem.',
      context_translation: 'הוא ___ עם המנהל על הבעיה.',
      correct_answer: 'spoke',
      common_mistake: '"Speak" is irregular: speak → spoke → spoken. Do not say "speaked."',
    },
  },
  // ── Present Perfect ───────────────────────────────────────
  {
    id: 'c6',
    type: 'verb_conjugation',
    difficulty: 450,
    skill: 'present_perfect',
    tags: ['present-perfect', 'beginner'],
    data: {
      verb_base: 'see',
      target_tense: 'Present Perfect',
      target_person: 'I',
      context_sentence: 'I ___ that film three times already.',
      context_translation: 'כבר ___ את הסרט הזה שלוש פעמים.',
      correct_answer: 'have seen',
      common_mistake: '"See" irregular past participle: see → saw → seen. Present Perfect: have/has + seen.',
    },
  },
  {
    id: 'c7',
    type: 'verb_conjugation',
    difficulty: 470,
    skill: 'present_perfect',
    tags: ['present-perfect'],
    data: {
      verb_base: 'eat',
      target_tense: 'Present Perfect',
      target_person: 'she',
      context_sentence: 'She ___ sushi many times — she loves Japanese food.',
      context_translation: 'היא ___ סושי הרבה פעמים — היא אוהבת אוכל יפני.',
      correct_answer: 'has eaten',
      common_mistake: '"Eat" irregular: eat → ate → eaten. With "she/he/it" use "has eaten", not "have eaten."',
    },
  },
  {
    id: 'c8',
    type: 'verb_conjugation',
    difficulty: 490,
    skill: 'present_perfect',
    tags: ['present-perfect', 'intermediate'],
    data: {
      verb_base: 'break',
      target_tense: 'Present Perfect',
      target_person: 'they',
      context_sentence: 'They ___ the record for the fastest marathon time.',
      context_translation: 'הם ___ את השיא לזמן המרתון המהיר ביותר.',
      correct_answer: 'have broken',
      common_mistake: '"Break" irregular: break → broke → broken. Present Perfect uses "broken" (past participle), not "broke."',
    },
  },
  // ── Present Simple (3rd person) ───────────────────────────
  {
    id: 'c9',
    type: 'verb_conjugation',
    difficulty: 360,
    skill: 'present_simple',
    tags: ['present-simple', 'beginner'],
    data: {
      verb_base: 'study',
      target_tense: 'Present Simple',
      target_person: 'she / he / it',
      context_sentence: 'She ___ English every evening.',
      context_translation: 'היא ___ אנגלית כל ערב.',
      correct_answer: 'studies',
      common_mistake: 'Verbs ending in consonant + y: change "y" to "i" and add "-es". study → studies, carry → carries.',
    },
  },
  {
    id: 'c10',
    type: 'verb_conjugation',
    difficulty: 370,
    skill: 'present_simple',
    tags: ['present-simple', 'beginner'],
    data: {
      verb_base: 'watch',
      target_tense: 'Present Simple',
      target_person: 'he',
      context_sentence: 'He ___ the news every morning before breakfast.',
      context_translation: 'הוא ___ חדשות כל בוקר לפני ארוחת הבוקר.',
      correct_answer: 'watches',
      common_mistake: 'Verbs ending in -ch, -sh, -x, -ss, -o add "-es": watch → watches, finish → finishes.',
    },
  },
  // ── Future (will / going to) ──────────────────────────────
  {
    id: 'c11',
    type: 'verb_conjugation',
    difficulty: 440,
    skill: 'future_will',
    tags: ['future', 'intermediate'],
    data: {
      verb_base: 'be',
      target_tense: 'Future Simple (will)',
      target_person: 'they',
      context_sentence: 'The results ___ announced at the end of the week.',
      context_translation: 'התוצאות ___ יוכרזו בסוף השבוע.',
      correct_answer: 'will be',
      common_mistake: 'This is passive future: "will be + past participle (announced)." Just conjugate "be" with "will" here.',
    },
  },
  {
    id: 'c12',
    type: 'verb_conjugation',
    difficulty: 460,
    skill: 'future_going_to',
    tags: ['future', 'intermediate'],
    data: {
      verb_base: 'travel',
      target_tense: 'Future (going to)',
      target_person: 'we',
      context_sentence: 'We ___ to Argentina next spring.',
      context_translation: 'אנחנו ___ לארגנטינה באביב הבא.',
      correct_answer: 'are going to travel',
      common_mistake: '"Going to" + base verb. With "we": "we are going to travel." Indicates a planned decision.',
    },
  },
  // ── Past Continuous ───────────────────────────────────────
  {
    id: 'c13',
    type: 'verb_conjugation',
    difficulty: 500,
    skill: 'past_continuous',
    tags: ['past-continuous', 'intermediate'],
    data: {
      verb_base: 'work',
      target_tense: 'Past Continuous',
      target_person: 'she',
      context_sentence: 'She ___ on the presentation when the power cut off.',
      context_translation: 'היא ___ על המצגת כשהחשמל נכבה.',
      correct_answer: 'was working',
      common_mistake: 'Past Continuous: was/were + verb-ing. Describes an ongoing past action interrupted by another event.',
    },
  },
  {
    id: 'c14',
    type: 'verb_conjugation',
    difficulty: 520,
    skill: 'past_continuous',
    tags: ['past-continuous', 'intermediate'],
    data: {
      verb_base: 'listen',
      target_tense: 'Past Continuous',
      target_person: 'they',
      context_sentence: 'They ___ to music when I arrived.',
      context_translation: 'הם ___ למוזיקה כשהגעתי.',
      correct_answer: 'were listening',
      common_mistake: 'With "they/we/you", use "were + -ing". With "I/she/he/it", use "was + -ing."',
    },
  },
  // ── Present Continuous ────────────────────────────────────
  {
    id: 'c15',
    type: 'verb_conjugation',
    difficulty: 390,
    skill: 'present_continuous',
    tags: ['present-continuous', 'beginner'],
    data: {
      verb_base: 'run',
      target_tense: 'Present Continuous',
      target_person: 'he',
      context_sentence: 'Look! He ___ towards the finish line.',
      context_translation: 'תסתכל! הוא ___ לקראת קו הסיום.',
      correct_answer: 'is running',
      common_mistake: 'Double the final consonant before adding -ing for short vowel + consonant verbs: run → running, sit → sitting.',
    },
  },
  // ── Beginner (Tier 1) ─────────────────────────────────────
  {
    id: 'c16',
    type: 'verb_conjugation',
    difficulty: 350,
    skill: 'present_simple',
    tags: ['present-simple', 'beginner'],
    data: {
      verb_base: 'be',
      target_tense: 'Present Simple',
      target_person: 'I',
      context_sentence: 'I ___ a student.',
      context_translation: 'אני ___ תלמיד.',
      correct_answer: 'am',
      common_mistake: 'Use "am" with "I", "is" with he/she/it, "are" with you/we/they.',
    },
  },
  {
    id: 'c17',
    type: 'verb_conjugation',
    difficulty: 370,
    skill: 'present_simple',
    tags: ['present-simple', 'beginner'],
    data: {
      verb_base: 'like',
      target_tense: 'Present Simple',
      target_person: 'she',
      context_sentence: 'She ___ chocolate.',
      context_translation: 'היא ___ שוקולד.',
      correct_answer: 'likes',
      common_mistake: 'Add -s for he/she/it in Present Simple: "She likes" not "She like".',
    },
  },
  {
    id: 'c18',
    type: 'verb_conjugation',
    difficulty: 390,
    skill: 'present_simple',
    tags: ['present-simple', 'beginner'],
    data: {
      verb_base: 'go',
      target_tense: 'Present Simple',
      target_person: 'they',
      context_sentence: 'They ___ to the park on Sundays.',
      context_translation: 'הם ___ לפארק בימי ראשון.',
      correct_answer: 'go',
      common_mistake: 'With they/we/you/I, use the base verb: "They go" — no -s.',
    },
  },
  // ── Advanced (Tier 9–10) ────────────────────────────────────
  {
    id: 'c19',
    type: 'verb_conjugation',
    difficulty: 790,
    skill: 'past_perfect',
    tags: ['past-perfect', 'advanced'],
    data: {
      verb_base: 'finish',
      target_tense: 'Past Perfect',
      target_person: 'they',
      context_sentence: 'They ___ the project before the deadline was moved forward.',
      context_translation: 'הם ___ את הפרויקט לפני שהדדליין הוקדם.',
      correct_answer: 'had finished',
      common_mistake: 'Past Perfect: had + past participle. Use when one past action happened before another.',
    },
  },
  {
    id: 'c20',
    type: 'verb_conjugation',
    difficulty: 860,
    skill: 'passive_voice',
    tags: ['passive', 'advanced'],
    data: {
      verb_base: 'consider',
      target_tense: 'Present Perfect Passive',
      target_person: 'it',
      context_sentence: 'It ___ that the policy will be revised next quarter.',
      context_translation: '___ שהמדיניות תתוקן ברבעון הבא.',
      correct_answer: 'is considered',
      common_mistake: 'Passive reporting structure: "It is considered that…" = people consider that…',
    },
  },
]
