import type { ContentItem } from '@/types/game'

export const GRAMMAR_ITEMS: ContentItem[] = [
  // ── Present Perfect ───────────────────────────────────────
  {
    id: 'g1',
    type: 'grammar_choice',
    difficulty: 450,
    skill: 'present_perfect',
    tags: ['tenses', 'present-perfect', 'beginner'],
    data: {
      question_text: 'Choose the correct verb form:',
      context_sentence: 'She ___ in London for five years.',
      context_translation: 'היא ___ בלונדון כבר חמש שנים.',
      options: ['has lived', 'is living', 'lived', 'was living'],
      correct_answer: 'has lived',
      grammar_hint: 'Use Present Perfect ("has/have + past participle") for actions that started in the past and continue to the present. "For five years" signals duration up to now.',
      common_mistake: 'Do not use Past Simple here — "She lived in London for five years" implies she no longer does.',
    },
  },
  {
    id: 'g2',
    type: 'grammar_choice',
    difficulty: 490,
    skill: 'present_perfect',
    tags: ['tenses', 'present-perfect'],
    data: {
      question_text: 'Which sentence is correct?',
      context_sentence: 'They ___ the project yet.',
      context_translation: 'הם ___ את הפרויקט עדיין.',
      options: ["haven't finished", "didn't finish", "don't finish", "weren't finishing"],
      correct_answer: "haven't finished",
      grammar_hint: '"Yet" is a signal word for the Present Perfect when used in negatives and questions. It means "up to now."',
      common_mistake: '"Didn\'t finish yet" is wrong — "yet" requires Present Perfect in standard British/American English.',
    },
  },
  {
    id: 'g3',
    type: 'grammar_choice',
    difficulty: 530,
    skill: 'present_perfect',
    tags: ['tenses', 'present-perfect', 'intermediate'],
    data: {
      question_text: 'Select the best option:',
      context_sentence: 'This is the most interesting book I ___ in years.',
      context_translation: 'זה הספר המעניין ביותר שאני ___ בשנים.',
      options: ['have read', 'read', 'was reading', 'am reading'],
      correct_answer: 'have read',
      grammar_hint: 'After superlatives ("most interesting", "best", "worst"), use the Present Perfect to describe a personal experience.',
      common_mistake: 'With superlatives comparing experiences, Present Perfect is standard, not Past Simple.',
    },
  },
  // ── Past Simple ───────────────────────────────────────────
  {
    id: 'g4',
    type: 'grammar_choice',
    difficulty: 420,
    skill: 'past_simple',
    tags: ['tenses', 'past-simple', 'beginner'],
    data: {
      question_text: 'Choose the correct form:',
      context_sentence: 'She ___ her keys when she left the house.',
      context_translation: 'היא ___ את המפתחות שלה כשיצאה מהבית.',
      options: ['forgot', 'has forgotten', 'was forgetting', 'forget'],
      correct_answer: 'forgot',
      grammar_hint: 'Use Past Simple for a completed action at a specific moment in the past. "When she left" anchors the action to a point in time.',
      common_mistake: '"When" followed by a past action usually calls for Past Simple, not Present Perfect.',
    },
  },
  {
    id: 'g5',
    type: 'grammar_choice',
    difficulty: 460,
    skill: 'past_simple',
    tags: ['tenses', 'past-simple'],
    data: {
      question_text: 'Fill in the blank:',
      context_sentence: 'Last summer, we ___ in a small cabin by the lake for two weeks.',
      context_translation: 'בקיץ שעבר, ___ בצריף קטן ליד האגם במשך שבועיים.',
      options: ['stayed', 'have stayed', 'were staying', 'stay'],
      correct_answer: 'stayed',
      grammar_hint: '"Last summer" is a finished time period — use Past Simple. Time phrases like "yesterday", "last year", "in 2020" always go with Past Simple.',
      common_mistake: 'Never use Present Perfect with a specific finished time expression like "last summer."',
    },
  },
  // ── Conditionals ──────────────────────────────────────────
  {
    id: 'g6',
    type: 'grammar_choice',
    difficulty: 500,
    skill: 'conditionals',
    tags: ['conditionals', 'intermediate'],
    data: {
      question_text: 'Which option correctly completes the sentence?',
      context_sentence: 'If I ___ more time, I would travel the world.',
      context_translation: 'אם היה לי יותר זמן, הייתי מטייל בעולם.',
      options: ['had', 'have', 'will have', 'would have'],
      correct_answer: 'had',
      grammar_hint: 'Second Conditional (hypothetical/unreal present): "If + past simple, would + base verb." Use "had" here — it signals this is imaginary, not real.',
      common_mistake: 'Never use "would" in the if-clause: NOT "If I would have time."',
    },
  },
  {
    id: 'g7',
    type: 'grammar_choice',
    difficulty: 560,
    skill: 'conditionals',
    tags: ['conditionals', 'advanced'],
    data: {
      question_text: 'Choose the correct third conditional:',
      context_sentence: 'If she ___ the warning, she would have avoided the accident.',
      context_translation: 'אם היא ___ את האזהרה, היא הייתה נמנעת מהתאונה.',
      options: ['had heeded', 'heeded', 'would heed', 'has heeded'],
      correct_answer: 'had heeded',
      grammar_hint: 'Third Conditional (unreal past): "If + past perfect, would have + past participle." The action cannot be changed now.',
      common_mistake: 'Do not mix up tenses: the if-clause needs "had + past participle", the result needs "would have + past participle."',
    },
  },
  {
    id: 'g8',
    type: 'grammar_choice',
    difficulty: 540,
    skill: 'conditionals',
    tags: ['conditionals', 'intermediate'],
    data: {
      question_text: 'Which is the first conditional?',
      context_sentence: 'If you ___ hard enough, you will pass the exam.',
      context_translation: 'אם תתאמן ___ מספיק קשה, תעבור את הבחינה.',
      options: ['study', 'studied', 'will study', 'would study'],
      correct_answer: 'study',
      grammar_hint: 'First Conditional (real/possible future): "If + present simple, will + base verb." The situation is possible.',
      common_mistake: 'Do NOT use "will" in the if-clause of first conditionals: NOT "If you will study."',
    },
  },
  // ── Passive Voice ─────────────────────────────────────────
  {
    id: 'g9',
    type: 'grammar_choice',
    difficulty: 550,
    skill: 'passive_voice',
    tags: ['passive', 'intermediate'],
    data: {
      question_text: 'Select the grammatically correct option:',
      context_sentence: 'The annual report ___ by the finance team last week.',
      context_translation: 'הדוח השנתי ___ על ידי צוות הכספים בשבוע שעבר.',
      options: ['was prepared', 'prepared', 'has been prepared', 'is prepared'],
      correct_answer: 'was prepared',
      grammar_hint: 'Passive voice in past simple: "was/were + past participle." The phrase "last week" confirms we need a past tense.',
      common_mistake: '"Has been prepared" would mean the action was recently completed with a present-time relevance — "last week" rules this out.',
    },
  },
  {
    id: 'g10',
    type: 'grammar_choice',
    difficulty: 590,
    skill: 'passive_voice',
    tags: ['passive', 'advanced'],
    data: {
      question_text: 'Choose the correct passive form:',
      context_sentence: 'A new hospital ___ in the city centre by the end of next year.',
      context_translation: 'בית חולים חדש ___ במרכז העיר עד סוף השנה הבאה.',
      options: ['will have been built', 'will build', 'will be built', 'is being built'],
      correct_answer: 'will be built',
      grammar_hint: 'Future passive: "will be + past participle." Use for an action that will happen to the subject in the future.',
      common_mistake: '"Will have been built" (future perfect passive) would be needed only if you specify a deadline by which it must be complete. Here the phrase "by the end of next year" indicates a simple planned future event.',
    },
  },
  // ── Articles ──────────────────────────────────────────────
  {
    id: 'g11',
    type: 'grammar_choice',
    difficulty: 440,
    skill: 'articles',
    tags: ['articles', 'beginner'],
    data: {
      question_text: 'Which article best fills the gap?',
      context_sentence: 'She is ___ honest person who always tells the truth.',
      context_translation: 'היא ___ אדם ישר שתמיד אומר את האמת.',
      options: ['an', 'a', 'the', 'no article needed'],
      correct_answer: 'an',
      grammar_hint: 'Use "an" before words beginning with a vowel SOUND. "Honest" starts with a silent "h," so it sounds like it starts with "o" — use "an."',
      common_mistake: 'The rule is about the SOUND, not the spelling. "A uniform" is correct because /juːnɪfɔːm/ starts with a "y" sound.',
    },
  },
  {
    id: 'g12',
    type: 'grammar_choice',
    difficulty: 480,
    skill: 'articles',
    tags: ['articles'],
    data: {
      question_text: 'Choose the correct article (or no article):',
      context_sentence: '___ money does not guarantee happiness.',
      context_translation: '___ כסף אינו מבטיח אושר.',
      options: ['no article', 'The', 'A', 'An'],
      correct_answer: 'no article',
      grammar_hint: 'When talking about something in general (uncountable nouns like "money", "love", "happiness"), use no article.',
      common_mistake: '"The money" would refer to specific money already mentioned. No article means "money in general."',
    },
  },
  {
    id: 'g13',
    type: 'grammar_choice',
    difficulty: 520,
    skill: 'articles',
    tags: ['articles', 'intermediate'],
    data: {
      question_text: 'Select the correct sentence:',
      context_sentence: 'We visited ___ Eiffel Tower during our trip to Paris.',
      context_translation: 'ביקרנו ב ___ מגדל אייפל במהלך הטיול שלנו בפריז.',
      options: ['the', 'a', 'an', 'no article'],
      correct_answer: 'the',
      grammar_hint: 'Use "the" with unique landmarks and specific places. There is only one Eiffel Tower, so it is already specific.',
      common_mistake: '"A Eiffel Tower" is wrong — use "the" for famous, unique places.',
    },
  },
  // ── Modal Verbs ───────────────────────────────────────────
  {
    id: 'g14',
    type: 'grammar_choice',
    difficulty: 470,
    skill: 'modal_verbs',
    tags: ['modals', 'beginner'],
    data: {
      question_text: 'Choose the best modal verb:',
      context_sentence: 'You ___ wear a helmet when cycling — it is the law.',
      context_translation: 'אתה ___ לחבוש קסדה בזמן רכיבה על אופניים — זה חוק.',
      options: ['must', 'should', 'might', 'could'],
      correct_answer: 'must',
      grammar_hint: '"Must" expresses a legal or strong external obligation. "Should" is a recommendation. When there is a law, use "must."',
      common_mistake: '"Should" is advisory. "Must" is obligatory. If you break the law, "must" was the right choice.',
    },
  },
  {
    id: 'g15',
    type: 'grammar_choice',
    difficulty: 540,
    skill: 'modal_verbs',
    tags: ['modals', 'intermediate'],
    data: {
      question_text: 'Choose the best modal for this context:',
      context_sentence: 'She ___ be at home — her car is in the driveway.',
      context_translation: 'היא ___ להיות בבית — המכונית שלה בחניה.',
      options: ['must', 'should', 'will', 'would'],
      correct_answer: 'must',
      grammar_hint: '"Must" is also used for logical deductions based on evidence. The car in the driveway is the evidence.',
      common_mistake: '"Should" implies expectation based on schedule. "Must" implies deduction from evidence — completely different meanings.',
    },
  },
  {
    id: 'g16',
    type: 'grammar_choice',
    difficulty: 610,
    skill: 'modal_verbs',
    tags: ['modals', 'advanced'],
    data: {
      question_text: 'Which sentence expresses a past ability?',
      context_sentence: 'When he was young, he ___ run a marathon without stopping.',
      context_translation: 'כשהיה צעיר, הוא ___ לרוץ מרתון ללא עצירה.',
      options: ['could', 'would', 'must have', 'should have'],
      correct_answer: 'could',
      grammar_hint: '"Could" expresses past ability (what someone was able to do). "Would" refers to past habits. "Must have" is a past deduction.',
      common_mistake: '"Would run a marathon" implies habitual action — he did it regularly. "Could run" means he had the ability (even once).',
    },
  },
  // ── Prepositions ──────────────────────────────────────────
  {
    id: 'g17',
    type: 'grammar_choice',
    difficulty: 430,
    skill: 'prepositions',
    tags: ['prepositions', 'beginner'],
    data: {
      question_text: 'Choose the correct preposition:',
      context_sentence: 'The meeting is scheduled ___ Monday at 9 a.m.',
      context_translation: 'הישיבה מתוכננת ___ יום שני בשעה 9 בבוקר.',
      options: ['on', 'at', 'in', 'by'],
      correct_answer: 'on',
      grammar_hint: 'Use "on" for days of the week (on Monday), dates (on 5th March), and specific days (on New Year\'s Day).',
      common_mistake: '"At" is for clock times, "in" is for months/years/seasons. "On" is for days.',
    },
  },
  {
    id: 'g18',
    type: 'grammar_choice',
    difficulty: 500,
    skill: 'prepositions',
    tags: ['prepositions'],
    data: {
      question_text: 'Select the correct preposition:',
      context_sentence: 'She has been working ___ this company since 2019.',
      context_translation: 'היא עובדת ב ___ חברה זו מאז 2019.',
      options: ['for', 'at', 'to', 'with'],
      correct_answer: 'for',
      grammar_hint: 'Use "for" to describe how long something has continued. Use "at" or "with" to describe where you work.',
      common_mistake: '"Working at this company" is also possible, but the blank precedes "this company" here, not a time duration, so "for" fits the sentence.',
    },
  },
  // ── Phrasal Verbs ─────────────────────────────────────────
  {
    id: 'g19',
    type: 'grammar_choice',
    difficulty: 510,
    skill: 'phrasal_verbs',
    tags: ['phrasal-verbs', 'intermediate'],
    data: {
      question_text: 'Choose the phrasal verb that fits the context:',
      context_sentence: 'He could not ___ the difficult maths problem no matter how hard he tried.',
      context_translation: 'הוא לא הצליח ___ את בעיית המתמטיקה הקשה לא משנה כמה קשה ניסה.',
      options: ['figure out', 'look up', 'put off', 'give in'],
      correct_answer: 'figure out',
      grammar_hint: '"Figure out" = to understand or solve something. "Look up" = to search for information. "Put off" = to delay. "Give in" = to surrender.',
      common_mistake: '"Figure out" is separable: "figure it out" is also correct.',
    },
  },
  {
    id: 'g20',
    type: 'grammar_choice',
    difficulty: 570,
    skill: 'phrasal_verbs',
    tags: ['phrasal-verbs', 'intermediate'],
    data: {
      question_text: 'Which phrasal verb means "to cancel a plan"?',
      context_sentence: 'We had to ___ the outdoor concert because of the heavy rain.',
      context_translation: 'נאלצנו ___ את הקונצרט בחוץ בגלל הגשם הכבד.',
      options: ['call off', 'call up', 'put on', 'get through'],
      correct_answer: 'call off',
      grammar_hint: '"Call off" means to cancel an event. "Call up" = to phone someone. "Put on" = to wear or organize.',
      common_mistake: '"Cancel" and "call off" are interchangeable, but "call off" is more informal.',
    },
  },
  // ── Comparison ────────────────────────────────────────────
  {
    id: 'g21',
    type: 'grammar_choice',
    difficulty: 440,
    skill: 'comparison',
    tags: ['comparison', 'beginner'],
    data: {
      question_text: 'Choose the correct comparative:',
      context_sentence: 'The new office building is ___ than the old one.',
      context_translation: 'בניין המשרדים החדש ___ מהישן.',
      options: ['more modern', 'moderner', 'most modern', 'much modern'],
      correct_answer: 'more modern',
      grammar_hint: 'For adjectives with two or more syllables, use "more + adjective" for comparatives, not "-er".',
      common_mistake: '"Moderner" is not a word. Three-syllable adjectives always use "more/most."',
    },
  },
  {
    id: 'g22',
    type: 'grammar_choice',
    difficulty: 520,
    skill: 'comparison',
    tags: ['comparison', 'intermediate'],
    data: {
      question_text: 'Select the correct sentence:',
      context_sentence: 'This is ___ meal I have ever tasted.',
      context_translation: 'זה ___ ארוחה שטעמתי אי פעם.',
      options: ['the most delicious', 'the more delicious', 'most delicious', 'the deliciouser'],
      correct_answer: 'the most delicious',
      grammar_hint: 'Superlatives need "the" before them: "the most + adjective" or "the + adjective + -est". Never "the more" for superlatives.',
      common_mistake: 'Always include "the" before a superlative when referring to a specific instance.',
    },
  },
  // ── Relative Clauses ──────────────────────────────────────
  {
    id: 'g23',
    type: 'grammar_choice',
    difficulty: 560,
    skill: 'relative_clauses',
    tags: ['relative-clauses', 'intermediate'],
    data: {
      question_text: 'Which relative pronoun is correct?',
      context_sentence: 'The scientist ___ discovered penicillin changed medicine forever.',
      context_translation: 'המדען ___ גילה את הפניצילין שינה את הרפואה לנצח.',
      options: ['who', 'which', 'whose', 'whom'],
      correct_answer: 'who',
      grammar_hint: 'Use "who" for people as the subject of the relative clause. Use "which" for things. Use "whose" for possession.',
      common_mistake: '"Which" is for things, not people. Always use "who" or "whom" when the antecedent is a person.',
    },
  },
  {
    id: 'g24',
    type: 'grammar_choice',
    difficulty: 620,
    skill: 'relative_clauses',
    tags: ['relative-clauses', 'advanced'],
    data: {
      question_text: 'Choose the correct relative pronoun:',
      context_sentence: 'The report, ___ findings were surprising, was published last month.',
      context_translation: 'הדו"ח, ___ ממצאיו היו מפתיעים, פורסם בחודש שעבר.',
      options: ['whose', 'which', 'who', 'that'],
      correct_answer: 'whose',
      grammar_hint: '"Whose" shows possession. The report has/owns the findings. "The report whose findings" = "the findings of the report."',
      common_mistake: '"Which findings" would make it an additional clause, not possessive. "Whose" is the possessive relative pronoun for both people and things.',
    },
  },
  // ── Reported Speech ──────────────────────────────────────
  {
    id: 'g25',
    type: 'grammar_choice',
    difficulty: 600,
    skill: 'reported_speech',
    tags: ['reported-speech', 'advanced'],
    data: {
      question_text: 'Convert to reported speech. He said: "I will finish the report tomorrow."',
      context_sentence: 'He said that he ___ the report the following day.',
      context_translation: 'הוא אמר שהוא ___ את הדו"ח למחרת.',
      options: ['would finish', 'will finish', 'finished', 'had finished'],
      correct_answer: 'would finish',
      grammar_hint: 'In reported speech, "will" shifts back to "would." Time references also shift: "tomorrow" becomes "the following day."',
      common_mistake: '"Will" is direct speech. In reported speech after a past verb ("said"), always shift "will" → "would."',
    },
  },
  // ── Present Continuous ────────────────────────────────────
  {
    id: 'g26',
    type: 'grammar_choice',
    difficulty: 410,
    skill: 'present_continuous',
    tags: ['tenses', 'present-continuous', 'beginner'],
    data: {
      question_text: 'Choose the correct tense:',
      context_sentence: 'Right now, the engineers ___ the software for the new feature.',
      context_translation: 'כרגע, המהנדסים ___ את התוכנה לתכונה החדשה.',
      options: ['are testing', 'test', 'have tested', 'tested'],
      correct_answer: 'are testing',
      grammar_hint: '"Right now" signals an action happening at this exact moment — use Present Continuous (am/is/are + -ing).',
      common_mistake: 'Present Simple ("test") describes general habits. Present Continuous describes what is happening at this moment.',
    },
  },
]
