import type { ContentItem } from '@/types/game'

export const GRAMMAR_ITEMS: ContentItem[] = [
  // ── Present Perfect ───────────────────────────────────────
  {
    id: 'g1',
    type: 'grammar_choice',
    difficulty: 450,
    skill: 'present_perfect',
    tags: ['tenses', 'present-perfect', 'beginner'],
    data: {
      question_text: 'Choose the correct verb form:',
      context_sentence: 'She ___ in London for five years.',
      context_translation: 'היא ___ בלונדון כבר חמש שנים.',
      options: ['has lived', 'is living', 'lived', 'was living'],
      correct_answer: 'has lived',
      grammar_hint: 'Use Present Perfect ("has/have + past participle") for actions that started in the past and continue to the present. "For five years" signals duration up to now.',
      common_mistake: 'Do not use Past Simple here — "She lived in London for five years" implies she no longer does.',
    },
  },
  {
    id: 'g2',
    type: 'grammar_choice',
    difficulty: 490,
    skill: 'present_perfect',
    tags: ['tenses', 'present-perfect'],
    data: {
      question_text: 'Which sentence is correct?',
      context_sentence: 'They ___ the project yet.',
      context_translation: 'הם ___ את הפרויקט עדיין.',
      options: ["haven't finished", "didn't finish", "don't finish", "weren't finishing"],
      correct_answer: "haven't finished",
      grammar_hint: '"Yet" is a signal word for the Present Perfect when used in negatives and questions. It means "up to now."',
      common_mistake: '"Didn\'t finish yet" is wrong — "yet" requires Present Perfect in standard British/American English.',
    },
  },
  {
    id: 'g3',
    type: 'grammar_choice',
    difficulty: 530,
    skill: 'present_perfect',
    tags: ['tenses', 'present-perfect', 'intermediate'],
    data: {
      question_text: 'Select the best option:',
      context_sentence: 'This is the most interesting book I ___ in years.',
      context_translation: 'זה הספר המעניין ביותר שאני ___ בשנים.',
      options: ['have read', 'read', 'was reading', 'am reading'],
      correct_answer: 'have read',
      grammar_hint: 'After superlatives ("most interesting", "best", "worst"), use the Present Perfect to describe a personal experience.',
      common_mistake: 'With superlatives comparing experiences, Present Perfect is standard, not Past Simple.',
    },
  },
  // ── Past Simple ───────────────────────────────────────────
  {
    id: 'g4',
    type: 'grammar_choice',
    difficulty: 420,
    skill: 'past_simple',
    tags: ['tenses', 'past-simple', 'beginner'],
    data: {
      question_text: 'Choose the correct form:',
      context_sentence: 'She ___ her keys when she left the house.',
      context_translation: 'היא ___ את המפתחות שלה כשיצאה מהבית.',
      options: ['forgot', 'has forgotten', 'was forgetting', 'forget'],
      correct_answer: 'forgot',
      grammar_hint: 'Use Past Simple for a completed action at a specific moment in the past. "When she left" anchors the action to a point in time.',
      common_mistake: '"When" followed by a past action usually calls for Past Simple, not Present Perfect.',
    },
  },
  {
    id: 'g5',
    type: 'grammar_choice',
    difficulty: 460,
    skill: 'past_simple',
    tags: ['tenses', 'past-simple'],
    data: {
      question_text: 'Fill in the blank:',
      context_sentence: 'Last summer, we ___ in a small cabin by the lake for two weeks.',
      context_translation: 'בקיץ שעבר, ___ בצריף קטן ליד האגם במשך שבועיים.',
      options: ['stayed', 'have stayed', 'were staying', 'stay'],
      correct_answer: 'stayed',
      grammar_hint: '"Last summer" is a finished time period — use Past Simple. Time phrases like "yesterday", "last year", "in 2020" always go with Past Simple.',
      common_mistake: 'Never use Present Perfect with a specific finished time expression like "last summer."',
    },
  },
  // ── Conditionals ──────────────────────────────────────────
  {
    id: 'g6',
    type: 'grammar_choice',
    difficulty: 500,
    skill: 'conditionals',
    tags: ['conditionals', 'intermediate'],
    data: {
      question_text: 'Which option correctly completes the sentence?',
      context_sentence: 'If I ___ more time, I would travel the world.',
      context_translation: 'אם היה לי יותר זמן, הייתי מטייל בעולם.',
      options: ['had', 'have', 'will have', 'would have'],
      correct_answer: 'had',
      grammar_hint: 'Second Conditional (hypothetical/unreal present): "If + past simple, would + base verb." Use "had" here — it signals this is imaginary, not real.',
      common_mistake: 'Never use "would" in the if-clause: NOT "If I would have time."',
    },
  },
  {
    id: 'g7',
    type: 'grammar_choice',
    difficulty: 560,
    skill: 'conditionals',
    tags: ['conditionals', 'advanced'],
    data: {
      question_text: 'Choose the correct third conditional:',
      context_sentence: 'If she ___ the warning, she would have avoided the accident.',
      context_translation: 'אם היא ___ את האזהרה, היא הייתה נמנעת מהתאונה.',
      options: ['had heeded', 'heeded', 'would heed', 'has heeded'],
      correct_answer: 'had heeded',
      grammar_hint: 'Third Conditional (unreal past): "If + past perfect, would have + past participle." The action cannot be changed now.',
      common_mistake: 'Do not mix up tenses: the if-clause needs "had + past participle", the result needs "would have + past participle."',
    },
  },
  {
    id: 'g8',
    type: 'grammar_choice',
    difficulty: 540,
    skill: 'conditionals',
    tags: ['conditionals', 'intermediate'],
    data: {
      question_text: 'Which is the first conditional?',
      context_sentence: 'If you ___ hard enough, you will pass the exam.',
      context_translation: 'אם תתאמן ___ מספיק קשה, תעבור את הבחינה.',
      options: ['study', 'studied', 'will study', 'would study'],
      correct_answer: 'study',
      grammar_hint: 'First Conditional (real/possible future): "If + present simple, will + base verb." The situation is possible.',
      common_mistake: 'Do NOT use "will" in the if-clause of first conditionals: NOT "If you will study."',
    },
  },
  // ── Passive Voice ─────────────────────────────────────────
  {
    id: 'g9',
    type: 'grammar_choice',
    difficulty: 550,
    skill: 'passive_voice',
    tags: ['passive', 'intermediate'],
    data: {
      question_text: 'Select the grammatically correct option:',
      context_sentence: 'The annual report ___ by the finance team last week.',
      context_translation: 'הדוח השנתי ___ על ידי צוות הכספים בשבוע שעבר.',
      options: ['was prepared', 'prepared', 'has been prepared', 'is prepared'],
      correct_answer: 'was prepared',
      grammar_hint: 'Passive voice in past simple: "was/were + past participle." The phrase "last week" confirms we need a past tense.',
      common_mistake: '"Has been prepared" would mean the action was recently completed with a present-time relevance — "last week" rules this out.',
    },
  },
  {
    id: 'g10',
    type: 'grammar_choice',
    difficulty: 590,
    skill: 'passive_voice',
    tags: ['passive', 'advanced'],
    data: {
      question_text: 'Choose the correct passive form:',
      context_sentence: 'A new hospital ___ in the city centre by the end of next year.',
      context_translation: 'בית חולים חדש ___ במרכז העיר עד סוף השנה הבאה.',
      options: ['will have been built', 'will build', 'will be built', 'is being built'],
      correct_answer: 'will be built',
      grammar_hint: 'Future passive: "will be + past participle." Use for an action that will happen to the subject in the future.',
      common_mistake: '"Will have been built" (future perfect passive) would be needed only if you specify a deadline by which it must be complete. Here the phrase "by the end of next year" indicates a simple planned future event.',
    },
  },
  // ── Articles ──────────────────────────────────────────────
  {
    id: 'g11',
    type: 'grammar_choice',
    difficulty: 440,
    skill: 'articles',
    tags: ['articles', 'beginner'],
    data: {
      question_text: 'Which article best fills the gap?',
      context_sentence: 'She is ___ honest person who always tells the truth.',
      context_translation: 'היא ___ אדם ישר שתמיד אומר את האמת.',
      options: ['an', 'a', 'the', 'no article needed'],
      correct_answer: 'an',
      grammar_hint: 'Use "an" before words beginning with a vowel SOUND. "Honest" starts with a silent "h," so it sounds like it starts with "o" — use "an."',
      common_mistake: 'The rule is about the SOUND, not the spelling. "A uniform" is correct because /juːnɪfɔːm/ starts with a "y" sound.',
    },
  },
  {
    id: 'g12',
    type: 'grammar_choice',
    difficulty: 480,
    skill: 'articles',
    tags: ['articles'],
    data: {
      question_text: 'Choose the correct article (or no article):',
      context_sentence: '___ money does not guarantee happiness.',
      context_translation: '___ כסף אינו מבטיח אושר.',
      options: ['no article', 'The', 'A', 'An'],
      correct_answer: 'no article',
      grammar_hint: 'When talking about something in general (uncountable nouns like "money", "love", "happiness"), use no article.',
      common_mistake: '"The money" would refer to specific money already mentioned. No article means "money in general."',
    },
  },
  {
    id: 'g13',
    type: 'grammar_choice',
    difficulty: 520,
    skill: 'articles',
    tags: ['articles', 'intermediate'],
    data: {
      question_text: 'Select the correct sentence:',
      context_sentence: 'We visited ___ Eiffel Tower during our trip to Paris.',
      context_translation: 'ביקרנו ב ___ מגדל אייפל במהלך הטיול שלנו בפריז.',
      options: ['the', 'a', 'an', 'no article'],
      correct_answer: 'the',
      grammar_hint: 'Use "the" with unique landmarks and specific places. There is only one Eiffel Tower, so it is already specific.',
      common_mistake: '"A Eiffel Tower" is wrong — use "the" for famous, unique places.',
    },
  },
  // ── Modal Verbs ───────────────────────────────────────────
  {
    id: 'g14',
    type: 'grammar_choice',
    difficulty: 470,
    skill: 'modal_verbs',
    tags: ['modals', 'beginner'],
    data: {
      question_text: 'Choose the best modal verb:',
      context_sentence: 'You ___ wear a helmet when cycling — it is the law.',
      context_translation: 'אתה ___ לחבוש קסדה בזמן רכיבה על אופניים — זה חוק.',
      options: ['must', 'should', 'might', 'could'],
      correct_answer: 'must',
      grammar_hint: '"Must" expresses a legal or strong external obligation. "Should" is a recommendation. When there is a law, use "must."',
      common_mistake: '"Should" is advisory. "Must" is obligatory. If you break the law, "must" was the right choice.',
    },
  },
  {
    id: 'g15',
    type: 'grammar_choice',
    difficulty: 540,
    skill: 'modal_verbs',
    tags: ['modals', 'intermediate'],
    data: {
      question_text: 'Choose the best modal for this context:',
      context_sentence: 'She ___ be at home — her car is in the driveway.',
      context_translation: 'היא ___ להיות בבית — המכונית שלה בחניה.',
      options: ['must', 'should', 'will', 'would'],
      correct_answer: 'must',
      grammar_hint: '"Must" is also used for logical deductions based on evidence. The car in the driveway is the evidence.',
      common_mistake: '"Should" implies expectation based on schedule. "Must" implies deduction from evidence — completely different meanings.',
    },
  },
  {
    id: 'g16',
    type: 'grammar_choice',
    difficulty: 610,
    skill: 'modal_verbs',
    tags: ['modals', 'advanced'],
    data: {
      question_text: 'Which sentence expresses a past ability?',
      context_sentence: 'When he was young, he ___ run a marathon without stopping.',
      context_translation: 'כשהיה צעיר, הוא ___ לרוץ מרתון ללא עצירה.',
      options: ['could', 'would', 'must have', 'should have'],
      correct_answer: 'could',
      grammar_hint: '"Could" expresses past ability (what someone was able to do). "Would" refers to past habits. "Must have" is a past deduction.',
      common_mistake: '"Would run a marathon" implies habitual action — he did it regularly. "Could run" means he had the ability (even once).',
    },
  },
  // ── Prepositions ──────────────────────────────────────────
  {
    id: 'g17',
    type: 'grammar_choice',
    difficulty: 430,
    skill: 'prepositions',
    tags: ['prepositions', 'beginner'],
    data: {
      question_text: 'Choose the correct preposition:',
      context_sentence: 'The meeting is scheduled ___ Monday at 9 a.m.',
      context_translation: 'הישיבה מתוכננת ___ יום שני בשעה 9 בבוקר.',
      options: ['on', 'at', 'in', 'by'],
      correct_answer: 'on',
      grammar_hint: 'Use "on" for days of the week (on Monday), dates (on 5th March), and specific days (on New Year\'s Day).',
      common_mistake: '"At" is for clock times, "in" is for months/years/seasons. "On" is for days.',
    },
  },
  {
    id: 'g18',
    type: 'grammar_choice',
    difficulty: 500,
    skill: 'prepositions',
    tags: ['prepositions'],
    data: {
      question_text: 'Select the correct preposition:',
      context_sentence: 'She has been working ___ this company since 2019.',
      context_translation: 'היא עובדת ב ___ חברה זו מאז 2019.',
      options: ['for', 'at', 'to', 'with'],
      correct_answer: 'for',
      grammar_hint: 'Use "for" to describe how long something has continued. Use "at" or "with" to describe where you work.',
      common_mistake: '"Working at this company" is also possible, but the blank precedes "this company" here, not a time duration, so "for" fits the sentence.',
    },
  },
  // ── Phrasal Verbs ─────────────────────────────────────────
  {
    id: 'g19',
    type: 'grammar_choice',
    difficulty: 510,
    skill: 'phrasal_verbs',
    tags: ['phrasal-verbs', 'intermediate'],
    data: {
      question_text: 'Choose the phrasal verb that fits the context:',
      context_sentence: 'He could not ___ the difficult maths problem no matter how hard he tried.',
      context_translation: 'הוא לא הצליח ___ את בעיית המתמטיקה הקשה לא משנה כמה קשה ניסה.',
      options: ['figure out', 'look up', 'put off', 'give in'],
      correct_answer: 'figure out',
      grammar_hint: '"Figure out" = to understand or solve something. "Look up" = to search for information. "Put off" = to delay. "Give in" = to surrender.',
      common_mistake: '"Figure out" is separable: "figure it out" is also correct.',
    },
  },
  {
    id: 'g20',
    type: 'grammar_choice',
    difficulty: 570,
    skill: 'phrasal_verbs',
    tags: ['phrasal-verbs', 'intermediate'],
    data: {
      question_text: 'Which phrasal verb means "to cancel a plan"?',
      context_sentence: 'We had to ___ the outdoor concert because of the heavy rain.',
      context_translation: 'נאלצנו ___ את הקונצרט בחוץ בגלל הגשם הכבד.',
      options: ['call off', 'call up', 'put on', 'get through'],
      correct_answer: 'call off',
      grammar_hint: '"Call off" means to cancel an event. "Call up" = to phone someone. "Put on" = to wear or organize.',
      common_mistake: '"Cancel" and "call off" are interchangeable, but "call off" is more informal.',
    },
  },
  // ── Comparison ────────────────────────────────────────────
  {
    id: 'g21',
    type: 'grammar_choice',
    difficulty: 440,
    skill: 'comparison',
    tags: ['comparison', 'beginner'],
    data: {
      question_text: 'Choose the correct comparative:',
      context_sentence: 'The new office building is ___ than the old one.',
      context_translation: 'בניין המשרדים החדש ___ מהישן.',
      options: ['more modern', 'moderner', 'most modern', 'much modern'],
      correct_answer: 'more modern',
      grammar_hint: 'For adjectives with two or more syllables, use "more + adjective" for comparatives, not "-er".',
      common_mistake: '"Moderner" is not a word. Three-syllable adjectives always use "more/most."',
    },
  },
  {
    id: 'g22',
    type: 'grammar_choice',
    difficulty: 520,
    skill: 'comparison',
    tags: ['comparison', 'intermediate'],
    data: {
      question_text: 'Select the correct sentence:',
      context_sentence: 'This is ___ meal I have ever tasted.',
      context_translation: 'זה ___ ארוחה שטעמתי אי פעם.',
      options: ['the most delicious', 'the more delicious', 'most delicious', 'the deliciouser'],
      correct_answer: 'the most delicious',
      grammar_hint: 'Superlatives need "the" before them: "the most + adjective" or "the + adjective + -est". Never "the more" for superlatives.',
      common_mistake: 'Always include "the" before a superlative when referring to a specific instance.',
    },
  },
  // ── Relative Clauses ──────────────────────────────────────
  {
    id: 'g23',
    type: 'grammar_choice',
    difficulty: 560,
    skill: 'relative_clauses',
    tags: ['relative-clauses', 'intermediate'],
    data: {
      question_text: 'Which relative pronoun is correct?',
      context_sentence: 'The scientist ___ discovered penicillin changed medicine forever.',
      context_translation: 'המדען ___ גילה את הפניצילין שינה את הרפואה לנצח.',
      options: ['who', 'which', 'whose', 'whom'],
      correct_answer: 'who',
      grammar_hint: 'Use "who" for people as the subject of the relative clause. Use "which" for things. Use "whose" for possession.',
      common_mistake: '"Which" is for things, not people. Always use "who" or "whom" when the antecedent is a person.',
    },
  },
  {
    id: 'g24',
    type: 'grammar_choice',
    difficulty: 620,
    skill: 'relative_clauses',
    tags: ['relative-clauses', 'advanced'],
    data: {
      question_text: 'Choose the correct relative pronoun:',
      context_sentence: 'The report, ___ findings were surprising, was published last month.',
      context_translation: 'הדו"ח, ___ ממצאיו היו מפתיעים, פורסם בחודש שעבר.',
      options: ['whose', 'which', 'who', 'that'],
      correct_answer: 'whose',
      grammar_hint: '"Whose" shows possession. The report has/owns the findings. "The report whose findings" = "the findings of the report."',
      common_mistake: '"Which findings" would make it an additional clause, not possessive. "Whose" is the possessive relative pronoun for both people and things.',
    },
  },
  // ── Reported Speech ──────────────────────────────────────
  {
    id: 'g25',
    type: 'grammar_choice',
    difficulty: 600,
    skill: 'reported_speech',
    tags: ['reported-speech', 'advanced'],
    data: {
      question_text: 'Convert to reported speech. He said: "I will finish the report tomorrow."',
      context_sentence: 'He said that he ___ the report the following day.',
      context_translation: 'הוא אמר שהוא ___ את הדו"ח למחרת.',
      options: ['would finish', 'will finish', 'finished', 'had finished'],
      correct_answer: 'would finish',
      grammar_hint: 'In reported speech, "will" shifts back to "would." Time references also shift: "tomorrow" becomes "the following day."',
      common_mistake: '"Will" is direct speech. In reported speech after a past verb ("said"), always shift "will" → "would."',
    },
  },
  // ── Present Continuous ────────────────────────────────────
  {
    id: 'g26',
    type: 'grammar_choice',
    difficulty: 410,
    skill: 'present_continuous',
    tags: ['tenses', 'present-continuous', 'beginner'],
    data: {
      question_text: 'Choose the correct tense:',
      context_sentence: 'Right now, the engineers ___ the software for the new feature.',
      context_translation: 'כרגע, המהנדסים ___ את התוכנה לתכונה החדשה.',
      options: ['are testing', 'test', 'have tested', 'tested'],
      correct_answer: 'are testing',
      grammar_hint: '"Right now" signals an action happening at this exact moment — use Present Continuous (am/is/are + -ing).',
      common_mistake: 'Present Simple ("test") describes general habits. Present Continuous describes what is happening at this moment.',
    },
  },
  // ── Beginner (Tier 1) ─────────────────────────────────────
  {
    id: 'g27',
    type: 'grammar_choice',
    difficulty: 350,
    skill: 'present_simple',
    tags: ['tenses', 'present-simple', 'beginner'],
    data: {
      question_text: 'Choose the correct form:',
      context_sentence: 'I ___ English every day.',
      context_translation: 'אני ___ אנגלית כל יום.',
      options: ['study', 'studies', 'studying', 'am study'],
      correct_answer: 'study',
      grammar_hint: 'With "I/you/we/they", use the base verb in Present Simple: "I study."',
      common_mistake: '"Studies" is for he/she/it. With "I", always use the base form.',
    },
  },
  {
    id: 'g28',
    type: 'grammar_choice',
    difficulty: 370,
    skill: 'articles',
    tags: ['articles', 'beginner'],
    data: {
      question_text: 'Choose the correct article:',
      context_sentence: 'She is ___ teacher.',
      context_translation: 'היא ___ מורה.',
      options: ['a', 'an', 'the', '-'],
      correct_answer: 'a',
      grammar_hint: 'Use "a" before consonant sounds and "an" before vowel sounds. "Teacher" starts with a consonant.',
      common_mistake: '"An teacher" is wrong — "teacher" begins with /t/, a consonant sound.',
    },
  },
  {
    id: 'g29',
    type: 'grammar_choice',
    difficulty: 390,
    skill: 'present_simple',
    tags: ['tenses', 'present-simple', 'beginner'],
    data: {
      question_text: 'Choose the correct form:',
      context_sentence: 'They ___ in Tel Aviv.',
      context_translation: 'הם ___ בתל אביב.',
      options: ['live', 'lives', 'living', 'are live'],
      correct_answer: 'live',
      grammar_hint: 'With "they/we/you/I", Present Simple uses the base verb without -s.',
      common_mistake: '"Lives" is only for he/she/it: "He lives" but "They live".',
    },
  },
  // ── Advanced (Tier 9–10) ────────────────────────────────────
  {
    id: 'g30',
    type: 'grammar_choice',
    difficulty: 780,
    skill: 'conditionals',
    tags: ['conditionals', 'advanced'],
    data: {
      question_text: 'Choose the correct third conditional form:',
      context_sentence: 'If the company ___ more aggressively, it would have captured the market.',
      context_translation: 'אם החברה ___ באגרסיביות רבה יותר, היא הייתה כובשת את השוק.',
      options: ['had invested', 'invested', 'would invest', 'has invested'],
      correct_answer: 'had invested',
      grammar_hint: 'Third conditional: If + past perfect, would have + past participle.',
      common_mistake: 'Second conditional uses past simple; third conditional uses past perfect in the if-clause.',
    },
  },
  {
    id: 'g31',
    type: 'grammar_choice',
    difficulty: 830,
    skill: 'passive_voice',
    tags: ['passive', 'advanced'],
    data: {
      question_text: 'Choose the correct form:',
      context_sentence: 'The manuscript is believed ___ by a team of anonymous scholars.',
      context_translation: 'מאמינים שהכתב יד ___ על ידי צוות של חוקרים אנונימיים.',
      options: ['to have been written', 'to be written', 'having been written', 'was written'],
      correct_answer: 'to have been written',
      grammar_hint: 'After "is believed", use passive infinitive. For completed past action: "to have been + past participle".',
      common_mistake: '"To be written" suggests future or general; "to have been written" refers to a completed past action.',
    },
  },
  {
    id: 'g32',
    type: 'grammar_choice',
    difficulty: 880,
    skill: 'relative_clauses',
    tags: ['relative-clauses', 'master'],
    data: {
      question_text: 'Choose the correct reduced relative clause:',
      context_sentence: 'The documents ___ at the archive contain evidence of the transaction.',
      context_translation: 'המסמכים ___ בארכיון מכילים ראיות לעסקה.',
      options: ['stored', 'storing', 'which storing', 'were storing'],
      correct_answer: 'stored',
      grammar_hint: 'Reduced relative clause: past participle replaces "which were + past participle". "Documents stored" = "documents which were stored".',
      common_mistake: '"Storing" is active — documents do not store themselves. Use past participle "stored" for passive meaning.',
    },
  },
  // ── Expanded pool (g33+) — was / were / had / has / have / is / are ──
  {
    id: 'g33',
    type: 'grammar_choice',
    difficulty: 360,
    skill: 'past_simple',
    tags: ['tenses', 'past-simple', 'beginner', 'be-verbs'],
    data: {
      question_text: 'Choose the correct form of "be":',
      context_sentence: 'She ___ very tired after the long flight yesterday.',
      context_translation: 'היא ___ מאוד עייפה אחרי הטיסה הארוכה אתמול.',
      options: ['was', 'were', 'is', 'has been'],
      correct_answer: 'was',
      grammar_hint: 'Past Simple of "be": I/he/she/it → was. We/you/they → were. "Yesterday" signals past tense.',
      common_mistake: '"Were" is for we/you/they — not for "she". Use "She was tired."',
    },
  },
  {
    id: 'g34',
    type: 'grammar_choice',
    difficulty: 368,
    skill: 'past_simple',
    tags: ['tenses', 'past-simple', 'beginner', 'be-verbs'],
    data: {
      question_text: 'Choose the correct form of "be":',
      context_sentence: 'We ___ at the concert until midnight last Saturday.',
      context_translation: '___ בקונצרט עד חצות ביום שבת שעבר.',
      options: ['were', 'was', 'are', 'have been'],
      correct_answer: 'were',
      grammar_hint: 'With "we/you/they", the past form of "be" is "were". "Last Saturday" confirms Past Simple.',
      common_mistake: '"Was" is only for I/he/she/it. "We were" — never "We was".',
    },
  },
  {
    id: 'g35',
    type: 'grammar_choice',
    difficulty: 375,
    skill: 'past_simple',
    tags: ['tenses', 'past-simple', 'beginner', 'be-verbs'],
    data: {
      question_text: 'Choose the correct negative form:',
      context_sentence: 'He ___ at home yesterday evening — he went out with friends.',
      context_translation: 'הוא ___ בבית אתמול בערב — הוא יצא עם חברים.',
      options: ["wasn't", "weren't", "isn't", "hasn't been"],
      correct_answer: "wasn't",
      grammar_hint: 'Negative Past Simple of "be": was not (wasn\'t) / were not (weren\'t). With "he" use "wasn\'t".',
      common_mistake: '"He weren\'t" is always wrong. "He wasn\'t" or "He was not".',
    },
  },
  {
    id: 'g36',
    type: 'grammar_choice',
    difficulty: 382,
    skill: 'past_simple',
    tags: ['tenses', 'past-simple', 'beginner', 'be-verbs'],
    data: {
      question_text: 'Choose the correct question form:',
      context_sentence: 'Where ___ you last night? I tried to call you.',
      context_translation: 'איפה ___ אתמול בלילה? ניסיתי להתקשר אליך.',
      options: ['were', 'was', 'are', 'did'],
      correct_answer: 'were',
      grammar_hint: 'Questions with "be": invert subject and verb — "Where were you?" With "you" use "were".',
      common_mistake: 'Do not use "did" with "be": NOT "Where did you were?" Say "Where were you?"',
    },
  },
  {
    id: 'g37',
    type: 'grammar_choice',
    difficulty: 390,
    skill: 'present_simple',
    tags: ['tenses', 'present-simple', 'beginner', 'be-verbs'],
    data: {
      question_text: 'Choose the correct form of "be":',
      context_sentence: 'The weather ___ nice today — let us go for a walk.',
      context_translation: 'מזג האוויר ___ נחמד היום — בוא נצא לטיול.',
      options: ['is', 'are', 'was', 'has been'],
      correct_answer: 'is',
      grammar_hint: 'Present Simple of "be": he/she/it/weather → is. "Today" signals present time.',
      common_mistake: '"The weather are" is wrong — "weather" is singular. Use "The weather is nice."',
    },
  },
  {
    id: 'g38',
    type: 'grammar_choice',
    difficulty: 398,
    skill: 'present_simple',
    tags: ['tenses', 'present-simple', 'beginner', 'be-verbs'],
    data: {
      question_text: 'Choose the correct form of "be":',
      context_sentence: 'My parents ___ both teachers at the same school.',
      context_translation: 'שני ההורים שלי ___ מורים באותו בית ספר.',
      options: ['are', 'is', 'was', 'have been'],
      correct_answer: 'are',
      grammar_hint: 'With plural subjects (parents, we, they), use "are" in the present.',
      common_mistake: '"My parents is" is wrong — plural subject needs "are".',
    },
  },
  {
    id: 'g39',
    type: 'grammar_choice',
    difficulty: 405,
    skill: 'present_perfect',
    tags: ['tenses', 'present-perfect', 'beginner', 'have-verbs'],
    data: {
      question_text: 'Choose the correct form:',
      context_sentence: 'She ___ already finished her homework for today.',
      context_translation: 'היא ___ כבר סיימה את שיעורי הבית להיום.',
      options: ['has', 'have', 'had', 'is'],
      correct_answer: 'has',
      grammar_hint: 'Present Perfect: has/have + past participle. With she/he/it use "has finished". "Already" often signals Present Perfect.',
      common_mistake: '"She have finished" is wrong. Third person singular uses "has".',
    },
  },
  {
    id: 'g40',
    type: 'grammar_choice',
    difficulty: 412,
    skill: 'present_perfect',
    tags: ['tenses', 'present-perfect', 'beginner', 'have-verbs'],
    data: {
      question_text: 'Choose the correct form:',
      context_sentence: 'We ___ known each other since we were children.',
      context_translation: '___ מכירים מאז שהיינו ילדים.',
      options: ['have', 'has', 'had', 'are'],
      correct_answer: 'have',
      grammar_hint: 'With we/you/they/I use "have" in Present Perfect. "Since" + past point in time → Present Perfect.',
      common_mistake: '"We has known" is wrong. Plural/first person uses "have known".',
    },
  },
  {
    id: 'g41',
    type: 'grammar_choice',
    difficulty: 420,
    skill: 'present_perfect',
    tags: ['tenses', 'present-perfect', 'beginner', 'have-verbs'],
    data: {
      question_text: 'Choose the correct negative form:',
      context_sentence: 'I ___ never been to London, but I hope to visit someday.',
      context_translation: '___ מעולם לא הייתי בלונדון, אבל אני מקווה לבקר שם יום אחד.',
      options: ['have', 'has', 'had', 'was'],
      correct_answer: 'have',
      grammar_hint: 'Present Perfect for life experience: "I have never been to…" With "I" always use "have".',
      common_mistake: '"I has never been" is wrong. "Never" goes between have/has and the past participle.',
    },
  },
  {
    id: 'g42',
    type: 'grammar_choice',
    difficulty: 428,
    skill: 'past_simple',
    tags: ['tenses', 'past-simple', 'beginner', 'have-verbs'],
    data: {
      question_text: 'Choose the correct form of "have" (possession):',
      context_sentence: 'He ___ a great idea for the school project.',
      context_translation: 'היה ___ לו רעיון נהדר לפרויקט בית הספר.',
      options: ['had', 'has', 'have', 'was'],
      correct_answer: 'had',
      grammar_hint: '"Have" for possession in the past: had. "He had an idea" = he possessed an idea at that time.',
      common_mistake: 'Do not confuse "had" (past of have) with "has" (present). The sentence describes a past situation.',
    },
  },
  {
    id: 'g43',
    type: 'grammar_choice',
    difficulty: 435,
    skill: 'past_perfect',
    tags: ['tenses', 'past-perfect', 'intermediate', 'have-verbs'],
    data: {
      question_text: 'Choose the correct form:',
      context_sentence: 'By the time we arrived, the movie ___ already started.',
      context_translation: 'עד שהגענו, הסרט ___ כבר התחיל.',
      options: ['had', 'has', 'have', 'was'],
      correct_answer: 'had',
      grammar_hint: 'Past Perfect: had + past participle. Use for an action completed BEFORE another past action ("arrived").',
      common_mistake: '"Has already started" is present perfect. Here both events are in the past — use "had started".',
    },
  },
  {
    id: 'g44',
    type: 'grammar_choice',
    difficulty: 442,
    skill: 'past_continuous',
    tags: ['tenses', 'past-continuous', 'intermediate', 'be-verbs'],
    data: {
      question_text: 'Choose the correct form:',
      context_sentence: 'I ___ watching TV when you called last night.',
      context_translation: '___ צופה בטלוויזיה כשהתקשרת אתמול בלילה.',
      options: ['was', 'were', 'am', 'have been'],
      correct_answer: 'was',
      grammar_hint: 'Past Continuous: was/were + verb-ing. Ongoing past action interrupted by another event. With "I" use "was".',
      common_mistake: '"I were watching" is wrong. I/he/she/it → was + -ing.',
    },
  },
  {
    id: 'g45',
    type: 'grammar_choice',
    difficulty: 450,
    skill: 'past_continuous',
    tags: ['tenses', 'past-continuous', 'intermediate', 'be-verbs'],
    data: {
      question_text: 'Choose the correct form:',
      context_sentence: 'They ___ sleeping when the alarm went off this morning.',
      context_translation: 'הם ___ ישנים כשהשעון המעורר צלצל הבוקר.',
      options: ['were', 'was', 'are', 'had been'],
      correct_answer: 'were',
      grammar_hint: 'Past Continuous with they/we/you: were + verb-ing. "When the alarm went off" = interrupting past event.',
      common_mistake: '"They was sleeping" is wrong. Plural subjects use "were sleeping".',
    },
  },
  {
    id: 'g46',
    type: 'grammar_choice',
    difficulty: 458,
    skill: 'present_continuous',
    tags: ['tenses', 'present-continuous', 'beginner', 'be-verbs'],
    data: {
      question_text: 'Choose the correct form:',
      context_sentence: 'Look! It ___ raining outside — take an umbrella.',
      context_translation: 'תסתכל! ___ יורד גשם בחוץ — קח מטריה.',
      options: ['is', 'are', 'was', 'has'],
      correct_answer: 'is',
      grammar_hint: 'Present Continuous: am/is/are + verb-ing for actions happening now. "It" takes "is".',
      common_mistake: '"It are raining" is wrong. Weather "it" always uses "is".',
    },
  },
  {
    id: 'g47',
    type: 'grammar_choice',
    difficulty: 465,
    skill: 'present_continuous',
    tags: ['tenses', 'present-continuous', 'beginner', 'be-verbs'],
    data: {
      question_text: 'Choose the correct form:',
      context_sentence: 'The children ___ playing in the garden right now.',
      context_translation: 'הילדים ___ משחקים בגינה עכשיו.',
      options: ['are', 'is', 'were', 'have been'],
      correct_answer: 'are',
      grammar_hint: 'Present Continuous with plural subjects: are + verb-ing. "Right now" signals ongoing present action.',
      common_mistake: '"The children is playing" is wrong — plural needs "are playing".',
    },
  },
  {
    id: 'g48',
    type: 'grammar_choice',
    difficulty: 472,
    skill: 'passive_voice',
    tags: ['passive', 'intermediate', 'be-verbs'],
    data: {
      question_text: 'Choose the correct passive form:',
      context_sentence: 'The windows ___ broken during the storm last week.',
      context_translation: 'החלונות ___ נשברו במהלך הסערה בשבוע שעבר.',
      options: ['were', 'was', 'are', 'have been'],
      correct_answer: 'were',
      grammar_hint: 'Past passive: was/were + past participle. Plural subject "windows" → "were broken".',
      common_mistake: '"The windows was broken" is wrong. Plural subject needs "were".',
    },
  },
  {
    id: 'g49',
    type: 'grammar_choice',
    difficulty: 480,
    skill: 'passive_voice',
    tags: ['passive', 'intermediate', 'be-verbs'],
    data: {
      question_text: 'Choose the correct passive form:',
      context_sentence: 'The cake ___ baked by my grandmother yesterday.',
      context_translation: 'העוגה ___ אפויה על ידי סבתי אתמול.',
      options: ['was', 'were', 'is', 'has been'],
      correct_answer: 'was',
      grammar_hint: 'Past passive with singular subject: was + past participle. "The cake" is singular → "was baked".',
      common_mistake: 'Active: "My grandmother baked the cake." Passive: "The cake was baked by my grandmother."',
    },
  },
  {
    id: 'g50',
    type: 'grammar_choice',
    difficulty: 488,
    skill: 'present_perfect',
    tags: ['tenses', 'present-perfect', 'intermediate', 'have-verbs'],
    data: {
      question_text: 'Choose the correct form:',
      context_sentence: 'They ___ been waiting for the bus for twenty minutes.',
      context_translation: 'הם ___ מחכים לאוטובוס כבר עשרים דקות.',
      options: ['have', 'has', 'had', 'are'],
      correct_answer: 'have',
      grammar_hint: 'Present Perfect Continuous: have/have been + verb-ing. Duration up to now ("for twenty minutes").',
      common_mistake: '"They has been waiting" is wrong. With "they" use "have been waiting".',
    },
  },
  {
    id: 'g51',
    type: 'grammar_choice',
    difficulty: 495,
    skill: 'past_perfect',
    tags: ['tenses', 'past-perfect', 'intermediate', 'have-verbs'],
    data: {
      question_text: 'Choose the correct form:',
      context_sentence: 'She ___ already left when I got to the party.',
      context_translation: 'היא ___ כבר עזבה כשהגעתי למסיבה.',
      options: ['had', 'has', 'have', 'was'],
      correct_answer: 'had',
      grammar_hint: 'Past Perfect: had + past participle. Her leaving happened BEFORE I arrived.',
      common_mistake: '"She has already left" suggests relevance to now. Both events are past — use "had left".',
    },
  },
  {
    id: 'g52',
    type: 'grammar_choice',
    difficulty: 502,
    skill: 'conditionals',
    tags: ['conditionals', 'intermediate', 'have-verbs'],
    data: {
      question_text: 'Choose the correct form:',
      context_sentence: 'If they ___ more time, they would have finished the project.',
      context_translation: 'אם היה ___ להם יותר זמן, הם היו מסיימים את הפרויקט.',
      options: ['had had', 'have had', 'has had', 'would have'],
      correct_answer: 'had had',
      grammar_hint: 'Third conditional if-clause: If + had + past participle. "Had had" = past perfect of "have" (possession/time).',
      common_mistake: 'Looks strange but correct: "If they had had more time" = if they had possessed more time.',
    },
  },
]
