import type { ContentItem } from '@/types/game'

export const LISTENING_ITEMS: ContentItem[] = [
  {
    id: 'l1',
    type: 'listening_dictation',
    difficulty: 400,
    skill: 'sentence_structure',
    tags: ['daily-life', 'beginner'],
    data: {
      context_sentence: 'The sun rises in the east and sets in the west.',
      context_translation: 'השמש עולה במזרח ושוקעת במערב.',
      correct_answer: 'The sun rises in the east and sets in the west.',
      audio_only: true,
      common_mistake: 'Pay attention to "rises" (not "rise") — third person singular needs the -s suffix.',
    },
  },
  {
    id: 'l2',
    type: 'listening_dictation',
    difficulty: 420,
    skill: 'past_simple',
    tags: ['past', 'beginner'],
    data: {
      context_sentence: 'Yesterday she called her parents and told them the good news.',
      context_translation: 'אתמול היא התקשרה להוריה וסיפרה להם את הבשורה הטובה.',
      correct_answer: 'Yesterday she called her parents and told them the good news.',
      audio_only: true,
      common_mistake: '"Called" and "told" are both regular past forms. Note "told" is irregular: tell → told.',
    },
  },
  {
    id: 'l3',
    type: 'listening_dictation',
    difficulty: 450,
    skill: 'present_perfect',
    tags: ['experience', 'intermediate'],
    data: {
      context_sentence: 'Have you ever tried sushi? It is one of the most popular dishes in Japan.',
      context_translation: 'האם ניסית אי פעם סושי? זהו אחד המאכלים הפופולריים ביותר ביפן.',
      correct_answer: 'Have you ever tried sushi? It is one of the most popular dishes in Japan.',
      audio_only: true,
      common_mistake: '"Ever" in questions with Present Perfect means "at any time in your life." Note "dishes" (plural) not "dish."',
    },
  },
  {
    id: 'l4',
    type: 'listening_dictation',
    difficulty: 480,
    skill: 'conditionals',
    tags: ['hypothetical', 'intermediate'],
    data: {
      context_sentence: 'If it rains tomorrow, we will cancel the outdoor barbecue.',
      context_translation: 'אם ירד גשם מחר, נבטל את המנגל בחוץ.',
      correct_answer: 'If it rains tomorrow, we will cancel the outdoor barbecue.',
      audio_only: true,
      common_mistake: 'First conditional: present tense after "if", future after the comma. "Barbecue" is often misspelled as "barbeque."',
    },
  },
  {
    id: 'l5',
    type: 'listening_dictation',
    difficulty: 510,
    skill: 'passive_voice',
    tags: ['formal', 'intermediate'],
    data: {
      context_sentence: 'The new policy was introduced by the government to reduce pollution.',
      context_translation: 'המדיניות החדשה הוכנסה על ידי הממשלה כדי להפחית זיהום.',
      correct_answer: 'The new policy was introduced by the government to reduce pollution.',
      audio_only: true,
      common_mistake: '"Was introduced" is passive past simple. "By the government" is the agent — it tells us who performed the action.',
    },
  },
  {
    id: 'l6',
    type: 'listening_dictation',
    difficulty: 540,
    skill: 'modal_verbs',
    tags: ['obligation', 'intermediate'],
    data: {
      context_sentence: 'Passengers should arrive at the airport at least two hours before departure.',
      context_translation: 'נוסעים צריכים להגיע לשדה התעופה לפחות שעתיים לפני היציאה.',
      correct_answer: 'Passengers should arrive at the airport at least two hours before departure.',
      audio_only: true,
      common_mistake: '"Departure" is a noun (not "depart"). "At least" means a minimum — could be more.',
    },
  },
  {
    id: 'l7',
    type: 'listening_dictation',
    difficulty: 570,
    skill: 'relative_clauses',
    tags: ['description', 'intermediate'],
    data: {
      context_sentence: 'The software engineer who designed the app won a prestigious award.',
      context_translation: 'מהנדס התוכנה שתכנן את האפליקציה זכה בפרס יוקרתי.',
      correct_answer: 'The software engineer who designed the app won a prestigious award.',
      audio_only: true,
      common_mistake: '"Prestigious" is often mispronounced. Stress: pres-TI-gious. "Won" is past simple of "win."',
    },
  },
  {
    id: 'l8',
    type: 'listening_dictation',
    difficulty: 600,
    skill: 'vocabulary_business',
    tags: ['business', 'advanced'],
    data: {
      context_sentence: 'The board of directors voted unanimously to approve the merger with the rival company.',
      context_translation: 'מועצת המנהלים הצביעה פה אחד לאישור המיזוג עם החברה המתחרה.',
      correct_answer: 'The board of directors voted unanimously to approve the merger with the rival company.',
      audio_only: true,
      common_mistake: '"Unanimously" means everyone agreed. "Merger" (noun) is the act of combining two companies — "merge" is the verb.',
    },
  },
  {
    id: 'l9',
    type: 'listening_dictation',
    difficulty: 630,
    skill: 'vocabulary_academic',
    tags: ['academic', 'advanced'],
    data: {
      context_sentence: 'The researchers hypothesised that increased screen time negatively affects concentration.',
      context_translation: 'החוקרים הניחו שזמן מסך מוגבר משפיע לרעה על הריכוז.',
      correct_answer: 'The researchers hypothesised that increased screen time negatively affects concentration.',
      audio_only: true,
      common_mistake: 'British spelling: "hypothesised." American spelling: "hypothesized." "Affects" (verb) not "effects" (noun).',
    },
  },
  {
    id: 'l10',
    type: 'listening_dictation',
    difficulty: 470,
    skill: 'vocabulary_travel',
    tags: ['travel', 'beginner'],
    data: {
      context_sentence: 'Could you please tell me where the nearest bus stop is?',
      context_translation: 'האם תוכל בבקשה להגיד לי איפה תחנת האוטובוס הקרובה ביותר?',
      correct_answer: 'Could you please tell me where the nearest bus stop is?',
      audio_only: true,
      common_mistake: 'Polite indirect question: the word order reverses — "where the nearest bus stop IS" not "where IS the nearest bus stop."',
    },
  },
  // ── Beginner (Tier 1) ─────────────────────────────────────
  {
    id: 'l11',
    type: 'listening_dictation',
    difficulty: 350,
    skill: 'sentence_structure',
    tags: ['basics', 'beginner'],
    data: {
      context_sentence: 'Good morning. How are you?',
      context_translation: 'בוקר טוב. מה שלומך?',
      correct_answer: 'Good morning. How are you?',
      audio_only: true,
      common_mistake: 'Capitalise "Good morning" — it starts a sentence.',
    },
  },
  {
    id: 'l12',
    type: 'listening_dictation',
    difficulty: 370,
    skill: 'present_simple',
    tags: ['basics', 'beginner'],
    data: {
      context_sentence: 'I have two brothers and one sister.',
      context_translation: 'יש לי שני אחים ואחות אחת.',
      correct_answer: 'I have two brothers and one sister.',
      audio_only: true,
      common_mistake: '"Brothers" is plural. "Sister" is singular when there is only one.',
    },
  },
  {
    id: 'l13',
    type: 'listening_dictation',
    difficulty: 390,
    skill: 'vocabulary_travel',
    tags: ['basics', 'beginner'],
    data: {
      context_sentence: 'The shop is on the left side of the street.',
      context_translation: 'החנות נמצאת בצד השמאלי של הרחוב.',
      correct_answer: 'The shop is on the left side of the street.',
      audio_only: true,
      common_mistake: 'Use "on the left" — not "in the left".',
    },
  },
  // ── Advanced (Tier 9–10) ────────────────────────────────────
  {
    id: 'l14',
    type: 'listening_dictation',
    difficulty: 780,
    skill: 'vocabulary_academic',
    tags: ['academic', 'advanced'],
    data: {
      context_sentence: 'The empirical evidence contradicts the prevailing hypothesis put forward by earlier researchers.',
      context_translation: 'הראיות האмпיריות סותרות את ההשערה השוררת שהוצעה על ידי חוקרים קודמים.',
      correct_answer: 'The empirical evidence contradicts the prevailing hypothesis put forward by earlier researchers.',
      audio_only: true,
      common_mistake: '"Put forward" is a phrasal verb meaning proposed or suggested.',
    },
  },
  {
    id: 'l15',
    type: 'listening_dictation',
    difficulty: 850,
    skill: 'vocabulary_business',
    tags: ['business', 'advanced'],
    data: {
      context_sentence: 'Shareholders expressed concern that the restructuring would erode long-term shareholder value.',
      context_translation: 'בעלי המניות הביעו דאגה שהארגון מחדש ישחיק את ערך המניות לטווח ארוך.',
      correct_answer: 'Shareholders expressed concern that the restructuring would erode long-term shareholder value.',
      audio_only: true,
      common_mistake: '"Erode" means gradually weaken or reduce — often used for value, trust, or confidence.',
    },
  },
]
