import type { ContentItem } from '@/types/game'

export const SENTENCE_ITEMS: ContentItem[] = [
  {
    id: 's1',
    type: 'sentence_builder',
    difficulty: 420,
    skill: 'sentence_structure',
    tags: ['daily-life', 'beginner'],
    data: {
      context_sentence: 'Arrange the words to form a morning routine sentence.',
      context_translation: 'סדר את המילים ליצירת משפט על שגרת בוקר.',
      correct_answer: 'Every morning I drink a cup of coffee before work',
      word_chips: ['Every', 'morning', 'I', 'drink', 'a', 'cup', 'of', 'coffee', 'before', 'work'],
      common_mistake: 'Remember: subject (I) comes before the verb (drink) in declarative sentences.',
    },
  },
  {
    id: 's2',
    type: 'sentence_builder',
    difficulty: 450,
    skill: 'future_going_to',
    tags: ['travel', 'intermediate'],
    data: {
      context_sentence: 'Build a sentence about confirmed travel plans.',
      context_translation: 'בנה משפט על תוכניות נסיעה מאושרות.',
      correct_answer: 'We are planning to visit Japan next summer',
      word_chips: ['We', 'are', 'planning', 'to', 'visit', 'Japan', 'next', 'summer'],
      common_mistake: '"Planning to" expresses a firm, already-arranged intention — similar in meaning to "going to."',
    },
  },
  {
    id: 's3',
    type: 'sentence_builder',
    difficulty: 500,
    skill: 'passive_voice',
    tags: ['work', 'intermediate'],
    data: {
      context_sentence: 'Build a passive-voice sentence about a rescheduled meeting.',
      context_translation: 'בנה משפט בגוף סביל על ישיבה שנדחתה.',
      correct_answer: 'The meeting has been rescheduled to Thursday afternoon',
      word_chips: ['The', 'meeting', 'has', 'been', 'rescheduled', 'to', 'Thursday', 'afternoon'],
      common_mistake: 'Present perfect passive: "has/have been + past participle." Note: "rescheduled TO" not "rescheduled FOR."',
    },
  },
  {
    id: 's4',
    type: 'sentence_builder',
    difficulty: 540,
    skill: 'conditionals',
    tags: ['work', 'intermediate'],
    data: {
      context_sentence: 'Build a first conditional sentence about finishing work on time.',
      context_translation: 'בנה משפט תנאי ראשון על סיום עבודה בזמן.',
      correct_answer: 'If you submit the report by noon we will review it today',
      word_chips: ['If', 'you', 'submit', 'the', 'report', 'by', 'noon', 'we', 'will', 'review', 'it', 'today'],
      common_mistake: 'First conditional: "If + present simple, will + base verb." No comma is needed when the main clause comes first.',
    },
  },
  {
    id: 's5',
    type: 'sentence_builder',
    difficulty: 580,
    skill: 'vocabulary_environment',
    tags: ['environment', 'intermediate'],
    data: {
      context_sentence: 'Build a sentence about the effects of climate change.',
      context_translation: 'בנה משפט על השפעות שינויי האקלים.',
      correct_answer: 'Scientists warn that rising temperatures will affect ecosystems worldwide',
      word_chips: ['Scientists', 'warn', 'that', 'rising', 'temperatures', 'will', 'affect', 'ecosystems', 'worldwide'],
      common_mistake: 'Notice "affect" (verb) vs "effect" (noun). "Rising temperatures will affect ecosystems" — affect is the action verb here.',
    },
  },
  {
    id: 's6',
    type: 'sentence_builder',
    difficulty: 620,
    skill: 'vocabulary_technology',
    tags: ['technology', 'advanced'],
    data: {
      context_sentence: 'Build a sentence about the global impact of artificial intelligence.',
      context_translation: 'בנה משפט על ההשפעה הגלובלית של בינה מלאכותית.',
      correct_answer: 'Artificial intelligence is transforming the way businesses operate globally',
      word_chips: ['Artificial', 'intelligence', 'is', 'transforming', 'the', 'way', 'businesses', 'operate', 'globally'],
      common_mistake: '"The way businesses operate" is a noun phrase, not a relative clause. No "that" or "which" is needed here.',
    },
  },
  {
    id: 's7',
    type: 'sentence_builder',
    difficulty: 460,
    skill: 'present_perfect',
    tags: ['experience', 'intermediate'],
    data: {
      context_sentence: 'Build a present perfect sentence about travel experience.',
      context_translation: 'בנה משפט בהווה מושלם על ניסיון טיול.',
      correct_answer: 'I have never been to South America but I hope to go someday',
      word_chips: ['I', 'have', 'never', 'been', 'to', 'South', 'America', 'but', 'I', 'hope', 'to', 'go', 'someday'],
      common_mistake: '"Never" is placed between "have" and the past participle. "Have been to" means visited — "have gone to" means went and is still there.',
    },
  },
  {
    id: 's8',
    type: 'sentence_builder',
    difficulty: 500,
    skill: 'past_simple',
    tags: ['daily-life', 'beginner'],
    data: {
      context_sentence: 'Build a past simple narrative sentence.',
      context_translation: 'בנה משפט עבר פשוט נרטיבי.',
      correct_answer: 'She woke up early checked her phone and then made breakfast',
      word_chips: ['She', 'woke', 'up', 'early', 'checked', 'her', 'phone', 'and', 'then', 'made', 'breakfast'],
      common_mistake: 'Past simple with a sequence of actions: use commas for longer lists. "Woke up" is an irregular verb — not "waked up."',
    },
  },
  {
    id: 's9',
    type: 'sentence_builder',
    difficulty: 560,
    skill: 'relative_clauses',
    tags: ['description', 'intermediate'],
    data: {
      context_sentence: 'Build a sentence with a defining relative clause.',
      context_translation: 'בנה משפט עם פסוקית שם עצם מגדירה.',
      correct_answer: 'The colleague who helped me with the project received a promotion',
      word_chips: ['The', 'colleague', 'who', 'helped', 'me', 'with', 'the', 'project', 'received', 'a', 'promotion'],
      common_mistake: 'Defining relative clauses have no commas — they identify which person/thing you mean.',
    },
  },
  {
    id: 's10',
    type: 'sentence_builder',
    difficulty: 640,
    skill: 'reported_speech',
    tags: ['communication', 'advanced'],
    data: {
      context_sentence: 'Build a reported speech sentence.',
      context_translation: 'בנה משפט בדיבור עקיף.',
      correct_answer: 'The manager told the team that the deadline would be moved to Friday',
      word_chips: ['The', 'manager', 'told', 'the', 'team', 'that', 'the', 'deadline', 'would', 'be', 'moved', 'to', 'Friday'],
      common_mistake: '"Will" changes to "would" in reported speech. "The deadline will be moved" → "the deadline would be moved."',
    },
  },
  {
    id: 's11',
    type: 'sentence_builder',
    difficulty: 480,
    skill: 'modal_verbs',
    tags: ['advice', 'beginner'],
    data: {
      context_sentence: 'Build a sentence giving strong advice.',
      context_translation: 'בנה משפט שנותן עצה חזקה.',
      correct_answer: 'You should drink at least eight glasses of water every day',
      word_chips: ['You', 'should', 'drink', 'at', 'least', 'eight', 'glasses', 'of', 'water', 'every', 'day'],
      common_mistake: '"Should" for advice is followed by the base infinitive (not "to drink"). Example: "should drink" not "should to drink."',
    },
  },
  {
    id: 's12',
    type: 'sentence_builder',
    difficulty: 520,
    skill: 'comparison',
    tags: ['comparison', 'intermediate'],
    data: {
      context_sentence: 'Build a superlative sentence about a city.',
      context_translation: 'בנה משפט עם תואר השוואה עליון על עיר.',
      correct_answer: 'Tokyo is one of the most densely populated cities in the world',
      word_chips: ['Tokyo', 'is', 'one', 'of', 'the', 'most', 'densely', 'populated', 'cities', 'in', 'the', 'world'],
      common_mistake: '"One of the most…" requires a plural noun (cities, not city). Always: "one of the most + plural noun."',
    },
  },
  // ── Beginner (Tier 1) ─────────────────────────────────────
  {
    id: 's13',
    type: 'sentence_builder',
    difficulty: 350,
    skill: 'sentence_structure',
    tags: ['basics', 'beginner'],
    data: {
      context_sentence: 'Arrange the words to make a simple greeting.',
      context_translation: 'סדר את המילים ליצירת ברכה פשוטה.',
      correct_answer: 'Hello my name is Anna',
      word_chips: ['Hello', 'my', 'name', 'is', 'Anna'],
      common_mistake: 'In English, names are capitalised: "Anna" not "anna".',
    },
  },
  {
    id: 's14',
    type: 'sentence_builder',
    difficulty: 370,
    skill: 'present_simple',
    tags: ['basics', 'beginner'],
    data: {
      context_sentence: 'Build a simple sentence about what you like.',
      context_translation: 'בנה משפט פשוט על מה שאתה אוהב.',
      correct_answer: 'I like apples and bananas',
      word_chips: ['I', 'like', 'apples', 'and', 'bananas'],
      common_mistake: 'After "like" use the base form of the verb or a noun: "I like apples" — no "to" needed.',
    },
  },
  {
    id: 's15',
    type: 'sentence_builder',
    difficulty: 390,
    skill: 'sentence_structure',
    tags: ['basics', 'beginner'],
    data: {
      context_sentence: 'Arrange the words to describe going to school.',
      context_translation: 'סדר את המילים לתיאור הליכה לבית הספר.',
      correct_answer: 'We go to school every day',
      word_chips: ['We', 'go', 'to', 'school', 'every', 'day'],
      common_mistake: 'Use "go to" + place: "go to school" — not "go in school".',
    },
  },
  // ── Advanced (Tier 9–10) ────────────────────────────────────
  {
    id: 's16',
    type: 'sentence_builder',
    difficulty: 770,
    skill: 'passive_voice',
    tags: ['advanced', 'formal'],
    data: {
      context_sentence: 'Build a formal passive sentence about a policy decision.',
      context_translation: 'בנה משפט פסיבי רשמי על החלטת מדיניות.',
      correct_answer: 'The new regulations were approved by the board after lengthy deliberation',
      word_chips: ['The', 'new', 'regulations', 'were', 'approved', 'by', 'the', 'board', 'after', 'lengthy', 'deliberation'],
      common_mistake: 'Passive voice: subject + was/were + past participle + by + agent.',
    },
  },
  {
    id: 's17',
    type: 'sentence_builder',
    difficulty: 820,
    skill: 'relative_clauses',
    tags: ['advanced'],
    data: {
      context_sentence: 'Build a sentence with a relative clause about a researcher.',
      context_translation: 'בנה משפט עם משפט יחס על חוקר.',
      correct_answer: 'The scientist whose groundbreaking research transformed the field received international acclaim',
      word_chips: ['The', 'scientist', 'whose', 'groundbreaking', 'research', 'transformed', 'the', 'field', 'received', 'international', 'acclaim'],
      common_mistake: '"Whose" shows possession — the scientist owns the research.',
    },
  },
  {
    id: 's18',
    type: 'sentence_builder',
    difficulty: 870,
    skill: 'reported_speech',
    tags: ['advanced', 'master'],
    data: {
      context_sentence: 'Build a complex reported-speech sentence.',
      context_translation: 'בנה משפט מורכב בדיבור מדווח.',
      correct_answer: 'She insisted that the proposal had been rejected without proper consultation',
      word_chips: ['She', 'insisted', 'that', 'the', 'proposal', 'had', 'been', 'rejected', 'without', 'proper', 'consultation'],
      common_mistake: 'After "insisted that", shift tenses back: "has been" → "had been".',
    },
  },
  // ── Expanded pool (s19+) ────────────────────────────────────
  {
    id: 's19',
    type: 'sentence_builder',
    difficulty: 360,
    skill: 'sentence_structure',
    tags: ['basics', 'beginner'],
    data: {
      context_sentence: 'Build a simple question about the time.',
      context_translation: 'בנה שאלה פשוטה על השעה.',
      correct_answer: 'What time is it now',
      word_chips: ['What', 'time', 'is', 'it', 'now'],
      common_mistake: 'Question word order: What + auxiliary + subject — "What time is it?"',
    },
  },
  {
    id: 's20',
    type: 'sentence_builder',
    difficulty: 380,
    skill: 'present_simple',
    tags: ['basics', 'beginner'],
    data: {
      context_sentence: 'Build a sentence about a daily habit.',
      context_translation: 'בנה משפט על הרגל יומי.',
      correct_answer: 'She walks to the office every morning',
      word_chips: ['She', 'walks', 'to', 'the', 'office', 'every', 'morning'],
      common_mistake: 'With she/he/it, add -s to the verb: "walks" not "walk".',
    },
  },
  {
    id: 's21',
    type: 'sentence_builder',
    difficulty: 400,
    skill: 'sentence_structure',
    tags: ['daily-life', 'beginner'],
    data: {
      context_sentence: 'Build a sentence about ordering food.',
      context_translation: 'בנה משפט על הזמנת אוכל.',
      correct_answer: 'I would like a salad and a glass of juice',
      word_chips: ['I', 'would', 'like', 'a', 'salad', 'and', 'a', 'glass', 'of', 'juice'],
      common_mistake: 'Polite requests use "I would like" — not "I want" in formal settings.',
    },
  },
  {
    id: 's22',
    type: 'sentence_builder',
    difficulty: 430,
    skill: 'present_continuous',
    tags: ['daily-life', 'beginner'],
    data: {
      context_sentence: 'Build a present continuous sentence about right now.',
      context_translation: 'בנה משפט בהווה מתמשך על מה שקורה עכשיו.',
      correct_answer: 'They are studying for the exam in the library',
      word_chips: ['They', 'are', 'studying', 'for', 'the', 'exam', 'in', 'the', 'library'],
      common_mistake: 'Present continuous: am/is/are + verb-ing for actions happening now.',
    },
  },
  {
    id: 's23',
    type: 'sentence_builder',
    difficulty: 470,
    skill: 'past_simple',
    tags: ['travel', 'intermediate'],
    data: {
      context_sentence: 'Build a past simple sentence about a trip.',
      context_translation: 'בנה משפט בעבר פשוט על טיול.',
      correct_answer: 'We visited three museums during our trip to Rome',
      word_chips: ['We', 'visited', 'three', 'museums', 'during', 'our', 'trip', 'to', 'Rome'],
      common_mistake: '"Visit" → "visited" (regular). Use "during" for a period of time.',
    },
  },
  {
    id: 's24',
    type: 'sentence_builder',
    difficulty: 490,
    skill: 'future_going_to',
    tags: ['plans', 'intermediate'],
    data: {
      context_sentence: 'Build a sentence about weekend plans.',
      context_translation: 'בנה משפט על תוכניות לסוף השבוע.',
      correct_answer: 'I am going to meet my friends at the beach on Saturday',
      word_chips: ['I', 'am', 'going', 'to', 'meet', 'my', 'friends', 'at', 'the', 'beach', 'on', 'Saturday'],
      common_mistake: '"Going to" for plans already decided — different from "will" for spontaneous decisions.',
    },
  },
  {
    id: 's25',
    type: 'sentence_builder',
    difficulty: 510,
    skill: 'present_perfect',
    tags: ['experience', 'intermediate'],
    data: {
      context_sentence: 'Build a present perfect sentence about life experience.',
      context_translation: 'בנה משפט בהווה מושלם על ניסיון חיים.',
      correct_answer: 'She has lived in Tel Aviv for five years',
      word_chips: ['She', 'has', 'lived', 'in', 'Tel', 'Aviv', 'for', 'five', 'years'],
      common_mistake: 'Use "for" with a duration (five years) and "since" with a starting point.',
    },
  },
  {
    id: 's26',
    type: 'sentence_builder',
    difficulty: 530,
    skill: 'modal_verbs',
    tags: ['advice', 'intermediate'],
    data: {
      context_sentence: 'Build a sentence giving permission.',
      context_translation: 'בנה משפט שנותן הרשאה.',
      correct_answer: 'You may use my laptop while I am in a meeting',
      word_chips: ['You', 'may', 'use', 'my', 'laptop', 'while', 'I', 'am', 'in', 'a', 'meeting'],
      common_mistake: '"May" for permission is more formal than "can" — both are correct in casual speech.',
    },
  },
  {
    id: 's27',
    type: 'sentence_builder',
    difficulty: 550,
    skill: 'comparison',
    tags: ['comparison', 'intermediate'],
    data: {
      context_sentence: 'Build a comparative sentence about two cities.',
      context_translation: 'בנה משפט השוואתי על שתי ערים.',
      correct_answer: 'Haifa is more relaxed than Tel Aviv in the evenings',
      word_chips: ['Haifa', 'is', 'more', 'relaxed', 'than', 'Tel', 'Aviv', 'in', 'the', 'evenings'],
      common_mistake: 'Long adjectives use "more + adjective" — not "-er": "more relaxed" not "relaxeder".',
    },
  },
  {
    id: 's28',
    type: 'sentence_builder',
    difficulty: 570,
    skill: 'conditionals',
    tags: ['work', 'intermediate'],
    data: {
      context_sentence: 'Build a second conditional sentence.',
      context_translation: 'בנה משפט תנאי שני.',
      correct_answer: 'If I had more time I would learn another language',
      word_chips: ['If', 'I', 'had', 'more', 'time', 'I', 'would', 'learn', 'another', 'language'],
      common_mistake: 'Second conditional: If + past simple, would + base verb — for hypothetical situations.',
    },
  },
  {
    id: 's29',
    type: 'sentence_builder',
    difficulty: 590,
    skill: 'passive_voice',
    tags: ['work', 'intermediate'],
    data: {
      context_sentence: 'Build a passive sentence about a completed task.',
      context_translation: 'בנה משפט פסיבי על משימה שהושלמה.',
      correct_answer: 'The report was finished by the team yesterday afternoon',
      word_chips: ['The', 'report', 'was', 'finished', 'by', 'the', 'team', 'yesterday', 'afternoon'],
      common_mistake: 'Past passive: was/were + past participle. "Finished" not "finish".',
    },
  },
  {
    id: 's30',
    type: 'sentence_builder',
    difficulty: 610,
    skill: 'relative_clauses',
    tags: ['description', 'advanced'],
    data: {
      context_sentence: 'Build a sentence with a relative clause about a book.',
      context_translation: 'בנה משפט עם פסוקית יחס על ספר.',
      correct_answer: 'The novel that won the prize has been translated into twenty languages',
      word_chips: ['The', 'novel', 'that', 'won', 'the', 'prize', 'has', 'been', 'translated', 'into', 'twenty', 'languages'],
      common_mistake: 'Use "that" or "which" for things. "Who" is for people only.',
    },
  },
  {
    id: 's31',
    type: 'sentence_builder',
    difficulty: 630,
    skill: 'reported_speech',
    tags: ['communication', 'advanced'],
    data: {
      context_sentence: 'Build a reported speech sentence about a warning.',
      context_translation: 'בנה משפט בדיבור מדווח על אזהרה.',
      correct_answer: 'The doctor warned that smoking could damage his lungs',
      word_chips: ['The', 'doctor', 'warned', 'that', 'smoking', 'could', 'damage', 'his', 'lungs'],
      common_mistake: '"Can" shifts to "could" in reported speech when the reporting verb is past.',
    },
  },
  {
    id: 's32',
    type: 'sentence_builder',
    difficulty: 680,
    skill: 'vocabulary_business',
    tags: ['business', 'advanced'],
    data: {
      context_sentence: 'Build a sentence about a successful negotiation.',
      context_translation: 'בנה משפט על משא ומתן מוצלח.',
      correct_answer: 'After lengthy negotiations both sides agreed on a fair compromise',
      word_chips: ['After', 'lengthy', 'negotiations', 'both', 'sides', 'agreed', 'on', 'a', 'fair', 'compromise'],
      common_mistake: '"Agree on" a topic/decision. "Agree with" a person. "Agree to" a proposal.',
    },
  },
  {
    id: 's33',
    type: 'sentence_builder',
    difficulty: 720,
    skill: 'vocabulary_academic',
    tags: ['academic', 'advanced'],
    data: {
      context_sentence: 'Build a formal academic sentence about research findings.',
      context_translation: 'בנה משפט אקדמי רשמי על ממצאי מחקר.',
      correct_answer: 'The findings suggest that early intervention significantly improves long term outcomes',
      word_chips: ['The', 'findings', 'suggest', 'that', 'early', 'intervention', 'significantly', 'improves', 'long', 'term', 'outcomes'],
      common_mistake: 'Academic writing often uses "suggest" (not "prove") to present cautious conclusions.',
    },
  },
  // ── Expanded pool (s34+) — was / were / had / has / have / is / are ──
  {
    id: 's34',
    type: 'sentence_builder',
    difficulty: 355,
    skill: 'past_simple',
    tags: ['be-verbs', 'beginner'],
    data: {
      context_sentence: 'Build a sentence using "was" about good news.',
      context_translation: 'בנה משפט עם "was" על חדשות טובות.',
      correct_answer: 'She was happy when she got the good news',
      word_chips: ['She', 'was', 'happy', 'when', 'she', 'got', 'the', 'good', 'news'],
      common_mistake: 'Past of "be" with she/he/it: "She was" — not "She were".',
    },
  },
  {
    id: 's35',
    type: 'sentence_builder',
    difficulty: 365,
    skill: 'past_simple',
    tags: ['be-verbs', 'beginner'],
    data: {
      context_sentence: 'Build a sentence using "were" about being late.',
      context_translation: 'בנה משפט עם "were" על איחור.',
      correct_answer: 'They were late because the bus did not come',
      word_chips: ['They', 'were', 'late', 'because', 'the', 'bus', 'did', 'not', 'come'],
      common_mistake: 'With they/we/you use "were": "They were late" — not "They was late".',
    },
  },
  {
    id: 's36',
    type: 'sentence_builder',
    difficulty: 375,
    skill: 'present_perfect',
    tags: ['have-verbs', 'beginner'],
    data: {
      context_sentence: 'Build a sentence using "has" about finished homework.',
      context_translation: 'בנה משפט עם "has" על שיעורי בית שהסתיימו.',
      correct_answer: 'He has finished all his homework for today',
      word_chips: ['He', 'has', 'finished', 'all', 'his', 'homework', 'for', 'today'],
      common_mistake: 'Present Perfect: has + past participle. "Finished" not "finish".',
    },
  },
  {
    id: 's37',
    type: 'sentence_builder',
    difficulty: 385,
    skill: 'present_perfect',
    tags: ['have-verbs', 'beginner'],
    data: {
      context_sentence: 'Build a sentence using "have" and "since".',
      context_translation: 'בנה משפט עם "have" ו-"since".',
      correct_answer: 'We have lived here since twenty twenty',
      word_chips: ['We', 'have', 'lived', 'here', 'since', 'twenty', 'twenty'],
      common_mistake: '"Since" + starting point → Present Perfect. "We have lived" not "We lived".',
    },
  },
  {
    id: 's38',
    type: 'sentence_builder',
    difficulty: 395,
    skill: 'past_continuous',
    tags: ['be-verbs', 'intermediate'],
    data: {
      context_sentence: 'Build a sentence using "was" and an interrupted action.',
      context_translation: 'בנה משפט עם "was" על פעולה שהופסקה.',
      correct_answer: 'I was reading a book when the phone rang',
      word_chips: ['I', 'was', 'reading', 'a', 'book', 'when', 'the', 'phone', 'rang'],
      common_mistake: 'Past Continuous: was + verb-ing for ongoing action. Past Simple for the interruption.',
    },
  },
  {
    id: 's39',
    type: 'sentence_builder',
    difficulty: 405,
    skill: 'past_continuous',
    tags: ['be-verbs', 'intermediate'],
    data: {
      context_sentence: 'Build a sentence using "were" about students studying.',
      context_translation: 'בנה משפט עם "were" על תלמידים שלומדים.',
      correct_answer: 'The students were studying when the teacher entered the room',
      word_chips: ['The', 'students', 'were', 'studying', 'when', 'the', 'teacher', 'entered', 'the', 'room'],
      common_mistake: 'Plural subject → "were studying". The interrupting action uses Past Simple.',
    },
  },
  {
    id: 's40',
    type: 'sentence_builder',
    difficulty: 415,
    skill: 'past_perfect',
    tags: ['have-verbs', 'intermediate'],
    data: {
      context_sentence: 'Build a sentence using "had" about something that happened before your arrival.',
      context_translation: 'בנה משפט עם "had" על משהו שקרה לפני שהגעת.',
      correct_answer: 'She had already left when I arrived at the party',
      word_chips: ['She', 'had', 'already', 'left', 'when', 'I', 'arrived', 'at', 'the', 'party'],
      common_mistake: 'Past Perfect (had + past participle) for the earlier of two past events.',
    },
  },
  {
    id: 's41',
    type: 'sentence_builder',
    difficulty: 425,
    skill: 'present_continuous',
    tags: ['be-verbs', 'beginner'],
    data: {
      context_sentence: 'Build a sentence using "is" and "are" about today.',
      context_translation: 'בנה משפט עם "is" ו-"are" על היום.',
      correct_answer: 'It is very hot today and the children are tired',
      word_chips: ['It', 'is', 'very', 'hot', 'today', 'and', 'the', 'children', 'are', 'tired'],
      common_mistake: '"It is" for weather. Plural "children" takes "are tired".',
    },
  },
  {
    id: 's42',
    type: 'sentence_builder',
    difficulty: 435,
    skill: 'passive_voice',
    tags: ['be-verbs', 'intermediate'],
    data: {
      context_sentence: 'Build a passive sentence using "was".',
      context_translation: 'בנה משפט פסיבי עם "was".',
      correct_answer: 'The cake was baked by my grandmother yesterday',
      word_chips: ['The', 'cake', 'was', 'baked', 'by', 'my', 'grandmother', 'yesterday'],
      common_mistake: 'Past passive: was/were + past participle. "Baked" not "bake".',
    },
  },
  {
    id: 's43',
    type: 'sentence_builder',
    difficulty: 445,
    skill: 'present_perfect',
    tags: ['have-verbs', 'intermediate'],
    data: {
      context_sentence: 'Build a sentence using "have been" about a long friendship.',
      context_translation: 'בנה משפט עם "have been" על חברות ארוכה.',
      correct_answer: 'They have been friends since they were children',
      word_chips: ['They', 'have', 'been', 'friends', 'since', 'they', 'were', 'children'],
      common_mistake: '"Have been friends" = friendship continues. "Since" + past ("were children") → Present Perfect.',
    },
  },
  {
    id: 's44',
    type: 'sentence_builder',
    difficulty: 455,
    skill: 'past_simple',
    tags: ['be-verbs', 'beginner'],
    data: {
      context_sentence: 'Build a sentence using both "was" and "were".',
      context_translation: 'בנה משפט עם "was" ו-"were" יחד.',
      correct_answer: 'I was at the park and my friends were there too',
      word_chips: ['I', 'was', 'at', 'the', 'park', 'and', 'my', 'friends', 'were', 'there', 'too'],
      common_mistake: 'I/he/she/it → was. We/you/they → were. Both in the same past-time sentence.',
    },
  },
  {
    id: 's45',
    type: 'sentence_builder',
    difficulty: 465,
    skill: 'present_perfect',
    tags: ['have-verbs', 'intermediate'],
    data: {
      context_sentence: 'Build a negative sentence using "has not been".',
      context_translation: 'בנה משפט שלילי עם "has not been".',
      correct_answer: 'She has not been to London yet but she wants to go',
      word_chips: ['She', 'has', 'not', 'been', 'to', 'London', 'yet', 'but', 'she', 'wants', 'to', 'go'],
      common_mistake: '"Has not been to" for places never visited. "Yet" in negatives often uses Present Perfect.',
    },
  },
  {
    id: 's46',
    type: 'sentence_builder',
    difficulty: 475,
    skill: 'past_simple',
    tags: ['have-verbs', 'beginner'],
    data: {
      context_sentence: 'Build a sentence using "had" for past possession.',
      context_translation: 'בנה משפט עם "had" לביטוי בעלות בעבר.',
      correct_answer: 'He had a good idea and the team liked it',
      word_chips: ['He', 'had', 'a', 'good', 'idea', 'and', 'the', 'team', 'liked', 'it'],
      common_mistake: '"Had" = past of "have" for possession. "He had an idea" = he got/had the idea in the past.',
    },
  },
  {
    id: 's47',
    type: 'sentence_builder',
    difficulty: 485,
    skill: 'present_simple',
    tags: ['be-verbs', 'beginner'],
    data: {
      context_sentence: 'Build a sentence using "am", "is", and "are".',
      context_translation: 'בנה משפט עם "am", "is" ו-"are".',
      correct_answer: 'I am a student my brother is a doctor and my parents are teachers',
      word_chips: ['I', 'am', 'a', 'student', 'my', 'brother', 'is', 'a', 'doctor', 'and', 'my', 'parents', 'are', 'teachers'],
      common_mistake: 'I → am. He/she/it (brother) → is. Plural (parents) → are.',
    },
  },
  {
    id: 's48',
    type: 'sentence_builder',
    difficulty: 495,
    skill: 'passive_voice',
    tags: ['be-verbs', 'intermediate'],
    data: {
      context_sentence: 'Build a passive sentence using "were" about broken windows.',
      context_translation: 'בנה משפט פסיבי עם "were" על חלונות שנשברו.',
      correct_answer: 'The windows were broken during the storm last night',
      word_chips: ['The', 'windows', 'were', 'broken', 'during', 'the', 'storm', 'last', 'night'],
      common_mistake: 'Plural subject → "were broken". Past participle "broken" stays the same.',
    },
  },
  {
    id: 's49',
    type: 'sentence_builder',
    difficulty: 505,
    skill: 'past_perfect',
    tags: ['have-verbs', 'intermediate'],
    data: {
      context_sentence: 'Build a sentence using "had already" before another past event.',
      context_translation: 'בנה משפט עם "had already" לפני אירוע עבר אחר.',
      correct_answer: 'The train had already left when we got to the station',
      word_chips: ['The', 'train', 'had', 'already', 'left', 'when', 'we', 'got', 'to', 'the', 'station'],
      common_mistake: 'Past Perfect (had left) = earlier event. Past Simple (got) = later event.',
    },
  },
  {
    id: 's50',
    type: 'sentence_builder',
    difficulty: 515,
    skill: 'present_perfect',
    tags: ['have-verbs', 'intermediate'],
    data: {
      context_sentence: 'Build a sentence using "has been" about a recent change.',
      context_translation: 'בנה משפט עם "has been" על שינוי אחרון.',
      correct_answer: 'The weather has been very cold this week',
      word_chips: ['The', 'weather', 'has', 'been', 'very', 'cold', 'this', 'week'],
      common_mistake: 'Present Perfect with "be": has/have been + adjective. Period up to now ("this week").',
    },
  },
]
