import type { ContentItem } from '@/types/game'

export const SENTENCE_ITEMS: ContentItem[] = [
  {
    id: 's1',
    type: 'sentence_builder',
    difficulty: 420,
    skill: 'sentence_structure',
    tags: ['daily-life', 'beginner'],
    data: {
      context_sentence: 'Arrange the words to form a morning routine sentence.',
      context_translation: 'סדר את המילים ליצירת משפט על שגרת בוקר.',
      correct_answer: 'Every morning I drink a cup of coffee before work',
      word_chips: ['Every', 'morning', 'I', 'drink', 'a', 'cup', 'of', 'coffee', 'before', 'work'],
      common_mistake: 'Remember: subject (I) comes before the verb (drink) in declarative sentences.',
    },
  },
  {
    id: 's2',
    type: 'sentence_builder',
    difficulty: 450,
    skill: 'future_going_to',
    tags: ['travel', 'intermediate'],
    data: {
      context_sentence: 'Build a sentence about confirmed travel plans.',
      context_translation: 'בנה משפט על תוכניות נסיעה מאושרות.',
      correct_answer: 'We are planning to visit Japan next summer',
      word_chips: ['We', 'are', 'planning', 'to', 'visit', 'Japan', 'next', 'summer'],
      common_mistake: '"Planning to" expresses a firm, already-arranged intention — similar in meaning to "going to."',
    },
  },
  {
    id: 's3',
    type: 'sentence_builder',
    difficulty: 500,
    skill: 'passive_voice',
    tags: ['work', 'intermediate'],
    data: {
      context_sentence: 'Build a passive-voice sentence about a rescheduled meeting.',
      context_translation: 'בנה משפט בגוף סביל על ישיבה שנדחתה.',
      correct_answer: 'The meeting has been rescheduled to Thursday afternoon',
      word_chips: ['The', 'meeting', 'has', 'been', 'rescheduled', 'to', 'Thursday', 'afternoon'],
      common_mistake: 'Present perfect passive: "has/have been + past participle." Note: "rescheduled TO" not "rescheduled FOR."',
    },
  },
  {
    id: 's4',
    type: 'sentence_builder',
    difficulty: 540,
    skill: 'conditionals',
    tags: ['work', 'intermediate'],
    data: {
      context_sentence: 'Build a first conditional sentence about finishing work on time.',
      context_translation: 'בנה משפט תנאי ראשון על סיום עבודה בזמן.',
      correct_answer: 'If you submit the report by noon we will review it today',
      word_chips: ['If', 'you', 'submit', 'the', 'report', 'by', 'noon', 'we', 'will', 'review', 'it', 'today'],
      common_mistake: 'First conditional: "If + present simple, will + base verb." No comma is needed when the main clause comes first.',
    },
  },
  {
    id: 's5',
    type: 'sentence_builder',
    difficulty: 580,
    skill: 'vocabulary_environment',
    tags: ['environment', 'intermediate'],
    data: {
      context_sentence: 'Build a sentence about the effects of climate change.',
      context_translation: 'בנה משפט על השפעות שינויי האקלים.',
      correct_answer: 'Scientists warn that rising temperatures will affect ecosystems worldwide',
      word_chips: ['Scientists', 'warn', 'that', 'rising', 'temperatures', 'will', 'affect', 'ecosystems', 'worldwide'],
      common_mistake: 'Notice "affect" (verb) vs "effect" (noun). "Rising temperatures will affect ecosystems" — affect is the action verb here.',
    },
  },
  {
    id: 's6',
    type: 'sentence_builder',
    difficulty: 620,
    skill: 'vocabulary_technology',
    tags: ['technology', 'advanced'],
    data: {
      context_sentence: 'Build a sentence about the global impact of artificial intelligence.',
      context_translation: 'בנה משפט על ההשפעה הגלובלית של בינה מלאכותית.',
      correct_answer: 'Artificial intelligence is transforming the way businesses operate globally',
      word_chips: ['Artificial', 'intelligence', 'is', 'transforming', 'the', 'way', 'businesses', 'operate', 'globally'],
      common_mistake: '"The way businesses operate" is a noun phrase, not a relative clause. No "that" or "which" is needed here.',
    },
  },
  {
    id: 's7',
    type: 'sentence_builder',
    difficulty: 460,
    skill: 'present_perfect',
    tags: ['experience', 'intermediate'],
    data: {
      context_sentence: 'Build a present perfect sentence about travel experience.',
      context_translation: 'בנה משפט בהווה מושלם על ניסיון טיול.',
      correct_answer: 'I have never been to South America but I hope to go someday',
      word_chips: ['I', 'have', 'never', 'been', 'to', 'South', 'America', 'but', 'I', 'hope', 'to', 'go', 'someday'],
      common_mistake: '"Never" is placed between "have" and the past participle. "Have been to" means visited — "have gone to" means went and is still there.',
    },
  },
  {
    id: 's8',
    type: 'sentence_builder',
    difficulty: 500,
    skill: 'past_simple',
    tags: ['daily-life', 'beginner'],
    data: {
      context_sentence: 'Build a past simple narrative sentence.',
      context_translation: 'בנה משפט עבר פשוט נרטיבי.',
      correct_answer: 'She woke up early checked her phone and then made breakfast',
      word_chips: ['She', 'woke', 'up', 'early', 'checked', 'her', 'phone', 'and', 'then', 'made', 'breakfast'],
      common_mistake: 'Past simple with a sequence of actions: use commas for longer lists. "Woke up" is an irregular verb — not "waked up."',
    },
  },
  {
    id: 's9',
    type: 'sentence_builder',
    difficulty: 560,
    skill: 'relative_clauses',
    tags: ['description', 'intermediate'],
    data: {
      context_sentence: 'Build a sentence with a defining relative clause.',
      context_translation: 'בנה משפט עם פסוקית שם עצם מגדירה.',
      correct_answer: 'The colleague who helped me with the project received a promotion',
      word_chips: ['The', 'colleague', 'who', 'helped', 'me', 'with', 'the', 'project', 'received', 'a', 'promotion'],
      common_mistake: 'Defining relative clauses have no commas — they identify which person/thing you mean.',
    },
  },
  {
    id: 's10',
    type: 'sentence_builder',
    difficulty: 640,
    skill: 'reported_speech',
    tags: ['communication', 'advanced'],
    data: {
      context_sentence: 'Build a reported speech sentence.',
      context_translation: 'בנה משפט בדיבור עקיף.',
      correct_answer: 'The manager told the team that the deadline would be moved to Friday',
      word_chips: ['The', 'manager', 'told', 'the', 'team', 'that', 'the', 'deadline', 'would', 'be', 'moved', 'to', 'Friday'],
      common_mistake: '"Will" changes to "would" in reported speech. "The deadline will be moved" → "the deadline would be moved."',
    },
  },
  {
    id: 's11',
    type: 'sentence_builder',
    difficulty: 480,
    skill: 'modal_verbs',
    tags: ['advice', 'beginner'],
    data: {
      context_sentence: 'Build a sentence giving strong advice.',
      context_translation: 'בנה משפט שנותן עצה חזקה.',
      correct_answer: 'You should drink at least eight glasses of water every day',
      word_chips: ['You', 'should', 'drink', 'at', 'least', 'eight', 'glasses', 'of', 'water', 'every', 'day'],
      common_mistake: '"Should" for advice is followed by the base infinitive (not "to drink"). Example: "should drink" not "should to drink."',
    },
  },
  {
    id: 's12',
    type: 'sentence_builder',
    difficulty: 520,
    skill: 'comparison',
    tags: ['comparison', 'intermediate'],
    data: {
      context_sentence: 'Build a superlative sentence about a city.',
      context_translation: 'בנה משפט עם תואר השוואה עליון על עיר.',
      correct_answer: 'Tokyo is one of the most densely populated cities in the world',
      word_chips: ['Tokyo', 'is', 'one', 'of', 'the', 'most', 'densely', 'populated', 'cities', 'in', 'the', 'world'],
      common_mistake: '"One of the most…" requires a plural noun (cities, not city). Always: "one of the most + plural noun."',
    },
  },
]
