import type { ContentItem } from '@/types/game'

export const SPELLING_ITEMS: ContentItem[] = [
  // ── Intermediate — tricky everyday spellings ────────────────
  {
    id: 'sp1',
    type: 'word_spelling',
    difficulty: 520,
    skill: 'vocabulary_academic',
    tags: ['spelling', 'intermediate'],
    data: {
      word: 'Separate',
      translation: 'נפרד / להפריד',
      context_sentence: 'Please keep the raw meat ___ from the vegetables.',
      context_translation: 'אנא שמור על הבשר הנא על ___ מהירקות.',
      correct_answer: 'Separate',
      alternate_answers: ['separate'],
      common_mistake: 'Remember: "separate" has "a" in the middle — not "seperate". Mnemonic: "There is a rat in separate."',
    },
  },
  {
    id: 'sp2',
    type: 'word_spelling',
    difficulty: 530,
    skill: 'vocabulary_academic',
    tags: ['spelling', 'intermediate'],
    data: {
      word: 'Necessary',
      translation: 'הכרחי / נחוץ',
      context_sentence: 'It is ___ to bring your passport to the airport.',
      context_translation: '___ להביא את הדרכון לשדה התעופה.',
      correct_answer: 'Necessary',
      alternate_answers: ['necessary'],
      common_mistake: 'One "c", two "s"s: ne-ces-sary. Not "neccessary" or "necesary".',
    },
  },
  {
    id: 'sp3',
    type: 'word_spelling',
    difficulty: 540,
    skill: 'vocabulary_travel',
    tags: ['spelling', 'intermediate'],
    data: {
      word: 'Accommodation',
      translation: 'לינה / מקום לינה',
      context_sentence: 'We booked ___ near the city centre for three nights.',
      context_translation: 'הזמנו ___ ליד מרכז העיר לשלוש לילות.',
      correct_answer: 'Accommodation',
      alternate_answers: ['accommodation'],
      common_mistake: 'Double "c" and double "m": ac-com-mo-da-tion. British spelling uses one "l" in "travelled" but two "m"s here.',
    },
  },
  {
    id: 'sp4',
    type: 'word_spelling',
    difficulty: 550,
    skill: 'vocabulary_academic',
    tags: ['spelling', 'intermediate'],
    data: {
      word: 'Occurrence',
      translation: 'מקרה / התרחשות',
      context_sentence: 'Power cuts are a rare ___ in this neighbourhood.',
      context_translation: 'הפסקות חשמל הן ___ נדירה בשכונה הזו.',
      correct_answer: 'Occurrence',
      alternate_answers: ['occurrence'],
      common_mistake: 'Double "c", double "r": oc-cur-rence. Not "occurance" or "ocurence".',
    },
  },
  {
    id: 'sp5',
    type: 'word_spelling',
    difficulty: 560,
    skill: 'vocabulary_academic',
    tags: ['spelling', 'intermediate'],
    data: {
      word: 'Independent',
      translation: 'עצמאי',
      context_sentence: 'She became financially ___ after starting her own business.',
      context_translation: 'היא הפכה ___ כלכלית אחרי שהקימה עסק משלה.',
      correct_answer: 'Independent',
      alternate_answers: ['independent'],
      common_mistake: 'Ends in "-ent", not "-ant": independ-ent. The noun is "independence".',
    },
  },
  {
    id: 'sp6',
    type: 'word_spelling',
    difficulty: 570,
    skill: 'vocabulary_environment',
    tags: ['spelling', 'intermediate'],
    data: {
      word: 'Environment',
      translation: 'סביבה',
      context_sentence: 'We must protect the natural ___ for future generations.',
      context_translation: 'עלינו להגן על ה___ הטבעית לדורות הבאים.',
      correct_answer: 'Environment',
      alternate_answers: ['environment'],
      common_mistake: 'n before m: en-vi-ron-ment. A very common error is "enviroment" (missing "n").',
    },
  },
  {
    id: 'sp7',
    type: 'word_spelling',
    difficulty: 580,
    skill: 'vocabulary_academic',
    tags: ['spelling', 'intermediate'],
    data: {
      word: 'Recommend',
      translation: 'להמליץ',
      context_sentence: 'I strongly ___ this book to anyone learning English.',
      context_translation: 'אני ___ בחום את הספר הזה לכל מי שלומד אנגלית.',
      correct_answer: 'Recommend',
      alternate_answers: ['recommend'],
      common_mistake: 'One "c", double "m": re-com-mend. Not "reccomend".',
    },
  },
  {
    id: 'sp8',
    type: 'word_spelling',
    difficulty: 590,
    skill: 'vocabulary_business',
    tags: ['spelling', 'intermediate'],
    data: {
      word: 'Maintenance',
      translation: 'תחזוקה',
      context_sentence: 'Regular ___ of the equipment prevents costly breakdowns.',
      context_translation: '___ קבועה של הציוד מונעת תקלות יקרות.',
      correct_answer: 'Maintenance',
      alternate_answers: ['maintenance'],
      common_mistake: 'Main-ten-ance — the "ten" is in the middle. Not "maintainance".',
    },
  },
  {
    id: 'sp9',
    type: 'word_spelling',
    difficulty: 600,
    skill: 'vocabulary_academic',
    tags: ['spelling', 'intermediate'],
    data: {
      word: 'Definitely',
      translation: 'בהחלט / בוודאות',
      context_sentence: 'I will ___ be at the meeting tomorrow morning.',
      context_translation: 'אני ___ אהיה בפגישה מחר בבוקר.',
      correct_answer: 'Definitely',
      alternate_answers: ['definitely'],
      common_mistake: 'Has "finite" inside: de-finite-ly. Never write "definately" or "defiantly" (different word).',
    },
  },
  {
    id: 'sp10',
    type: 'word_spelling',
    difficulty: 610,
    skill: 'vocabulary_business',
    tags: ['spelling', 'intermediate'],
    data: {
      word: 'Privilege',
      translation: 'זכות / פריבילגיה',
      context_sentence: 'Access to this data is a ___ granted only to senior staff.',
      context_translation: 'גישה לנתונים האלה היא ___ שניתנת רק לעובדים בכירים.',
      correct_answer: 'Privilege',
      alternate_answers: ['privilege'],
      common_mistake: 'i before leg: priv-i-lege. Not "priviledge" (no "d").',
    },
  },
  // ── Advanced — longer / less intuitive spellings ────────────
  {
    id: 'sp11',
    type: 'word_spelling',
    difficulty: 660,
    skill: 'vocabulary_business',
    tags: ['spelling', 'advanced'],
    data: {
      word: 'Bureaucracy',
      translation: 'בירוקרטיה',
      context_sentence: 'The project was delayed by excessive ___ in the approval process.',
      context_translation: 'הפרויקט התעכב בגלל ___ מוגזמת בתהליך האישור.',
      correct_answer: 'Bureaucracy',
      alternate_answers: ['bureaucracy'],
      common_mistake: 'French origin: bureau + cracy. The "eau" in bureau sounds like "oh".',
    },
  },
  {
    id: 'sp12',
    type: 'word_spelling',
    difficulty: 680,
    skill: 'vocabulary_academic',
    tags: ['spelling', 'advanced'],
    data: {
      word: 'Conscientious',
      translation: 'קפדן / יסודי',
      context_sentence: 'She is a ___ worker who always checks her work twice.',
      context_translation: 'היא עובדת ___ שתמיד בודקת את עבודתה פעמיים.',
      correct_answer: 'Conscientious',
      alternate_answers: ['conscientious'],
      common_mistake: 'sci in the middle: con-sci-en-tious. Related to "conscience", not "conscious".',
    },
  },
  {
    id: 'sp13',
    type: 'word_spelling',
    difficulty: 700,
    skill: 'vocabulary_travel',
    tags: ['spelling', 'advanced'],
    data: {
      word: 'Mediterranean',
      translation: 'ים תיכוני / ים-תיכוני',
      context_sentence: 'They spent their holiday on a ___ cruise.',
      context_translation: 'הם בילו את החופשה שלהם בשייט ___ .',
      correct_answer: 'Mediterranean',
      alternate_answers: ['mediterranean'],
      common_mistake: 'Double "r", double "n": Med-i-ter-ran-ean. Break it into syllables when spelling.',
    },
  },
  {
    id: 'sp14',
    type: 'word_spelling',
    difficulty: 720,
    skill: 'vocabulary_emotions',
    tags: ['spelling', 'advanced'],
    data: {
      word: 'Mischievous',
      translation: 'שובב / מציק',
      context_sentence: 'The ___ child hid his sister\'s toys as a prank.',
      context_translation: 'הילד ___ הסתיר את הצעצועים של אחותו כמתיחה.',
      correct_answer: 'Mischievous',
      alternate_answers: ['mischievous'],
      common_mistake: 'Ends in "-evous", not "-ious": mis-chiev-ous. Do not add an extra "i" (not "mischievious").',
    },
  },
  {
    id: 'sp15',
    type: 'word_spelling',
    difficulty: 740,
    skill: 'vocabulary_academic',
    tags: ['spelling', 'advanced'],
    data: {
      word: 'Pronunciation',
      translation: 'הגייה',
      context_sentence: 'Good ___ is essential for clear communication.',
      context_translation: '___ טובה חיונית לתקשורת ברורה.',
      correct_answer: 'Pronunciation',
      alternate_answers: ['pronunciation'],
      common_mistake: 'Noun from "pronounce" — but spelled pro-nun-ci-a-tion (not "pronounciation").',
    },
  },
  {
    id: 'sp16',
    type: 'word_spelling',
    difficulty: 760,
    skill: 'vocabulary_business',
    tags: ['spelling', 'advanced'],
    data: {
      word: 'Hierarchy',
      translation: 'היררכיה',
      context_sentence: 'Decision-making follows a strict ___ in the organisation.',
      context_translation: 'קבלת החלטות עוקבת אחר ___ קפדנית בארגון.',
      correct_answer: 'Hierarchy',
      alternate_answers: ['hierarchy'],
      common_mistake: 'Ends in "-archy" (like monarchy): hi-er-ar-chy. Not "heirarchy".',
    },
  },
  // ── Master — very complex spellings ─────────────────────────
  {
    id: 'sp17',
    type: 'word_spelling',
    difficulty: 820,
    skill: 'vocabulary_academic',
    tags: ['spelling', 'master'],
    data: {
      word: 'Onomatopoeia',
      translation: 'מילה המחקה צליל',
      context_sentence: 'Words like "buzz" and "splash" are examples of ___.',
      context_translation: 'מילים כמו "buzz" ו-"splash" הן דוגמאות ל___.',
      correct_answer: 'Onomatopoeia',
      alternate_answers: ['onomatopoeia'],
      common_mistake: 'o-e-i-a at the end: ono-mato-poe-ia. Say each syllable aloud while spelling.',
    },
  },
  {
    id: 'sp18',
    type: 'word_spelling',
    difficulty: 850,
    skill: 'vocabulary_academic',
    tags: ['spelling', 'master'],
    data: {
      word: 'Idiosyncrasy',
      translation: 'ייחודיות / הרגל מיוחד',
      context_sentence: 'Drinking tea at exactly four o\'clock was one of his little ___.',
      context_translation: 'שתיית תה בדיוק בארבע הייתה אחת מה___ הקטנות שלו.',
      correct_answer: 'Idiosyncrasy',
      alternate_answers: ['idiosyncrasy'],
      common_mistake: 'Ends in "-crasy" (not "-cracy"): idio-syn-crasy. Plural: idiosyncrasies.',
    },
  },
  {
    id: 'sp19',
    type: 'word_spelling',
    difficulty: 870,
    skill: 'vocabulary_academic',
    tags: ['spelling', 'master'],
    data: {
      word: 'Supersede',
      translation: 'להחליף / לגבור על',
      context_sentence: 'The new software will ___ the outdated version next month.',
      context_translation: 'התוכנה החדשה ___ את הגרסה המיושנת בחודש הבא.',
      correct_answer: 'Supersede',
      alternate_answers: ['supersede'],
      common_mistake: 'Only one "s" and ends in "-sede" (not "-cede"): super-sede. Think "super + sede", not "supercede".',
    },
  },
  {
    id: 'sp20',
    type: 'word_spelling',
    difficulty: 890,
    skill: 'vocabulary_academic',
    tags: ['spelling', 'master'],
    data: {
      word: 'Manoeuvre',
      translation: 'תמרון / maneuvre',
      context_sentence: 'The pilot had to perform a difficult ___ to avoid the storm.',
      context_translation: 'הטייס נאלץ לבצע ___ קשה כדי להימנע מהסערה.',
      correct_answer: 'Manoeuvre',
      alternate_answers: ['manoeuvre', 'Maneuver', 'maneuver'],
      common_mistake: 'British: manoeuvre (oeu). American: maneuver. Both are accepted here.',
    },
  },
  {
    id: 'sp21',
    type: 'word_spelling',
    difficulty: 380,
    skill: 'vocabulary_travel',
    tags: ['spelling', 'beginner'],
    data: {
      word: 'Airport',
      translation: 'שדה תעופה',
      context_sentence: 'We arrived at the ___ two hours early.',
      context_translation: 'הגענו ל___ שעתיים מוקדם.',
      correct_answer: 'Airport',
      alternate_answers: ['airport'],
      common_mistake: 'One word: airport — not "air port".',
    },
  },
  {
    id: 'sp22',
    type: 'word_spelling',
    difficulty: 395,
    skill: 'vocabulary_emotions',
    tags: ['spelling', 'beginner'],
    data: {
      word: 'Happy',
      translation: 'שמח / מאושר',
      context_sentence: 'The children were ___ to see their grandparents.',
      context_translation: 'הילדים היו ___ לראות את הסבא והסבתא.',
      correct_answer: 'Happy',
      alternate_answers: ['happy'],
      common_mistake: 'Double "p" in happy — not "hapy".',
    },
  },
  {
    id: 'sp23',
    type: 'word_spelling',
    difficulty: 410,
    skill: 'vocabulary_business',
    tags: ['spelling', 'beginner'],
    data: {
      word: 'Meeting',
      translation: 'פגישה / ישיבה',
      context_sentence: 'The team has a ___ every Monday morning.',
      context_translation: 'הצוות מקיים ___ כל יום שני בבוקר.',
      correct_answer: 'Meeting',
      alternate_answers: ['meeting'],
      common_mistake: 'Double "e" in meeting — not "meating" (which means food).',
    },
  },
  {
    id: 'sp24',
    type: 'word_spelling',
    difficulty: 425,
    skill: 'vocabulary_technology',
    tags: ['spelling', 'beginner'],
    data: {
      word: 'Password',
      translation: 'סיסמה',
      context_sentence: 'Never share your ___ with colleagues.',
      context_translation: 'אל תשתף את ה___ שלך עם עמיתים לעבודה.',
      correct_answer: 'Password',
      alternate_answers: ['password'],
      common_mistake: 'One word: password — not "pass word".',
    },
  },
  {
    id: 'sp25',
    type: 'word_spelling',
    difficulty: 440,
    skill: 'vocabulary_environment',
    tags: ['spelling', 'beginner'],
    data: {
      word: 'Climate',
      translation: 'אקלים',
      context_sentence: 'The ___ in this region is hot and dry.',
      context_translation: 'ה___ באזור הזה חם ויבש.',
      correct_answer: 'Climate',
      alternate_answers: ['climate'],
      common_mistake: 'Not the same as "weather" — climate is long-term.',
    },
  },
  {
    id: 'sp26',
    type: 'word_spelling',
    difficulty: 455,
    skill: 'vocabulary_academic',
    tags: ['spelling', 'beginner'],
    data: {
      word: 'Library',
      translation: 'ספרייה',
      context_sentence: 'She borrowed two books from the university ___.',
      context_translation: 'היא הלוותה שני ספרים מה___ של האוניברסיטה.',
      correct_answer: 'Library',
      alternate_answers: ['library'],
      common_mistake: 'Ends in "-ary" — not "libary" (missing r).',
    },
  },
]
