import type { ContentItem } from '@/types/game'

export const VOCABULARY_ITEMS: ContentItem[] = [
  // ── Emotions ──────────────────────────────────────────────
  {
    id: 'v1',
    type: 'vocabulary',
    difficulty: 420,
    skill: 'vocabulary_emotions',
    tags: ['emotions', 'adjectives', 'beginner'],
    data: {
      word: 'Melancholy',
      translation: 'עצבות עמוקה / נוסטלגיה עצובה',
      context_sentence: 'She felt a deep melancholy as she looked at old family photographs.',
      context_translation: 'היא חשה עצבות עמוקה כשהסתכלה על תמונות ישנות של המשפחה.',
      correct_answer: 'Melancholy',
      common_mistake: 'Do not confuse with "sadness" — melancholy implies a reflective, lingering quality.',
    },
  },
  {
    id: 'v2',
    type: 'vocabulary',
    difficulty: 460,
    skill: 'vocabulary_emotions',
    tags: ['emotions', 'adjectives'],
    data: {
      word: 'Apprehensive',
      translation: 'חרד / מודאג לקראת משהו עתידי',
      context_sentence: 'He was apprehensive about the job interview, barely sleeping the night before.',
      context_translation: 'הוא היה חרד לקראת ראיון העבודה וכמעט לא ישן בלילה שלפני.',
      correct_answer: 'Apprehensive',
      common_mistake: '"Apprehensive" is about anticipating something bad — not the same as generally anxious.',
    },
  },
  {
    id: 'v3',
    type: 'vocabulary',
    difficulty: 510,
    skill: 'vocabulary_emotions',
    tags: ['emotions', 'adjectives', 'intermediate'],
    data: {
      word: 'Exhilarated',
      translation: 'מלא התלהבות / אקסטזה של שמחה',
      context_sentence: 'The crowd was exhilarated when the team scored the winning goal in extra time.',
      context_translation: 'הקהל היה מלא התלהבות כשהקבוצה כבשה שער הניצחון בהארכה.',
      correct_answer: 'Exhilarated',
      common_mistake: 'Stronger than "excited" — implies a rush of energy and elation.',
    },
  },
  {
    id: 'v4',
    type: 'vocabulary',
    difficulty: 560,
    skill: 'vocabulary_emotions',
    tags: ['emotions', 'adjectives'],
    data: {
      word: 'Ambivalent',
      translation: 'אמביוולנטי / בעל רגשות מעורבים',
      context_sentence: 'She felt ambivalent about moving abroad — excited for the opportunity but sad to leave her family.',
      context_translation: 'היא חשה בעלת רגשות מעורבים לגבי המעבר לחו"ל — נרגשת מהאפשרות אך עצובה לעזוב את משפחתה.',
      correct_answer: 'Ambivalent',
      common_mistake: 'Does not mean "indifferent" — it means having BOTH positive and negative feelings simultaneously.',
    },
  },
  // ── Business ──────────────────────────────────────────────
  {
    id: 'v5',
    type: 'vocabulary',
    difficulty: 480,
    skill: 'vocabulary_business',
    tags: ['work', 'nouns', 'intermediate'],
    data: {
      word: 'Diligent',
      translation: 'חרוץ / שקדן',
      context_sentence: 'The diligent student reviewed her notes every evening without fail.',
      context_translation: 'הסטודנטית החרוצה עברה על הערותיה כל ערב ללא יוצא מן הכלל.',
      correct_answer: 'Diligent',
      common_mistake: 'Diligent emphasises careful, persistent effort — not just being "hard-working".',
    },
  },
  {
    id: 'v6',
    type: 'vocabulary',
    difficulty: 520,
    skill: 'vocabulary_business',
    tags: ['business', 'nouns'],
    data: {
      word: 'Leverage',
      translation: 'מינוף / להשתמש ביתרון',
      context_sentence: 'The startup decided to leverage its social media following to attract new investors.',
      context_translation: 'הסטארט-אפ החליט למנף את כמות העוקבים שלו ברשתות החברתיות כדי למשוך משקיעים חדשים.',
      correct_answer: 'Leverage',
      common_mistake: 'As a verb: "to leverage" means to use something to maximum advantage.',
    },
  },
  {
    id: 'v7',
    type: 'vocabulary',
    difficulty: 570,
    skill: 'vocabulary_business',
    tags: ['business', 'adjectives'],
    data: {
      word: 'Stringent',
      translation: 'מחמיר / נוקשה (לגבי כללים)',
      context_sentence: 'The new data privacy law introduced stringent requirements for all online businesses.',
      context_translation: 'חוק פרטיות הנתונים החדש הכניס דרישות מחמירות לכל עסקי האינטרנט.',
      correct_answer: 'Stringent',
      common_mistake: 'Describes rules/conditions that are strict and difficult to satisfy.',
    },
  },
  {
    id: 'v8',
    type: 'vocabulary',
    difficulty: 620,
    skill: 'vocabulary_business',
    tags: ['business', 'verbs', 'advanced'],
    data: {
      word: 'Mitigate',
      translation: 'להפחית / למתן (סיכון או נזק)',
      context_sentence: 'The company implemented new safeguards to mitigate the risk of a data breach.',
      context_translation: 'החברה יישמה אמצעי הגנה חדשים כדי להפחית את הסיכון לפרצת נתונים.',
      correct_answer: 'Mitigate',
      common_mistake: '"Mitigate" means to lessen severity — do not confuse with "eliminate".',
    },
  },
  // ── Travel ────────────────────────────────────────────────
  {
    id: 'v9',
    type: 'vocabulary',
    difficulty: 430,
    skill: 'vocabulary_travel',
    tags: ['travel', 'nouns', 'beginner'],
    data: {
      word: 'Itinerary',
      translation: 'מסלול / לוח זמנים של טיול',
      context_sentence: "The travel agent sent a detailed itinerary listing every hotel, flight, and excursion.",
      context_translation: 'סוכן הנסיעות שלח מסלול מפורט המפרט כל מלון, טיסה וטיול.',
      correct_answer: 'Itinerary',
      common_mistake: 'Pronounced /ɪˈtɪn.ər.ər.i/ — five syllables. Often misspelled.',
    },
  },
  {
    id: 'v10',
    type: 'vocabulary',
    difficulty: 490,
    skill: 'vocabulary_travel',
    tags: ['travel', 'adjectives'],
    data: {
      word: 'Scenic',
      translation: 'ציורי / בעל נוף יפה',
      context_sentence: 'They chose the scenic coastal route even though it added two hours to the drive.',
      context_translation: 'הם בחרו במסלול החוף הציורי למרות שהוסיף שעתיים לנסיעה.',
      correct_answer: 'Scenic',
      common_mistake: '"Scenic" relates to beautiful natural or landscape views — not decorations inside a place.',
    },
  },
  {
    id: 'v11',
    type: 'vocabulary',
    difficulty: 540,
    skill: 'vocabulary_travel',
    tags: ['travel', 'nouns'],
    data: {
      word: 'Layover',
      translation: 'עצירת ביניים (בשדה תעופה)',
      context_sentence: 'Their flight to Tokyo included a six-hour layover in Dubai.',
      context_translation: 'הטיסה שלהם לטוקיו כללה עצירת ביניים של שש שעות בדובאי.',
      correct_answer: 'Layover',
      common_mistake: 'In British English this is often called a "stopover". Both are correct.',
    },
  },
  // ── Technology ────────────────────────────────────────────
  {
    id: 'v12',
    type: 'vocabulary',
    difficulty: 500,
    skill: 'vocabulary_technology',
    tags: ['technology', 'nouns'],
    data: {
      word: 'Algorithm',
      translation: 'אלגוריתם / רצף הוראות לפתרון בעיה',
      context_sentence: 'The streaming platform uses an algorithm to recommend shows based on your viewing history.',
      context_translation: 'פלטפורמת הסטרימינג משתמשת באלגוריתם להמלצת תוכניות על בסיס היסטוריית הצפייה שלך.',
      correct_answer: 'Algorithm',
      common_mistake: 'Often mispronounced: /ˈæl.ɡə.rɪ.ðəm/ — stress on the first syllable.',
    },
  },
  {
    id: 'v13',
    type: 'vocabulary',
    difficulty: 550,
    skill: 'vocabulary_technology',
    tags: ['technology', 'nouns', 'intermediate'],
    data: {
      word: 'Encryption',
      translation: 'הצפנה',
      context_sentence: 'End-to-end encryption ensures that only the sender and recipient can read the messages.',
      context_translation: 'הצפנה מקצה לקצה מבטיחה שרק השולח והנמען יכולים לקרוא את ההודעות.',
      correct_answer: 'Encryption',
      common_mistake: 'Do not confuse "encrypt" (verb) with "encode" — encryption specifically implies security.',
    },
  },
  {
    id: 'v14',
    type: 'vocabulary',
    difficulty: 640,
    skill: 'vocabulary_technology',
    tags: ['technology', 'adjectives', 'advanced'],
    data: {
      word: 'Obsolete',
      translation: 'מיושן / שאינו בשימוש עוד',
      context_sentence: 'With the rapid pace of innovation, many skills can become obsolete within a decade.',
      context_translation: 'עם קצב החדשנות המהיר, מיומנויות רבות יכולות להפוך למיושנות תוך עשור.',
      correct_answer: 'Obsolete',
      common_mistake: '"Obsolete" means no longer in use, not just old — something old but still used is "dated" or "vintage".',
    },
  },
  // ── Environment ───────────────────────────────────────────
  {
    id: 'v15',
    type: 'vocabulary',
    difficulty: 530,
    skill: 'vocabulary_environment',
    tags: ['environment', 'nouns'],
    data: {
      word: 'Biodiversity',
      translation: 'מגוון ביולוגי',
      context_sentence: 'Tropical rainforests contain the greatest biodiversity of any ecosystem on Earth.',
      context_translation: 'יערות הגשם הטרופיים מכילים את המגוון הביולוגי הגדול ביותר מכל מערכת אקולוגית בכדור הארץ.',
      correct_answer: 'Biodiversity',
      common_mistake: 'Refers to variety of species, not just quantity. A rainforest and a fish farm may both have many organisms but only one has true biodiversity.',
    },
  },
  {
    id: 'v16',
    type: 'vocabulary',
    difficulty: 580,
    skill: 'vocabulary_environment',
    tags: ['environment', 'adjectives'],
    data: {
      word: 'Sustainable',
      translation: 'בר-קיימא',
      context_sentence: 'The local government launched a sustainable transport initiative to reduce carbon emissions.',
      context_translation: 'הממשל המקומי השיק יוזמת תחבורה בת-קיימא להפחתת פליטות פחמן.',
      correct_answer: 'Sustainable',
      common_mistake: '"Sustainable" means able to be maintained long-term without depleting resources — stronger than just "eco-friendly".',
    },
  },
  // ── Academic ──────────────────────────────────────────────
  {
    id: 'v17',
    type: 'vocabulary',
    difficulty: 590,
    skill: 'vocabulary_academic',
    tags: ['academic', 'nouns'],
    data: {
      word: 'Hypothesis',
      translation: 'השערה / הנחת עבודה',
      context_sentence: 'Before beginning the experiment, the researcher stated a clear hypothesis that she intended to test.',
      context_translation: 'לפני תחילת הניסוי, הציגה החוקרת השערה ברורה שבכוונתה לבדוק.',
      correct_answer: 'Hypothesis',
      common_mistake: 'A hypothesis is a testable prediction, not yet proven. Once proven, it may become a theory.',
    },
  },
  {
    id: 'v18',
    type: 'vocabulary',
    difficulty: 610,
    skill: 'vocabulary_academic',
    tags: ['academic', 'nouns', 'advanced'],
    data: {
      word: 'Ambiguity',
      translation: 'עמימות / חוסר בהירות',
      context_sentence: "The contract was full of ambiguity, making it hard to determine each party's responsibilities.",
      context_translation: 'החוזה היה מלא עמימות, מה שהקשה לקבוע את אחריות כל צד.',
      correct_answer: 'Ambiguity',
      common_mistake: '"Ambiguity" is a noun. The adjective is "ambiguous." The adverb is "ambiguously."',
    },
  },
  {
    id: 'v19',
    type: 'vocabulary',
    difficulty: 650,
    skill: 'vocabulary_academic',
    tags: ['academic', 'verbs', 'advanced'],
    data: {
      word: 'Corroborate',
      translation: 'לאשר / לחזק (ראיות)',
      context_sentence: 'The second witness came forward to corroborate the original testimony given in court.',
      context_translation: 'העד השני התייצב כדי לאשר את העדות המקורית שניתנה בבית המשפט.',
      correct_answer: 'Corroborate',
      common_mistake: '"Corroborate" specifically means to confirm evidence already presented — stronger than "support."',
    },
  },
  // ── Idioms ────────────────────────────────────────────────
  {
    id: 'v20',
    type: 'vocabulary',
    difficulty: 470,
    skill: 'vocabulary_idioms',
    tags: ['idioms', 'beginner'],
    data: {
      word: 'Bite the bullet',
      translation: 'לנשוך את הכדור — לעשות משהו כואב אך הכרחי',
      context_sentence: 'I hate going to the dentist, but I decided to bite the bullet and make an appointment.',
      context_translation: 'אני שונא ללכת לרופא שיניים, אבל החלטתי "לנשוך את הכדור" ולקבוע תור.',
      correct_answer: 'Bite the bullet',
      common_mistake: 'Do not use this idiom for physical pain alone — it specifically means accepting something unpleasant because it is necessary.',
    },
  },
  {
    id: 'v21',
    type: 'vocabulary',
    difficulty: 510,
    skill: 'vocabulary_idioms',
    tags: ['idioms'],
    data: {
      word: 'Burn bridges',
      translation: 'לשרוף גשרים — לקצץ קשרים בצורה שלא ניתן לחזור',
      context_sentence: 'She left the company on bad terms, effectively burning bridges with most of her former colleagues.',
      context_translation: 'היא עזבה את החברה בתנאים רעים, ובעצם שרפה גשרים עם רוב עמיתיה לשעבר.',
      correct_answer: 'Burn bridges',
      common_mistake: 'Usually used as a warning: "don\'t burn your bridges" — implying you may need those contacts later.',
    },
  },
  {
    id: 'v22',
    type: 'vocabulary',
    difficulty: 560,
    skill: 'vocabulary_idioms',
    tags: ['idioms', 'intermediate'],
    data: {
      word: 'On the fence',
      translation: 'על הגדר — לא להחליט לאיזה צד לעמוד',
      context_sentence: 'Many voters were on the fence about the new policy until the details were published.',
      context_translation: 'מצביעים רבים לא החליטו לגבי המדיניות החדשה עד שהפרטים פורסמו.',
      correct_answer: 'On the fence',
      common_mistake: 'Means undecided between two clear options — different from "confused" (which implies lack of understanding).',
    },
  },
  {
    id: 'v23',
    type: 'vocabulary',
    difficulty: 600,
    skill: 'vocabulary_idioms',
    tags: ['idioms', 'advanced'],
    data: {
      word: 'Spill the beans',
      translation: 'לשפוך את השעועית — לגלות סוד בטעות',
      context_sentence: 'He accidentally spilled the beans about the surprise party when he mentioned it to her sister.',
      context_translation: 'הוא בטעות גילה את הסוד על מסיבת ההפתעה כשציין זאת בפני אחותה.',
      correct_answer: 'Spill the beans',
      common_mistake: 'Always implies accidental disclosure of secret information. The "spilling" is unintentional.',
    },
  },
  // ── Nature / Adjectives ───────────────────────────────────
  {
    id: 'v24',
    type: 'vocabulary',
    difficulty: 530,
    skill: 'vocabulary_environment',
    tags: ['nature', 'adjectives', 'intermediate'],
    data: {
      word: 'Serene',
      translation: 'שליו / שקט ורגוע',
      context_sentence: 'The lake at dawn was completely serene, with no wind to disturb the surface.',
      context_translation: 'האגם בשחר היה שליו לחלוטין, ללא רוח שתפריע לפני המים.',
      correct_answer: 'Serene',
      common_mistake: '"Serene" implies peaceful calm, often of a place or a person\'s expression — more poetic than just "quiet."',
    },
  },
  {
    id: 'v25',
    type: 'vocabulary',
    difficulty: 580,
    skill: 'vocabulary_academic',
    tags: ['social', 'verbs', 'intermediate'],
    data: {
      word: 'Persuade',
      translation: 'לשכנע',
      context_sentence: 'He tried to persuade his manager to approve the new project proposal by presenting solid data.',
      context_translation: 'הוא ניסה לשכנע את מנהלו לאשר את הצעת הפרויקט החדשה על ידי הצגת נתונים מוצקים.',
      correct_answer: 'Persuade',
      common_mistake: '"Persuade" requires someone to actually change their mind. "Try to persuade" does not guarantee success. Contrast with "convince."',
    },
  },
  {
    id: 'v26',
    type: 'vocabulary',
    difficulty: 460,
    skill: 'vocabulary_business',
    tags: ['business', 'adjectives'],
    data: {
      word: 'Pragmatic',
      translation: 'פרגמטי / מעשי',
      context_sentence: 'A pragmatic leader focuses on what works in practice, not just what sounds good in theory.',
      context_translation: 'מנהיג פרגמטי מתמקד במה שעובד בפועל, לא רק במה שנשמע טוב בתיאוריה.',
      correct_answer: 'Pragmatic',
      common_mistake: '"Pragmatic" is about practical outcomes — not cold or uncaring, just realistic.',
    },
  },
  {
    id: 'v27',
    type: 'vocabulary',
    difficulty: 670,
    skill: 'vocabulary_academic',
    tags: ['academic', 'adjectives', 'advanced'],
    data: {
      word: 'Paradoxical',
      translation: 'פרדוקסלי / סותר את עצמו',
      context_sentence: 'It is paradoxical that the more choices we have, the less satisfied we often feel with our decisions.',
      context_translation: 'זה פרדוקסלי שככל שיש לנו יותר אפשרויות, לעתים קרובות אנו מרגישים פחות מרוצים מהחלטותינו.',
      correct_answer: 'Paradoxical',
      common_mistake: 'A paradox appears self-contradictory but may still be true — do not confuse with "ironic."',
    },
  },
  {
    id: 'v28',
    type: 'vocabulary',
    difficulty: 500,
    skill: 'vocabulary_travel',
    tags: ['travel', 'nouns'],
    data: {
      word: 'Accommodation',
      translation: 'לינה / מקום מגורים זמני',
      context_sentence: 'We booked our accommodation well in advance to get the best price during peak season.',
      context_translation: 'הזמנו את הלינה מראש כדי לקבל את המחיר הטוב ביותר בעונת השיא.',
      correct_answer: 'Accommodation',
      common_mistake: 'Note the spelling: double "c" and double "m". Common misspelling: "acommodation".',
    },
  },
  {
    id: 'v29',
    type: 'vocabulary',
    difficulty: 440,
    skill: 'vocabulary_emotions',
    tags: ['emotions', 'adjectives'],
    data: {
      word: 'Overwhelmed',
      translation: 'מוצף / שקוע יותר מדי',
      context_sentence: 'She felt overwhelmed by the sheer number of emails waiting in her inbox on Monday morning.',
      context_translation: 'היא הרגישה מוצפת מכמות האימיילים שהמתינו בתיבת הדואר שלה בבוקר יום שני.',
      correct_answer: 'Overwhelmed',
      common_mistake: '"Overwhelmed" can be used for both negative situations (stress) and positive ones (overwhelmed with joy).',
    },
  },
  {
    id: 'v30',
    type: 'vocabulary',
    difficulty: 620,
    skill: 'vocabulary_business',
    tags: ['business', 'nouns', 'advanced'],
    data: {
      word: 'Accountability',
      translation: 'אחריותיות / מחויבות לתוצאות',
      context_sentence: "The new manager introduced a culture of accountability where every team member owned their results.",
      context_translation: 'המנהל החדש הכניס תרבות של אחריותיות שבה כל חבר צוות היה אחראי לתוצאותיו.',
      correct_answer: 'Accountability',
      common_mistake: '"Accountability" means being answerable for outcomes, not just being responsible for tasks.',
    },
  },
  // ── Beginner (Tier 1) ─────────────────────────────────────
  {
    id: 'v31',
    type: 'vocabulary',
    difficulty: 350,
    skill: 'vocabulary_travel',
    tags: ['basics', 'beginner'],
    data: {
      word: 'Hello',
      translation: 'שלום',
      context_sentence: 'Hello! My name is Tom.',
      context_translation: 'שלום! קוראים לי טום.',
      correct_answer: 'Hello',
      common_mistake: 'Use "Hello" as a general greeting. "Hi" is informal but also correct in casual settings.',
    },
  },
  {
    id: 'v32',
    type: 'vocabulary',
    difficulty: 360,
    skill: 'vocabulary_travel',
    tags: ['basics', 'beginner'],
    data: {
      word: 'Water',
      translation: 'מים',
      context_sentence: 'Can I have a glass of water, please?',
      context_translation: 'אפשר לקבל כוס מים, בבקשה?',
      correct_answer: 'Water',
      common_mistake: '"Water" is uncountable — say "a glass of water", not "a water".',
    },
  },
  {
    id: 'v33',
    type: 'vocabulary',
    difficulty: 370,
    skill: 'vocabulary_travel',
    tags: ['basics', 'beginner'],
    data: {
      word: 'Book',
      translation: 'ספר',
      context_sentence: 'I read a book every night before bed.',
      context_translation: 'אני קורא ספר כל לילה לפני השינה.',
      correct_answer: 'Book',
      common_mistake: '"Read" is pronounced /riːd/ (present) and /red/ (past) — same spelling, different sound.',
    },
  },
  {
    id: 'v34',
    type: 'vocabulary',
    difficulty: 380,
    skill: 'vocabulary_emotions',
    tags: ['basics', 'beginner'],
    data: {
      word: 'Happy',
      translation: 'שמח / מאושר',
      context_sentence: 'The children are happy because it is their birthday.',
      context_translation: 'הילדים שמחים כי זה יום ההולדת שלהם.',
      correct_answer: 'Happy',
      common_mistake: 'Use "happy" with "be": "I am happy" — not "I have happy".',
    },
  },
  {
    id: 'v35',
    type: 'vocabulary',
    difficulty: 390,
    skill: 'vocabulary_travel',
    tags: ['basics', 'beginner'],
    data: {
      word: 'Friend',
      translation: 'חבר / חברה',
      context_sentence: 'She is my best friend from school.',
      context_translation: 'היא החברה הכי טובה שלי מבית הספר.',
      correct_answer: 'Friend',
      common_mistake: '"Best friend" is one person. For several close friends, say "close friends".',
    },
  },
  // ── Advanced (Tier 9–10) ────────────────────────────────────
  {
    id: 'v36',
    type: 'vocabulary',
    difficulty: 760,
    skill: 'vocabulary_academic',
    tags: ['academic', 'advanced'],
    data: {
      word: 'Ubiquitous',
      translation: 'נמצא בכל מקום / שכיח מאוד',
      context_sentence: 'Smartphones have become ubiquitous in modern society, appearing in nearly every public space.',
      context_translation: 'סמארטפונים הפכו לנפוצים בכל מקום בחברה המודרנית, ומופיעים כמעט בכל מרחב ציבורי.',
      correct_answer: 'Ubiquitous',
      common_mistake: '"Ubiquitous" means present everywhere — stronger than "common" or "popular".',
    },
  },
  {
    id: 'v37',
    type: 'vocabulary',
    difficulty: 810,
    skill: 'vocabulary_academic',
    tags: ['academic', 'advanced'],
    data: {
      word: 'Inscrutable',
      translation: 'בלתי ניתן לפענוח / מסתורי',
      context_sentence: 'The CEO maintained an inscrutable expression throughout the entire press conference.',
      context_translation: 'מנכ"ל החברה שמר על הבעה בלתי ניתנת לפענוח לאורך כל מסיבת העיתונות.',
      correct_answer: 'Inscrutable',
      common_mistake: '"Inscrutable" describes something impossible to read or interpret — often a face or motive.',
    },
  },
  {
    id: 'v38',
    type: 'vocabulary',
    difficulty: 860,
    skill: 'vocabulary_academic',
    tags: ['advanced', 'formal'],
    data: {
      word: 'Ephemeral',
      translation: 'חולף / קצר-ימים',
      context_sentence: 'The beauty of cherry blossoms is ephemeral, lasting only a few weeks each spring.',
      context_translation: 'יופי פריחת הדובדבן חולף, ונמשך רק כמה שבועות בכל אביב.',
      correct_answer: 'Ephemeral',
      common_mistake: '"Ephemeral" means very short-lived — not the same as "temporary" which can last months or years.',
    },
  },
  {
    id: 'v39',
    type: 'vocabulary',
    difficulty: 880,
    skill: 'vocabulary_academic',
    tags: ['academic', 'master'],
    data: {
      word: 'Perspicacious',
      translation: 'חד תבונה / בעל הבנה עמוקה',
      context_sentence: 'The perspicacious analyst predicted the market downturn months before it occurred.',
      context_translation: 'האנליסט החד-תבונה חזה את ירידת השוק חודשים לפני שהיא התרחשה.',
      correct_answer: 'Perspicacious',
      common_mistake: '"Perspicacious" means keenly perceptive — do not confuse with "perspicuous" (clearly expressed).',
    },
  },
  // ── Expanded pool (v40+) ────────────────────────────────────
  {
    id: 'v40',
    type: 'vocabulary',
    difficulty: 400,
    skill: 'vocabulary_travel',
    tags: ['basics', 'beginner'],
    data: {
      word: 'Ticket',
      translation: 'כרטיס',
      context_sentence: 'I bought a train ticket to Haifa this morning.',
      context_translation: 'קניתי כרטיס רכבת לחיפה הבוקר.',
      correct_answer: 'Ticket',
      common_mistake: 'Say "a ticket" (countable) — not "a ticket of train".',
    },
  },
  {
    id: 'v41',
    type: 'vocabulary',
    difficulty: 410,
    skill: 'vocabulary_emotions',
    tags: ['basics', 'beginner'],
    data: {
      word: 'Tired',
      translation: 'עייף / עייפה',
      context_sentence: 'After a long day at work, I feel very tired.',
      context_translation: 'אחרי יום ארוך בעבודה, אני מרגיש מאוד עייף.',
      correct_answer: 'Tired',
      common_mistake: 'Use "tired" with "be": "I am tired" — not "I have tired".',
    },
  },
  {
    id: 'v42',
    type: 'vocabulary',
    difficulty: 420,
    skill: 'vocabulary_travel',
    tags: ['travel', 'beginner'],
    data: {
      word: 'Luggage',
      translation: 'מזוודות / כבודה',
      context_sentence: 'Please keep your luggage with you at all times in the airport.',
      context_translation: 'אנא שמרו על המזוודות שלכם איתכם בכל עת בשדה התעופה.',
      correct_answer: 'Luggage',
      common_mistake: '"Luggage" is uncountable — say "two suitcases", not "two luggages".',
    },
  },
  {
    id: 'v43',
    type: 'vocabulary',
    difficulty: 440,
    skill: 'vocabulary_emotions',
    tags: ['emotions', 'beginner'],
    data: {
      word: 'Grateful',
      translation: 'אסיר תודה',
      context_sentence: 'I am grateful for all the help you gave me during the project.',
      context_translation: 'אני אסיר תודה על כל העזרה שנתת לי במהלך הפרויקט.',
      correct_answer: 'Grateful',
      common_mistake: '"Grateful" is followed by "for" or "to": grateful for something, grateful to someone.',
    },
  },
  {
    id: 'v44',
    type: 'vocabulary',
    difficulty: 455,
    skill: 'vocabulary_business',
    tags: ['work', 'intermediate'],
    data: {
      word: 'Deadline',
      translation: 'מועד אחרון',
      context_sentence: 'We must submit the proposal before the Friday deadline.',
      context_translation: 'עלינו להגיש את ההצעה לפני המועד האחרון ביום שישי.',
      correct_answer: 'Deadline',
      common_mistake: 'Use "meet a deadline" or "miss a deadline" — not "finish a deadline".',
    },
  },
  {
    id: 'v45',
    type: 'vocabulary',
    difficulty: 470,
    skill: 'vocabulary_technology',
    tags: ['technology', 'intermediate'],
    data: {
      word: 'Download',
      translation: 'להוריד (קובץ)',
      context_sentence: 'You can download the app from the official website for free.',
      context_translation: 'אפשר להוריד את האפליקציה מהאתר הרשמי בחינם.',
      correct_answer: 'Download',
      common_mistake: '"Download" = receive a file. "Upload" = send a file. Do not confuse the two.',
    },
  },
  {
    id: 'v46',
    type: 'vocabulary',
    difficulty: 485,
    skill: 'vocabulary_environment',
    tags: ['environment', 'intermediate'],
    data: {
      word: 'Recycle',
      translation: 'למחזר',
      context_sentence: 'Our neighbourhood collects plastic bottles to recycle every Tuesday.',
      context_translation: 'השכונה שלנו אוספת בקבוקי פלסטיק למחזור בכל יום שלישי.',
      correct_answer: 'Recycle',
      common_mistake: '"Recycle" is the verb. The noun is "recycling".',
    },
  },
  {
    id: 'v47',
    type: 'vocabulary',
    difficulty: 495,
    skill: 'vocabulary_idioms',
    tags: ['idioms', 'intermediate'],
    data: {
      word: 'Break the ice',
      translation: 'לשבור את הקרח — להתחיל שיחה בנוחות',
      context_sentence: 'He told a funny story to break the ice at the start of the meeting.',
      context_translation: 'הוא סיפר סיפור מצחיק כדי לשבור את הקרח בתחילת הפגישה.',
      correct_answer: 'Break the ice',
      common_mistake: 'Used for easing social tension at the start — not for literally breaking something frozen.',
    },
  },
  {
    id: 'v48',
    type: 'vocabulary',
    difficulty: 505,
    skill: 'vocabulary_academic',
    tags: ['academic', 'intermediate'],
    data: {
      word: 'Evidence',
      translation: 'ראיה / עדות',
      context_sentence: 'The researcher presented strong evidence to support her conclusion.',
      context_translation: 'החוקרת הציגה ראיות חזקות לתמיכה במסקנתה.',
      correct_answer: 'Evidence',
      common_mistake: '"Evidence" is usually uncountable — say "pieces of evidence", not "evidences".',
    },
  },
  {
    id: 'v49',
    type: 'vocabulary',
    difficulty: 515,
    skill: 'vocabulary_business',
    tags: ['business', 'intermediate'],
    data: {
      word: 'Negotiate',
      translation: 'לנהל משא ומתן',
      context_sentence: 'They managed to negotiate a better salary after the performance review.',
      context_translation: 'הם הצליחו לנהל משא ומתן על משכורת טובה יותר אחרי סקירת הביצועים.',
      correct_answer: 'Negotiate',
      common_mistake: 'You negotiate WITH someone ABOUT something — not "negotiate someone".',
    },
  },
  {
    id: 'v50',
    type: 'vocabulary',
    difficulty: 525,
    skill: 'vocabulary_travel',
    tags: ['travel', 'intermediate'],
    data: {
      word: 'Customs',
      translation: 'מכס',
      context_sentence: 'We had to declare our purchases when we passed through customs.',
      context_translation: 'היינו צריכים להצהיר על הקניות שלנו כשעברנו במכס.',
      correct_answer: 'Customs',
      common_mistake: '"Customs" (מכס) is always plural. Do not confuse with "costume" (תחפושת).',
    },
  },
  {
    id: 'v51',
    type: 'vocabulary',
    difficulty: 535,
    skill: 'vocabulary_emotions',
    tags: ['emotions', 'intermediate'],
    data: {
      word: 'Frustrated',
      translation: 'מתוסכל',
      context_sentence: 'She felt frustrated when the software crashed again during her presentation.',
      context_translation: 'היא הרגישה מתוסכלת כשהתוכנה קרסה שוב במהלך המצגת שלה.',
      correct_answer: 'Frustrated',
      common_mistake: '"Frustrated" describes a feeling caused by blocked progress — stronger than just "annoyed".',
    },
  },
  {
    id: 'v52',
    type: 'vocabulary',
    difficulty: 545,
    skill: 'vocabulary_technology',
    tags: ['technology', 'intermediate'],
    data: {
      word: 'Bandwidth',
      translation: 'רוחב פס',
      context_sentence: 'The video call kept freezing because our internet bandwidth was too low.',
      context_translation: 'שיחת הווידאו נתקעה כי רוחב הפס של האינטרנט שלנו היה נמוך מדי.',
      correct_answer: 'Bandwidth',
      common_mistake: 'In tech, "bandwidth" can also mean mental capacity — "I don\'t have the bandwidth for that."',
    },
  },
  {
    id: 'v53',
    type: 'vocabulary',
    difficulty: 555,
    skill: 'vocabulary_environment',
    tags: ['environment', 'intermediate'],
    data: {
      word: 'Drought',
      translation: 'בצורת',
      context_sentence: 'Farmers struggled after three years of severe drought in the region.',
      context_translation: 'חקלאים התקשו אחרי שלוש שנים של בצורת קשה באזור.',
      correct_answer: 'Drought',
      common_mistake: 'Pronounced /draʊt/ — rhymes with "out". Not "drouth".',
    },
  },
  {
    id: 'v54',
    type: 'vocabulary',
    difficulty: 565,
    skill: 'vocabulary_academic',
    tags: ['academic', 'intermediate'],
    data: {
      word: 'Analyze',
      translation: 'לנתח / לבחון',
      context_sentence: 'Students were asked to analyze the poem and explain its central theme.',
      context_translation: 'התלמידים התבקשו לנתח את השיר ולהסביר את הנושא המרכזי שלו.',
      correct_answer: 'Analyze',
      common_mistake: 'American spelling: "analyze". British spelling: "analyse". Both are correct.',
    },
  },
  {
    id: 'v55',
    type: 'vocabulary',
    difficulty: 575,
    skill: 'vocabulary_idioms',
    tags: ['idioms', 'intermediate'],
    data: {
      word: 'Hit the nail on the head',
      translation: 'פגע במטרה — אמר בדיוק את הדבר הנכון',
      context_sentence: 'When she said the problem was poor communication, she hit the nail on the head.',
      context_translation: 'כשאמרה שהבעיה היא תקשורת לקויה, היא פגעה במטרה.',
      correct_answer: 'Hit the nail on the head',
      common_mistake: 'Means to describe something exactly right — not related to actual nails or hammers.',
    },
  },
  {
    id: 'v56',
    type: 'vocabulary',
    difficulty: 585,
    skill: 'vocabulary_business',
    tags: ['business', 'advanced'],
    data: {
      word: 'Stakeholder',
      translation: 'בעל עניין',
      context_sentence: 'The company invited all stakeholders to review the new sustainability plan.',
      context_translation: 'החברה הזמינה את כל בעלי העניין לעיין בתוכנית הקיימות החדשה.',
      correct_answer: 'Stakeholder',
      common_mistake: 'A stakeholder is anyone affected by a decision — not only shareholders.',
    },
  },
  {
    id: 'v57',
    type: 'vocabulary',
    difficulty: 595,
    skill: 'vocabulary_travel',
    tags: ['travel', 'advanced'],
    data: {
      word: 'Jet lag',
      translation: 'עייפות מטיסה / הפרעת שעות',
      context_sentence: 'After the long flight from New York, jet lag kept me awake until 3 a.m.',
      context_translation: 'אחרי הטיסה הארוכה מניו יורק, עייפות הטיסה השאירה אותי ער עד 3 בלילה.',
      correct_answer: 'Jet lag',
      common_mistake: 'Two words: "jet lag". You "have jet lag" or "suffer from jet lag".',
    },
  },
  {
    id: 'v58',
    type: 'vocabulary',
    difficulty: 605,
    skill: 'vocabulary_emotions',
    tags: ['emotions', 'advanced'],
    data: {
      word: 'Resilient',
      translation: 'גמיש / בעל חוסן',
      context_sentence: 'Despite many setbacks, she remained resilient and rebuilt her career.',
      context_translation: 'למרות מכשולים רבים, היא נשארה בעלת חוסן ובנתה מחדש את הקריירה שלה.',
      correct_answer: 'Resilient',
      common_mistake: '"Resilient" means bouncing back from difficulty — not the same as "stubborn".',
    },
  },
  {
    id: 'v59',
    type: 'vocabulary',
    difficulty: 615,
    skill: 'vocabulary_technology',
    tags: ['technology', 'advanced'],
    data: {
      word: 'Scalability',
      translation: 'יכולת התרחבות',
      context_sentence: 'Scalability was the main reason investors backed the cloud platform.',
      context_translation: 'יכולת ההתרחבות הייתה הסיבה העיקרית שמשקיעים תמכו בפלטפורמת הענן.',
      correct_answer: 'Scalability',
      common_mistake: 'In tech, scalability means handling growth without breaking — not just "size".',
    },
  },
  {
    id: 'v60',
    type: 'vocabulary',
    difficulty: 625,
    skill: 'vocabulary_environment',
    tags: ['environment', 'advanced'],
    data: {
      word: 'Deforestation',
      translation: 'בירוא יערות',
      context_sentence: 'Deforestation in the Amazon threatens thousands of plant and animal species.',
      context_translation: 'בירוא היערות באמזונס מאיים על אלפי מיני צמחים ובעלי חיים.',
      correct_answer: 'Deforestation',
      common_mistake: 'The verb is "deforest". The opposite process is "reforestation".',
    },
  },
  {
    id: 'v61',
    type: 'vocabulary',
    difficulty: 635,
    skill: 'vocabulary_academic',
    tags: ['academic', 'advanced'],
    data: {
      word: 'Plausible',
      translation: 'סביר / אמין',
      context_sentence: 'Her explanation sounded plausible, but we still needed more data to confirm it.',
      context_translation: 'ההסבר שלה נשמע סביר, אבל עדיין היינו צריכים עוד נתונים לאישור.',
      correct_answer: 'Plausible',
      common_mistake: '"Plausible" means believable — not the same as "true" or "proven".',
    },
  },
  {
    id: 'v62',
    type: 'vocabulary',
    difficulty: 645,
    skill: 'vocabulary_idioms',
    tags: ['idioms', 'advanced'],
    data: {
      word: 'Once in a blue moon',
      translation: 'לעתים רחוקות מאוד',
      context_sentence: 'We live in the same city, but we only meet once in a blue moon.',
      context_translation: 'אנחנו גרים באותה עיר, אבל נפגשים רק לעתים רחוקות מאוד.',
      correct_answer: 'Once in a blue moon',
      common_mistake: 'Means very rarely — not literally related to the colour of the moon.',
    },
  },
  {
    id: 'v63',
    type: 'vocabulary',
    difficulty: 700,
    skill: 'vocabulary_business',
    tags: ['business', 'advanced'],
    data: {
      word: 'Due diligence',
      translation: 'בדיקת נאותות',
      context_sentence: 'The investors conducted due diligence before acquiring the startup.',
      context_translation: 'המשקיעים ביצעו בדיקת נאותות לפני רכישת הסטארט-אפ.',
      correct_answer: 'Due diligence',
      common_mistake: 'A formal business term for thorough investigation before a deal — always two words.',
    },
  },
  {
    id: 'v64',
    type: 'vocabulary',
    difficulty: 750,
    skill: 'vocabulary_academic',
    tags: ['academic', 'master'],
    data: {
      word: 'Quintessential',
      translation: 'מושלם / אופייני ביותר',
      context_sentence: 'The small café by the harbour is the quintessential example of Mediterranean charm.',
      context_translation: 'הבית קפה הקטן ליד הנמל הוא הדוגמה האופיינית ביותר לקסם ים-תיכוני.',
      correct_answer: 'Quintessential',
      common_mistake: '"Quintessential" means the purest, most typical example — stronger than "typical".',
    },
  },
  // ── Tier expansion (v65+) — more variety per level ─────────
  // Tier 1 (350–399)
  {
    id: 'v65',
    type: 'vocabulary',
    difficulty: 352,
    skill: 'vocabulary_travel',
    tags: ['basics', 'beginner'],
    data: {
      word: 'Thank you',
      translation: 'תודה',
      context_sentence: 'Thank you for helping me carry the bags.',
      context_translation: 'תודה שעזרת לי לסחוב את התיקים.',
      correct_answer: 'Thank you',
      common_mistake: 'Say "Thank you" — not "Thanks you". "Thanks" alone is informal but correct.',
    },
  },
  {
    id: 'v66',
    type: 'vocabulary',
    difficulty: 365,
    skill: 'vocabulary_travel',
    tags: ['basics', 'beginner'],
    data: {
      word: 'Please',
      translation: 'בבקשה',
      context_sentence: 'Can I sit here, please?',
      context_translation: 'אפשר לשבת כאן, בבקשה?',
      correct_answer: 'Please',
      common_mistake: '"Please" goes at the end of a request in English: "Can I have water, please?"',
    },
  },
  {
    id: 'v67',
    type: 'vocabulary',
    difficulty: 375,
    skill: 'vocabulary_emotions',
    tags: ['basics', 'beginner'],
    data: {
      word: 'Sad',
      translation: 'עצוב / עצובה',
      context_sentence: 'The movie was sad, and many people cried at the end.',
      context_translation: 'הסרט היה עצוב, ואנשים רבים בכו בסוף.',
      correct_answer: 'Sad',
      common_mistake: 'Use "be" with adjectives: "I am sad" — not "I feel sad" only (both work, but beginners often forget "am").',
    },
  },
  {
    id: 'v68',
    type: 'vocabulary',
    difficulty: 385,
    skill: 'vocabulary_travel',
    tags: ['basics', 'beginner', 'food'],
    data: {
      word: 'Food',
      translation: 'אוכל',
      context_sentence: 'The food at this restaurant is fresh and delicious.',
      context_translation: 'האוכל במסעדה הזו טרי וטעים.',
      correct_answer: 'Food',
      common_mistake: '"Food" is uncountable — say "some food" or "a meal", not "a food".',
    },
  },
  {
    id: 'v69',
    type: 'vocabulary',
    difficulty: 395,
    skill: 'vocabulary_travel',
    tags: ['basics', 'beginner'],
    data: {
      word: 'Family',
      translation: 'משפחה',
      context_sentence: 'My family lives in Tel Aviv, but I study in Jerusalem.',
      context_translation: 'משפחתי גרה בתל אביב, אבל אני לומד בירושלים.',
      correct_answer: 'Family',
      common_mistake: '"Family" can be singular (one unit) or plural (members): "My family is" vs "My family are all doctors."',
    },
  },
  {
    id: 'v70',
    type: 'vocabulary',
    difficulty: 398,
    skill: 'vocabulary_emotions',
    tags: ['basics', 'beginner'],
    data: {
      word: 'Excited',
      translation: 'נרגש / נרגשת',
      context_sentence: 'The children are excited about the school trip tomorrow.',
      context_translation: 'הילדים נרגשים מהטיול של בית הספר מחר.',
      correct_answer: 'Excited',
      common_mistake: '"Excited about" something future. Do not confuse with "exciting" (the thing causes excitement).',
    },
  },
  // Tier 2 (400–449)
  {
    id: 'v71',
    type: 'vocabulary',
    difficulty: 402,
    skill: 'vocabulary_travel',
    tags: ['travel', 'beginner'],
    data: {
      word: 'Airport',
      translation: 'שדה תעופה',
      context_sentence: 'We arrived at the airport two hours before our flight.',
      context_translation: 'הגענו לשדה התעופה שעתיים לפני הטיסה.',
      correct_answer: 'Airport',
      common_mistake: 'Use "at the airport" — not "in the airport" (unless inside a specific building).',
    },
  },
  {
    id: 'v72',
    type: 'vocabulary',
    difficulty: 415,
    skill: 'vocabulary_travel',
    tags: ['travel', 'beginner'],
    data: {
      word: 'Passport',
      translation: 'דרכון',
      context_sentence: 'Do not forget your passport when you travel abroad.',
      context_translation: 'אל תשכח את הדרכון כשאתה נוסע לחו"ל.',
      correct_answer: 'Passport',
      common_mistake: '"Passport" is countable: "a passport" or "passports" — not "a passport card" unless it is that document.',
    },
  },
  {
    id: 'v73',
    type: 'vocabulary',
    difficulty: 425,
    skill: 'vocabulary_travel',
    tags: ['basics', 'beginner'],
    data: {
      word: 'Weather',
      translation: 'מזג אוויר',
      context_sentence: 'The weather is sunny today, so let us go to the beach.',
      context_translation: 'מזג האוויר שמשי היום, אז בואו נלך לחוף.',
      correct_answer: 'Weather',
      common_mistake: '"Weather" is uncountable — say "nice weather", not "a nice weather".',
    },
  },
  {
    id: 'v74',
    type: 'vocabulary',
    difficulty: 435,
    skill: 'vocabulary_emotions',
    tags: ['emotions', 'beginner'],
    data: {
      word: 'Nervous',
      translation: 'עצבני / לחוץ',
      context_sentence: 'She felt nervous before her first presentation in English.',
      context_translation: 'היא הרגישה לחוצה לפני המצגת הראשונה שלה באנגלית.',
      correct_answer: 'Nervous',
      common_mistake: '"Nervous" often means anxious before an event — not the same as "angry".',
    },
  },
  {
    id: 'v75',
    type: 'vocabulary',
    difficulty: 442,
    skill: 'vocabulary_travel',
    tags: ['food', 'beginner'],
    data: {
      word: 'Restaurant',
      translation: 'מסעדה',
      context_sentence: 'We found a small restaurant that serves excellent hummus.',
      context_translation: 'מצאנו מסעדה קטנה שמגישה חומוס מצוין.',
      correct_answer: 'Restaurant',
      common_mistake: 'Pronounced /ˈres.tər.ɒnt/ or /ˈres.tə.rɑːnt/ — stress on the first syllable.',
    },
  },
  {
    id: 'v76',
    type: 'vocabulary',
    difficulty: 448,
    skill: 'vocabulary_business',
    tags: ['work', 'beginner'],
    data: {
      word: 'Office',
      translation: 'משרד',
      context_sentence: 'He works in an office near the city centre.',
      context_translation: 'הוא עובד במשרד ליד מרכז העיר.',
      correct_answer: 'Office',
      common_mistake: '"In the office" = at work. "At the office" also common — both are fine.',
    },
  },
  // Tier 3 (450–499)
  {
    id: 'v77',
    type: 'vocabulary',
    difficulty: 452,
    skill: 'vocabulary_emotions',
    tags: ['emotions', 'intermediate'],
    data: {
      word: 'Curious',
      translation: 'סקרן / סקרנית',
      context_sentence: 'The curious student asked why the sky turns red at sunset.',
      context_translation: 'התלמיד הסקרן שאל למה השמיים הופכים לאדומים בשקיעה.',
      correct_answer: 'Curious',
      common_mistake: '"Curious about" something. "Curious" describes wanting to know — not "strange" (that is "curious" as adjective for odd things).',
    },
  },
  {
    id: 'v78',
    type: 'vocabulary',
    difficulty: 463,
    skill: 'vocabulary_emotions',
    tags: ['emotions', 'intermediate'],
    data: {
      word: 'Proud',
      translation: 'גאה',
      context_sentence: 'Her parents were proud when she graduated with honours.',
      context_translation: 'הוריה היו גאים כשסיימה את הלימודים בהצטיינות.',
      correct_answer: 'Proud',
      common_mistake: '"Proud of" someone or something — not "proud from".',
    },
  },
  {
    id: 'v79',
    type: 'vocabulary',
    difficulty: 472,
    skill: 'vocabulary_business',
    tags: ['work', 'intermediate'],
    data: {
      word: 'Schedule',
      translation: 'לוח זמנים / לתזמן',
      context_sentence: 'Let us schedule a meeting for next Tuesday at ten o\'clock.',
      context_translation: 'בואו נתזמן פגישה ליום שלישי הבא בשעה עשר.',
      correct_answer: 'Schedule',
      common_mistake: 'As a verb: "schedule a meeting". As a noun: "on a tight schedule".',
    },
  },
  {
    id: 'v80',
    type: 'vocabulary',
    difficulty: 478,
    skill: 'vocabulary_travel',
    tags: ['travel', 'intermediate'],
    data: {
      word: 'Reservation',
      translation: 'הזמנה (מראש)',
      context_sentence: 'We made a reservation at the hotel for three nights.',
      context_translation: 'עשינו הזמנה במלון לשלוש לילות.',
      correct_answer: 'Reservation',
      common_mistake: '"Make a reservation" — not "do a reservation".',
    },
  },
  {
    id: 'v81',
    type: 'vocabulary',
    difficulty: 486,
    skill: 'vocabulary_technology',
    tags: ['technology', 'intermediate'],
    data: {
      word: 'Password',
      translation: 'סיסמה',
      context_sentence: 'Choose a strong password and do not share it with anyone.',
      context_translation: 'בחר סיסמה חזקה ואל תשתף אותה עם אף אחד.',
      correct_answer: 'Password',
      common_mistake: 'One word: "password". Related: "passcode" (often numeric).',
    },
  },
  {
    id: 'v82',
    type: 'vocabulary',
    difficulty: 494,
    skill: 'vocabulary_environment',
    tags: ['nature', 'intermediate'],
    data: {
      word: 'Pollution',
      translation: 'זיהום',
      context_sentence: 'Air pollution in big cities can cause serious health problems.',
      context_translation: 'זיהום אוויר בערים גדולות עלול לגרום לבעיות בריאות חמורות.',
      correct_answer: 'Pollution',
      common_mistake: '"Pollution" is uncountable. Say "types of pollution", not "pollutions".',
    },
  },
  // Tier 4 (500–549)
  {
    id: 'v83',
    type: 'vocabulary',
    difficulty: 502,
    skill: 'vocabulary_emotions',
    tags: ['emotions', 'intermediate'],
    data: {
      word: 'Relieved',
      translation: 'מרגיש הקלה',
      context_sentence: 'She was relieved when the doctor said the test results were normal.',
      context_translation: 'היא הרגישה הקלה כשהרופא אמר שתוצאות הבדיקה תקינות.',
      correct_answer: 'Relieved',
      common_mistake: '"Relieved" follows something worrying that ended well — stronger than just "happy".',
    },
  },
  {
    id: 'v84',
    type: 'vocabulary',
    difficulty: 512,
    skill: 'vocabulary_business',
    tags: ['business', 'intermediate'],
    data: {
      word: 'Colleague',
      translation: 'עמית / עמיתה לעבודה',
      context_sentence: 'My colleague helped me finish the report before the deadline.',
      context_translation: 'עמיתי לעבודה עזר לי לסיים את הדוח לפני המועד האחרון.',
      correct_answer: 'Colleague',
      common_mistake: '"Colleague" = coworker. "Co-worker" is also correct — same meaning.',
    },
  },
  {
    id: 'v85',
    type: 'vocabulary',
    difficulty: 522,
    skill: 'vocabulary_travel',
    tags: ['travel', 'intermediate'],
    data: {
      word: 'Destination',
      translation: 'יעד / מקום יעד',
      context_sentence: 'Barcelona was our final destination on a two-week tour of Spain.',
      context_translation: 'ברצלונה הייתה היעד הסופי שלנו בטיול של שבועיים בספרד.',
      correct_answer: 'Destination',
      common_mistake: '"Destination" is where you are going — not where you start from.',
    },
  },
  {
    id: 'v86',
    type: 'vocabulary',
    difficulty: 532,
    skill: 'vocabulary_technology',
    tags: ['technology', 'intermediate'],
    data: {
      word: 'Software',
      translation: 'תוכנה',
      context_sentence: 'The company updated its software to fix several security bugs.',
      context_translation: 'החברה עדכנה את התוכנה שלה כדי לתקן מספר באגים באבטחה.',
      correct_answer: 'Software',
      common_mistake: '"Software" is uncountable — say "a software program" or "applications", not "a software".',
    },
  },
  {
    id: 'v87',
    type: 'vocabulary',
    difficulty: 538,
    skill: 'vocabulary_idioms',
    tags: ['idioms', 'intermediate'],
    data: {
      word: 'Piece of cake',
      translation: 'קל מאוד (כמו לחתוך עוגה)',
      context_sentence: 'The grammar exercise was a piece of cake for her after months of practice.',
      context_translation: 'תרגיל הדקדוק היה קל מאוד עבורה אחרי חודשים של תרגול.',
      correct_answer: 'Piece of cake',
      common_mistake: 'Means "very easy" — nothing to do with actual cake or food.',
    },
  },
  {
    id: 'v88',
    type: 'vocabulary',
    difficulty: 547,
    skill: 'vocabulary_academic',
    tags: ['academic', 'intermediate'],
    data: {
      word: 'Conclusion',
      translation: 'מסקנה / סיכום',
      context_sentence: 'In conclusion, the study shows that sleep improves memory.',
      context_translation: 'לסיכום, המחקר מראה ששינה משפרת זיכרון.',
      correct_answer: 'Conclusion',
      common_mistake: 'In writing: "In conclusion" starts the final paragraph — not "To conclusion".',
    },
  },
  // Tier 5 (550–599)
  {
    id: 'v89',
    type: 'vocabulary',
    difficulty: 552,
    skill: 'vocabulary_emotions',
    tags: ['emotions', 'intermediate'],
    data: {
      word: 'Nostalgic',
      translation: 'נוסטלגי',
      context_sentence: 'Listening to old songs made him feel nostalgic for his childhood summers.',
      context_translation: 'האזנה לשירים ישנים גרמה לו להרגיש נוסטלגיה לקיץ ילדותו.',
      correct_answer: 'Nostalgic',
      common_mistake: '"Nostalgic" = longing for the past. The noun is "nostalgia".',
    },
  },
  {
    id: 'v90',
    type: 'vocabulary',
    difficulty: 562,
    skill: 'vocabulary_business',
    tags: ['business', 'intermediate'],
    data: {
      word: 'Feasible',
      translation: 'בר-ביצוע / אפשרי',
      context_sentence: 'The team discussed whether the project timeline was feasible with current resources.',
      context_translation: 'הצוות דן האם לוח הזמנים של הפרויקט בר-ביצוע עם המשאבים הנוכחיים.',
      correct_answer: 'Feasible',
      common_mistake: '"Feasible" = can be done practically — not the same as "possible" (which is broader).',
    },
  },
  {
    id: 'v91',
    type: 'vocabulary',
    difficulty: 572,
    skill: 'vocabulary_travel',
    tags: ['travel', 'intermediate'],
    data: {
      word: 'Expedition',
      translation: 'משלחת / מסע מחקר',
      context_sentence: 'The expedition to Antarctica lasted six months and required special equipment.',
      context_translation: 'המשלחת לאנטארקטיקה נמשכה שישה חודשים ודרשה ציוד מיוחד.',
      correct_answer: 'Expedition',
      common_mistake: 'An expedition is organised for exploration or research — more formal than "trip".',
    },
  },
  {
    id: 'v92',
    type: 'vocabulary',
    difficulty: 582,
    skill: 'vocabulary_technology',
    tags: ['technology', 'intermediate'],
    data: {
      word: 'Backup',
      translation: 'גיבוי',
      context_sentence: 'Always create a backup of important files before updating your computer.',
      context_translation: 'תמיד צור גיבוי של קבצים חשובים לפני עדכון המחשב.',
      correct_answer: 'Backup',
      common_mistake: 'Noun: "a backup". Verb: "back up" (two words): "Back up your data."',
    },
  },
  {
    id: 'v93',
    type: 'vocabulary',
    difficulty: 588,
    skill: 'vocabulary_environment',
    tags: ['environment', 'intermediate'],
    data: {
      word: 'Renewable',
      translation: 'מתחדש (אנרגיה)',
      context_sentence: 'Many countries invest in renewable energy such as solar and wind power.',
      context_translation: 'מדינות רבות משקיעות באנרגיה מתחדשת כמו אנרגיה סולארית ואנרגיית רוח.',
      correct_answer: 'Renewable',
      common_mistake: '"Renewable" describes energy sources that replenish — solar, wind, hydro.',
    },
  },
  {
    id: 'v94',
    type: 'vocabulary',
    difficulty: 597,
    skill: 'vocabulary_idioms',
    tags: ['idioms', 'intermediate'],
    data: {
      word: 'Under the weather',
      translation: 'לא מרגיש טוב / קצת חולה',
      context_sentence: 'I will stay home today because I am feeling a bit under the weather.',
      context_translation: 'אני אשאר בבית היום כי אני מרגיש קצת לא טוב.',
      correct_answer: 'Under the weather',
      common_mistake: 'Mild illness only — not for serious medical conditions.',
    },
  },
  // Tier 6 (600–649)
  {
    id: 'v95',
    type: 'vocabulary',
    difficulty: 602,
    skill: 'vocabulary_emotions',
    tags: ['emotions', 'advanced'],
    data: {
      word: 'Compassionate',
      translation: 'אכפתי / רחום',
      context_sentence: 'The compassionate nurse listened patiently to every patient\'s concerns.',
      context_translation: 'האחות האכפתית הקשיבה בסבלנות לדאגות של כל מטופל.',
      correct_answer: 'Compassionate',
      common_mistake: '"Compassionate" shows deep care for others\' suffering — stronger than "kind".',
    },
  },
  {
    id: 'v96',
    type: 'vocabulary',
    difficulty: 612,
    skill: 'vocabulary_business',
    tags: ['business', 'advanced'],
    data: {
      word: 'Synergy',
      translation: 'סינרגיה / תועלת משולבת',
      context_sentence: 'The merger created synergy by combining marketing expertise with technical skills.',
      context_translation: 'המיזוג יצר סינרגיה על ידי שילוב מומחיות שיווקית עם כישורים טכניים.',
      correct_answer: 'Synergy',
      common_mistake: 'Business buzzword: combined effect greater than separate parts.',
    },
  },
  {
    id: 'v97',
    type: 'vocabulary',
    difficulty: 622,
    skill: 'vocabulary_travel',
    tags: ['travel', 'advanced'],
    data: {
      word: 'Backpacking',
      translation: 'טיול עם תרמיל',
      context_sentence: 'They spent a month backpacking through Southeast Asia on a tight budget.',
      context_translation: 'הם בילו חודש בטיול עם תרמיל בדרום-מזרח אסיה בתקציב מוגבל.',
      correct_answer: 'Backpacking',
      common_mistake: '"Go backpacking" — travel carrying everything in a backpack, often low-cost.',
    },
  },
  {
    id: 'v98',
    type: 'vocabulary',
    difficulty: 628,
    skill: 'vocabulary_technology',
    tags: ['technology', 'advanced'],
    data: {
      word: 'Malware',
      translation: 'תוכנה זדונית',
      context_sentence: 'Never open email attachments from unknown senders — they may contain malware.',
      context_translation: 'לעולם אל תפתח קבצים מצורפים מאימיילים של שולחים לא מוכרים — הם עלולים להכיל תוכנה זדונית.',
      correct_answer: 'Malware',
      common_mistake: 'Short for "malicious software" — includes viruses, ransomware, spyware.',
    },
  },
  {
    id: 'v99',
    type: 'vocabulary',
    difficulty: 638,
    skill: 'vocabulary_environment',
    tags: ['environment', 'advanced'],
    data: {
      word: 'Carbon footprint',
      translation: 'טביעת רגל פחמנית',
      context_sentence: 'Taking the train instead of flying reduces your carbon footprint significantly.',
      context_translation: 'נסיעה ברכבת במקום בטיסה מפחיתה משמעותית את טביעת הרגל הפחמנית שלך.',
      correct_answer: 'Carbon footprint',
      common_mistake: 'Measures total greenhouse gas emissions caused by a person or activity.',
    },
  },
  {
    id: 'v100',
    type: 'vocabulary',
    difficulty: 648,
    skill: 'vocabulary_academic',
    tags: ['academic', 'advanced'],
    data: {
      word: 'Methodology',
      translation: 'מתודולוגיה / שיטת מחקר',
      context_sentence: 'The professor explained the methodology used to collect and analyse the survey data.',
      context_translation: 'הפרופסור הסביר את המתודולוגיה ששימשה לאיסוף ולניתוח נתוני הסקר.',
      correct_answer: 'Methodology',
      common_mistake: '"Methodology" = systematic approach — broader than a single "method".',
    },
  },
  // Tier 7 (650–699)
  {
    id: 'v101',
    type: 'vocabulary',
    difficulty: 655,
    skill: 'vocabulary_emotions',
    tags: ['emotions', 'advanced'],
    data: {
      word: 'Contemplative',
      translation: 'מהורהר / שקט ומחשב',
      context_sentence: 'He sat in a contemplative silence, considering every option before deciding.',
      context_translation: 'הוא ישב בשקט מהורהר, שוקל כל אפשרות לפני ההחלטה.',
      correct_answer: 'Contemplative',
      common_mistake: '"Contemplative" = deep thoughtful reflection — not the same as "confused".',
    },
  },
  {
    id: 'v102',
    type: 'vocabulary',
    difficulty: 665,
    skill: 'vocabulary_business',
    tags: ['business', 'advanced'],
    data: {
      word: 'Arbitrage',
      translation: 'רווח מהפרשי מחיר בין שווקים',
      context_sentence: 'Traders used arbitrage to profit from small price differences between two markets.',
      context_translation: 'סוחרים ניצלו פערי מחיר קטנים בין שני שווקים כדי להרוויח.',
      correct_answer: 'Arbitrage',
      common_mistake: 'Finance term: buying low in one market and selling high in another simultaneously.',
    },
  },
  {
    id: 'v103',
    type: 'vocabulary',
    difficulty: 675,
    skill: 'vocabulary_travel',
    tags: ['travel', 'advanced'],
    data: {
      word: 'Visa waiver',
      translation: 'פטור מוויזה',
      context_sentence: 'Israeli citizens can visit many European countries under a visa waiver programme.',
      context_translation: 'אזרחים ישראלים יכולים לבקר במדינות רבות באירופה במסגרת תוכנית פטור מוויזה.',
      correct_answer: 'Visa waiver',
      common_mistake: 'A visa waiver lets you enter without applying for a visa — rules vary by nationality.',
    },
  },
  {
    id: 'v104',
    type: 'vocabulary',
    difficulty: 685,
    skill: 'vocabulary_technology',
    tags: ['technology', 'advanced'],
    data: {
      word: 'Blockchain',
      translation: 'בלוקצ\'יין',
      context_sentence: 'Blockchain technology creates a secure, decentralised record of transactions.',
      context_translation: 'טכנולוגיית הבלוקצ\'יין יוצרת רשומה מאובטחת ומבוזרת של עסקאות.',
      correct_answer: 'Blockchain',
      common_mistake: 'One word. Not the same as "Bitcoin" — blockchain is the underlying technology.',
    },
  },
  {
    id: 'v105',
    type: 'vocabulary',
    difficulty: 692,
    skill: 'vocabulary_environment',
    tags: ['environment', 'advanced'],
    data: {
      word: 'Greenhouse effect',
      translation: 'אפקט החממה',
      context_sentence: 'The greenhouse effect traps heat in the atmosphere, warming the planet.',
      context_translation: 'אפקט החממה לוכד חום באטמוספירה ומחמם את כדור הארץ.',
      correct_answer: 'Greenhouse effect',
      common_mistake: 'Natural process amplified by human emissions — not the same as "global warming" alone.',
    },
  },
  {
    id: 'v106',
    type: 'vocabulary',
    difficulty: 698,
    skill: 'vocabulary_idioms',
    tags: ['idioms', 'advanced'],
    data: {
      word: 'Blessing in disguise',
      translation: 'ברכה במסווה',
      context_sentence: 'Losing that job turned out to be a blessing in disguise — she found a much better role.',
      context_translation: 'אובדן העבודה ההיא התברר כברכה במסווה — היא מצאה תפקיד הרבה יותר טוב.',
      correct_answer: 'Blessing in disguise',
      common_mistake: 'Something bad that leads to something good — hindsight reveals the benefit.',
    },
  },
  // Tier 8 (700–749)
  {
    id: 'v107',
    type: 'vocabulary',
    difficulty: 705,
    skill: 'vocabulary_emotions',
    tags: ['emotions', 'advanced'],
    data: {
      word: 'Eloquent',
      translation: 'רהוט / בעל יכולת ביטוי',
      context_sentence: 'The eloquent speaker moved the audience with clear, powerful language.',
      context_translation: 'הדובר הרהוט ריגש את הקהל בשפה ברורה ועוצמתית.',
      correct_answer: 'Eloquent',
      common_mistake: '"Eloquent" = fluent and persuasive speech — not just "talkative".',
    },
  },
  {
    id: 'v108',
    type: 'vocabulary',
    difficulty: 715,
    skill: 'vocabulary_business',
    tags: ['business', 'advanced'],
    data: {
      word: 'Procurement',
      translation: 'רכש / תהליך רכישה',
      context_sentence: 'The procurement department negotiated contracts with all major suppliers.',
      context_translation: 'מחלקת הרכש ניהלה משא ומתן על חוזים עם כל הספקים הגדולים.',
      correct_answer: 'Procurement',
      common_mistake: 'Formal term for obtaining goods/services — more specific than "buying".',
    },
  },
  {
    id: 'v109',
    type: 'vocabulary',
    difficulty: 725,
    skill: 'vocabulary_travel',
    tags: ['travel', 'advanced'],
    data: {
      word: 'Wanderlust',
      translation: 'געגוע לנסיעות / תשוקה לטייל',
      context_sentence: 'Her wanderlust led her to visit over thirty countries before she turned thirty.',
      context_translation: 'געגועיה לנסיעות הובילו אותה לבקר ביותר משלושים מדינות לפני שמלאו לה שלושים.',
      correct_answer: 'Wanderlust',
      common_mistake: 'German-origin noun — a strong desire to travel and explore the world.',
    },
  },
  {
    id: 'v110',
    type: 'vocabulary',
    difficulty: 735,
    skill: 'vocabulary_technology',
    tags: ['technology', 'advanced'],
    data: {
      word: 'Machine learning',
      translation: 'למידת מכונה',
      context_sentence: 'Machine learning algorithms improve as they process more training data.',
      context_translation: 'אלגוריתמי למידת מכונה משתפרים ככל שהם מעבדים יותר נתוני אימון.',
      correct_answer: 'Machine learning',
      common_mistake: 'Subset of AI — systems learn patterns from data rather than explicit rules.',
    },
  },
  {
    id: 'v111',
    type: 'vocabulary',
    difficulty: 742,
    skill: 'vocabulary_environment',
    tags: ['environment', 'advanced'],
    data: {
      word: 'Conservation',
      translation: 'שימור (טבע)',
      context_sentence: 'Wildlife conservation efforts have helped several endangered species recover.',
      context_translation: 'מאמצי שימור החיות עזרו למספר מינים בסכנת הכחדה להתאושש.',
      correct_answer: 'Conservation',
      common_mistake: '"Conservation" = protecting nature. "Conversation" = talk — do not confuse spelling.',
    },
  },
  {
    id: 'v112',
    type: 'vocabulary',
    difficulty: 748,
    skill: 'vocabulary_academic',
    tags: ['academic', 'advanced'],
    data: {
      word: 'Paradigm',
      translation: 'פרדיגמה / מודל מחשבתי',
      context_sentence: 'Einstein\'s theory caused a paradigm shift in how scientists understood physics.',
      context_translation: 'תורתו של איינשטיין גרמה לשינוי פרדיגמה בדרך שבה מדענים הבינו פיזיקה.',
      correct_answer: 'Paradigm',
      common_mistake: 'A paradigm is a framework of assumptions — "paradigm shift" = fundamental change in thinking.',
    },
  },
  // Tier 9 (750–799)
  {
    id: 'v113',
    type: 'vocabulary',
    difficulty: 755,
    skill: 'vocabulary_emotions',
    tags: ['emotions', 'advanced'],
    data: {
      word: 'Wistful',
      translation: 'געגוע / עם ניחוח של עצב',
      context_sentence: 'She gave a wistful smile as she remembered her grandmother\'s kitchen.',
      context_translation: 'היא חייכה בגעגוע כשזכרה את המטבח של סבתה.',
      correct_answer: 'Wistful',
      common_mistake: '"Wistful" = sad longing, often for something past — gentler than "depressed".',
    },
  },
  {
    id: 'v114',
    type: 'vocabulary',
    difficulty: 765,
    skill: 'vocabulary_business',
    tags: ['business', 'advanced'],
    data: {
      word: 'Restructuring',
      translation: 'ארגון מחדש',
      context_sentence: 'The company announced a restructuring that would eliminate two management layers.',
      context_translation: 'החברה הודיעה על ארגון מחדש שיפחית שני שכבות ניהול.',
      correct_answer: 'Restructuring',
      common_mistake: 'Organisational change — often involves layoffs, mergers, or new departments.',
    },
  },
  {
    id: 'v115',
    type: 'vocabulary',
    difficulty: 775,
    skill: 'vocabulary_travel',
    tags: ['travel', 'advanced'],
    data: {
      word: 'Off the beaten path',
      translation: 'מחוץ למסלול התיירים',
      context_sentence: 'They preferred villages off the beaten path to crowded tourist attractions.',
      context_translation: 'הם העדיפו כפרים מחוץ למסלול התיירים על פני אטרקציות תיירותיות עמוסות.',
      correct_answer: 'Off the beaten path',
      common_mistake: 'Describes remote, less-visited places — the opposite of mainstream tourism.',
    },
  },
  {
    id: 'v116',
    type: 'vocabulary',
    difficulty: 785,
    skill: 'vocabulary_technology',
    tags: ['technology', 'advanced'],
    data: {
      word: 'Neural network',
      translation: 'רשת נוירונים',
      context_sentence: 'The neural network learned to recognise faces after training on millions of images.',
      context_translation: 'רשת הנוירונים למדה לזהות פנים אחרי אימון על מיליוני תמונות.',
      correct_answer: 'Neural network',
      common_mistake: 'Inspired by brain structure — core technology behind many AI applications.',
    },
  },
  {
    id: 'v117',
    type: 'vocabulary',
    difficulty: 792,
    skill: 'vocabulary_environment',
    tags: ['environment', 'advanced'],
    data: {
      word: 'Anthropogenic',
      translation: 'מקורו בפעילות אנושית',
      context_sentence: 'Scientists linked the rise in sea levels to anthropogenic climate change.',
      context_translation: 'מדענים קשרו את עליית מפלי הים לשינויי אקלים מקורם בפעילות אנושית.',
      correct_answer: 'Anthropogenic',
      common_mistake: 'Formal/academic: caused by human activity — opposite of "natural" causes.',
    },
  },
  {
    id: 'v118',
    type: 'vocabulary',
    difficulty: 798,
    skill: 'vocabulary_idioms',
    tags: ['idioms', 'advanced'],
    data: {
      word: 'Cut to the chase',
      translation: 'לעבור לעניין / ישר לתכל\'ס',
      context_sentence: 'Let us cut to the chase — we need a decision by Friday.',
      context_translation: 'בואו נעבור לעניין — אנחנו צריכים החלטה עד יום שישי.',
      correct_answer: 'Cut to the chase',
      common_mistake: 'From film editing — skip unnecessary details and get to the main point.',
    },
  },
  // Tier 10 (800–899)
  {
    id: 'v119',
    type: 'vocabulary',
    difficulty: 805,
    skill: 'vocabulary_academic',
    tags: ['academic', 'master'],
    data: {
      word: 'Meticulous',
      translation: 'קפדני / מדויק בפרטים',
      context_sentence: 'The meticulous editor checked every footnote and comma in the manuscript.',
      context_translation: 'העורך הקפדני בדק כל הערת שוליים ופסיק בכתב היד.',
      correct_answer: 'Meticulous',
      common_mistake: '"Meticulous" = extreme attention to detail — stronger than "careful".',
    },
  },
  {
    id: 'v120',
    type: 'vocabulary',
    difficulty: 815,
    skill: 'vocabulary_business',
    tags: ['business', 'master'],
    data: {
      word: 'Proprietary',
      translation: 'קנייני / בבעלות פרטית',
      context_sentence: 'The formula is proprietary, and the company refuses to disclose its ingredients.',
      context_translation: 'הנוסחה קניינית, והחברה מסרבת לחשוף את הרכיבים שלה.',
      correct_answer: 'Proprietary',
      common_mistake: 'Owned exclusively by one company — often protected by trade secrets or patents.',
    },
  },
  {
    id: 'v121',
    type: 'vocabulary',
    difficulty: 825,
    skill: 'vocabulary_travel',
    tags: ['travel', 'master'],
    data: {
      word: 'Peregrination',
      translation: 'מסע ארוך / wandering',
      context_sentence: 'His peregrination across three continents took nearly a decade to complete.',
      context_translation: 'מסעו הארוך בשלוש יבשות נמשך כמעט עשור.',
      correct_answer: 'Peregrination',
      common_mistake: 'Literary/formal word for an extended journey — rarely used in casual speech.',
    },
  },
  {
    id: 'v122',
    type: 'vocabulary',
    difficulty: 845,
    skill: 'vocabulary_technology',
    tags: ['technology', 'master'],
    data: {
      word: 'Quantum computing',
      translation: 'מחשוב קוונטי',
      context_sentence: 'Quantum computing could solve certain problems far faster than classical computers.',
      context_translation: 'מחשוב קוונטי עלול לפתור בעיות מסוימות הרבה יותר מהר ממחשבים קלאסיים.',
      correct_answer: 'Quantum computing',
      common_mistake: 'Uses quantum mechanics principles — still emerging, not yet mainstream.',
    },
  },
  {
    id: 'v123',
    type: 'vocabulary',
    difficulty: 865,
    skill: 'vocabulary_environment',
    tags: ['environment', 'master'],
    data: {
      word: 'Anthropocene',
      translation: 'עידן האדם (Anthropocene)',
      context_sentence: 'Geologists debate whether we have entered the Anthropocene, an era shaped by human impact.',
      context_translation: 'גאולוגים מתווכחים האם נכנסנו לעידן האדם, עידן שמעוצב על ידי השפעה אנושית.',
      correct_answer: 'Anthropocene',
      common_mistake: 'Proposed geological epoch — marks significant human alteration of Earth systems.',
    },
  },
  {
    id: 'v124',
    type: 'vocabulary',
    difficulty: 885,
    skill: 'vocabulary_academic',
    tags: ['academic', 'master'],
    data: {
      word: 'Esoteric',
      translation: 'אזוטרי / מיועד למעטים',
      context_sentence: 'The lecture covered esoteric topics in medieval philosophy that few students understood.',
      context_translation: 'ההרצאה עסקה בנושאים אזוטריים בפילוסופיה של ימי הביניים שמעט תלמידים הבינו.',
      correct_answer: 'Esoteric',
      common_mistake: 'Known or understood by only a small group — opposite of "mainstream" or "accessible".',
    },
  },
]
