import type { ContentItem } from '@/types/game'

export const VOCABULARY_ITEMS: ContentItem[] = [
  // ── Emotions ──────────────────────────────────────────────
  {
    id: 'v1',
    type: 'vocabulary',
    difficulty: 420,
    skill: 'vocabulary_emotions',
    tags: ['emotions', 'adjectives', 'beginner'],
    data: {
      word: 'Melancholy',
      translation: 'עצבות עמוקה / נוסטלגיה עצובה',
      context_sentence: 'She felt a deep melancholy as she looked at old family photographs.',
      context_translation: 'היא חשה עצבות עמוקה כשהסתכלה על תמונות ישנות של המשפחה.',
      correct_answer: 'Melancholy',
      common_mistake: 'Do not confuse with "sadness" — melancholy implies a reflective, lingering quality.',
    },
  },
  {
    id: 'v2',
    type: 'vocabulary',
    difficulty: 460,
    skill: 'vocabulary_emotions',
    tags: ['emotions', 'adjectives'],
    data: {
      word: 'Apprehensive',
      translation: 'חרד / מודאג לקראת משהו עתידי',
      context_sentence: 'He was apprehensive about the job interview, barely sleeping the night before.',
      context_translation: 'הוא היה חרד לקראת ראיון העבודה וכמעט לא ישן בלילה שלפני.',
      correct_answer: 'Apprehensive',
      common_mistake: '"Apprehensive" is about anticipating something bad — not the same as generally anxious.',
    },
  },
  {
    id: 'v3',
    type: 'vocabulary',
    difficulty: 510,
    skill: 'vocabulary_emotions',
    tags: ['emotions', 'adjectives', 'intermediate'],
    data: {
      word: 'Exhilarated',
      translation: 'מלא התלהבות / אקסטזה של שמחה',
      context_sentence: 'The crowd was exhilarated when the team scored the winning goal in extra time.',
      context_translation: 'הקהל היה מלא התלהבות כשהקבוצה כבשה שער הניצחון בהארכה.',
      correct_answer: 'Exhilarated',
      common_mistake: 'Stronger than "excited" — implies a rush of energy and elation.',
    },
  },
  {
    id: 'v4',
    type: 'vocabulary',
    difficulty: 560,
    skill: 'vocabulary_emotions',
    tags: ['emotions', 'adjectives'],
    data: {
      word: 'Ambivalent',
      translation: 'אמביוולנטי / בעל רגשות מעורבים',
      context_sentence: 'She felt ambivalent about moving abroad — excited for the opportunity but sad to leave her family.',
      context_translation: 'היא חשה בעלת רגשות מעורבים לגבי המעבר לחו"ל — נרגשת מהאפשרות אך עצובה לעזוב את משפחתה.',
      correct_answer: 'Ambivalent',
      common_mistake: 'Does not mean "indifferent" — it means having BOTH positive and negative feelings simultaneously.',
    },
  },
  // ── Business ──────────────────────────────────────────────
  {
    id: 'v5',
    type: 'vocabulary',
    difficulty: 480,
    skill: 'vocabulary_business',
    tags: ['work', 'nouns', 'intermediate'],
    data: {
      word: 'Diligent',
      translation: 'חרוץ / שקדן',
      context_sentence: 'The diligent student reviewed her notes every evening without fail.',
      context_translation: 'הסטודנטית החרוצה עברה על הערותיה כל ערב ללא יוצא מן הכלל.',
      correct_answer: 'Diligent',
      common_mistake: 'Diligent emphasises careful, persistent effort — not just being "hard-working".',
    },
  },
  {
    id: 'v6',
    type: 'vocabulary',
    difficulty: 520,
    skill: 'vocabulary_business',
    tags: ['business', 'nouns'],
    data: {
      word: 'Leverage',
      translation: 'מינוף / להשתמש ביתרון',
      context_sentence: 'The startup decided to leverage its social media following to attract new investors.',
      context_translation: 'הסטארט-אפ החליט למנף את כמות העוקבים שלו ברשתות החברתיות כדי למשוך משקיעים חדשים.',
      correct_answer: 'Leverage',
      common_mistake: 'As a verb: "to leverage" means to use something to maximum advantage.',
    },
  },
  {
    id: 'v7',
    type: 'vocabulary',
    difficulty: 570,
    skill: 'vocabulary_business',
    tags: ['business', 'adjectives'],
    data: {
      word: 'Stringent',
      translation: 'מחמיר / נוקשה (לגבי כללים)',
      context_sentence: 'The new data privacy law introduced stringent requirements for all online businesses.',
      context_translation: 'חוק פרטיות הנתונים החדש הכניס דרישות מחמירות לכל עסקי האינטרנט.',
      correct_answer: 'Stringent',
      common_mistake: 'Describes rules/conditions that are strict and difficult to satisfy.',
    },
  },
  {
    id: 'v8',
    type: 'vocabulary',
    difficulty: 620,
    skill: 'vocabulary_business',
    tags: ['business', 'verbs', 'advanced'],
    data: {
      word: 'Mitigate',
      translation: 'להפחית / למתן (סיכון או נזק)',
      context_sentence: 'The company implemented new safeguards to mitigate the risk of a data breach.',
      context_translation: 'החברה יישמה אמצעי הגנה חדשים כדי להפחית את הסיכון לפרצת נתונים.',
      correct_answer: 'Mitigate',
      common_mistake: '"Mitigate" means to lessen severity — do not confuse with "eliminate".',
    },
  },
  // ── Travel ────────────────────────────────────────────────
  {
    id: 'v9',
    type: 'vocabulary',
    difficulty: 430,
    skill: 'vocabulary_travel',
    tags: ['travel', 'nouns', 'beginner'],
    data: {
      word: 'Itinerary',
      translation: 'מסלול / לוח זמנים של טיול',
      context_sentence: "The travel agent sent a detailed itinerary listing every hotel, flight, and excursion.",
      context_translation: 'סוכן הנסיעות שלח מסלול מפורט המפרט כל מלון, טיסה וטיול.',
      correct_answer: 'Itinerary',
      common_mistake: 'Pronounced /ɪˈtɪn.ər.ər.i/ — five syllables. Often misspelled.',
    },
  },
  {
    id: 'v10',
    type: 'vocabulary',
    difficulty: 490,
    skill: 'vocabulary_travel',
    tags: ['travel', 'adjectives'],
    data: {
      word: 'Scenic',
      translation: 'ציורי / בעל נוף יפה',
      context_sentence: 'They chose the scenic coastal route even though it added two hours to the drive.',
      context_translation: 'הם בחרו במסלול החוף הציורי למרות שהוסיף שעתיים לנסיעה.',
      correct_answer: 'Scenic',
      common_mistake: '"Scenic" relates to beautiful natural or landscape views — not decorations inside a place.',
    },
  },
  {
    id: 'v11',
    type: 'vocabulary',
    difficulty: 540,
    skill: 'vocabulary_travel',
    tags: ['travel', 'nouns'],
    data: {
      word: 'Layover',
      translation: 'עצירת ביניים (בשדה תעופה)',
      context_sentence: 'Their flight to Tokyo included a six-hour layover in Dubai.',
      context_translation: 'הטיסה שלהם לטוקיו כללה עצירת ביניים של שש שעות בדובאי.',
      correct_answer: 'Layover',
      common_mistake: 'In British English this is often called a "stopover". Both are correct.',
    },
  },
  // ── Technology ────────────────────────────────────────────
  {
    id: 'v12',
    type: 'vocabulary',
    difficulty: 500,
    skill: 'vocabulary_technology',
    tags: ['technology', 'nouns'],
    data: {
      word: 'Algorithm',
      translation: 'אלגוריתם / רצף הוראות לפתרון בעיה',
      context_sentence: 'The streaming platform uses an algorithm to recommend shows based on your viewing history.',
      context_translation: 'פלטפורמת הסטרימינג משתמשת באלגוריתם להמלצת תוכניות על בסיס היסטוריית הצפייה שלך.',
      correct_answer: 'Algorithm',
      common_mistake: 'Often mispronounced: /ˈæl.ɡə.rɪ.ðəm/ — stress on the first syllable.',
    },
  },
  {
    id: 'v13',
    type: 'vocabulary',
    difficulty: 550,
    skill: 'vocabulary_technology',
    tags: ['technology', 'nouns', 'intermediate'],
    data: {
      word: 'Encryption',
      translation: 'הצפנה',
      context_sentence: 'End-to-end encryption ensures that only the sender and recipient can read the messages.',
      context_translation: 'הצפנה מקצה לקצה מבטיחה שרק השולח והנמען יכולים לקרוא את ההודעות.',
      correct_answer: 'Encryption',
      common_mistake: 'Do not confuse "encrypt" (verb) with "encode" — encryption specifically implies security.',
    },
  },
  {
    id: 'v14',
    type: 'vocabulary',
    difficulty: 640,
    skill: 'vocabulary_technology',
    tags: ['technology', 'adjectives', 'advanced'],
    data: {
      word: 'Obsolete',
      translation: 'מיושן / שאינו בשימוש עוד',
      context_sentence: 'With the rapid pace of innovation, many skills can become obsolete within a decade.',
      context_translation: 'עם קצב החדשנות המהיר, מיומנויות רבות יכולות להפוך למיושנות תוך עשור.',
      correct_answer: 'Obsolete',
      common_mistake: '"Obsolete" means no longer in use, not just old — something old but still used is "dated" or "vintage".',
    },
  },
  // ── Environment ───────────────────────────────────────────
  {
    id: 'v15',
    type: 'vocabulary',
    difficulty: 530,
    skill: 'vocabulary_environment',
    tags: ['environment', 'nouns'],
    data: {
      word: 'Biodiversity',
      translation: 'מגוון ביולוגי',
      context_sentence: 'Tropical rainforests contain the greatest biodiversity of any ecosystem on Earth.',
      context_translation: 'יערות הגשם הטרופיים מכילים את המגוון הביולוגי הגדול ביותר מכל מערכת אקולוגית בכדור הארץ.',
      correct_answer: 'Biodiversity',
      common_mistake: 'Refers to variety of species, not just quantity. A rainforest and a fish farm may both have many organisms but only one has true biodiversity.',
    },
  },
  {
    id: 'v16',
    type: 'vocabulary',
    difficulty: 580,
    skill: 'vocabulary_environment',
    tags: ['environment', 'adjectives'],
    data: {
      word: 'Sustainable',
      translation: 'בר-קיימא',
      context_sentence: 'The local government launched a sustainable transport initiative to reduce carbon emissions.',
      context_translation: 'הממשל המקומי השיק יוזמת תחבורה בת-קיימא להפחתת פליטות פחמן.',
      correct_answer: 'Sustainable',
      common_mistake: '"Sustainable" means able to be maintained long-term without depleting resources — stronger than just "eco-friendly".',
    },
  },
  // ── Academic ──────────────────────────────────────────────
  {
    id: 'v17',
    type: 'vocabulary',
    difficulty: 590,
    skill: 'vocabulary_academic',
    tags: ['academic', 'nouns'],
    data: {
      word: 'Hypothesis',
      translation: 'השערה / הנחת עבודה',
      context_sentence: 'Before beginning the experiment, the researcher stated a clear hypothesis that she intended to test.',
      context_translation: 'לפני תחילת הניסוי, הציגה החוקרת השערה ברורה שבכוונתה לבדוק.',
      correct_answer: 'Hypothesis',
      common_mistake: 'A hypothesis is a testable prediction, not yet proven. Once proven, it may become a theory.',
    },
  },
  {
    id: 'v18',
    type: 'vocabulary',
    difficulty: 610,
    skill: 'vocabulary_academic',
    tags: ['academic', 'nouns', 'advanced'],
    data: {
      word: 'Ambiguity',
      translation: 'עמימות / חוסר בהירות',
      context_sentence: "The contract was full of ambiguity, making it hard to determine each party's responsibilities.",
      context_translation: 'החוזה היה מלא עמימות, מה שהקשה לקבוע את אחריות כל צד.',
      correct_answer: 'Ambiguity',
      common_mistake: '"Ambiguity" is a noun. The adjective is "ambiguous." The adverb is "ambiguously."',
    },
  },
  {
    id: 'v19',
    type: 'vocabulary',
    difficulty: 650,
    skill: 'vocabulary_academic',
    tags: ['academic', 'verbs', 'advanced'],
    data: {
      word: 'Corroborate',
      translation: 'לאשר / לחזק (ראיות)',
      context_sentence: 'The second witness came forward to corroborate the original testimony given in court.',
      context_translation: 'העד השני התייצב כדי לאשר את העדות המקורית שניתנה בבית המשפט.',
      correct_answer: 'Corroborate',
      common_mistake: '"Corroborate" specifically means to confirm evidence already presented — stronger than "support."',
    },
  },
  // ── Idioms ────────────────────────────────────────────────
  {
    id: 'v20',
    type: 'vocabulary',
    difficulty: 470,
    skill: 'vocabulary_idioms',
    tags: ['idioms', 'beginner'],
    data: {
      word: 'Bite the bullet',
      translation: 'לנשוך את הכדור — לעשות משהו כואב אך הכרחי',
      context_sentence: 'I hate going to the dentist, but I decided to bite the bullet and make an appointment.',
      context_translation: 'אני שונא ללכת לרופא שיניים, אבל החלטתי "לנשוך את הכדור" ולקבוע תור.',
      correct_answer: 'Bite the bullet',
      common_mistake: 'Do not use this idiom for physical pain alone — it specifically means accepting something unpleasant because it is necessary.',
    },
  },
  {
    id: 'v21',
    type: 'vocabulary',
    difficulty: 510,
    skill: 'vocabulary_idioms',
    tags: ['idioms'],
    data: {
      word: 'Burn bridges',
      translation: 'לשרוף גשרים — לקצץ קשרים בצורה שלא ניתן לחזור',
      context_sentence: 'She left the company on bad terms, effectively burning bridges with most of her former colleagues.',
      context_translation: 'היא עזבה את החברה בתנאים רעים, ובעצם שרפה גשרים עם רוב עמיתיה לשעבר.',
      correct_answer: 'Burn bridges',
      common_mistake: 'Usually used as a warning: "don\'t burn your bridges" — implying you may need those contacts later.',
    },
  },
  {
    id: 'v22',
    type: 'vocabulary',
    difficulty: 560,
    skill: 'vocabulary_idioms',
    tags: ['idioms', 'intermediate'],
    data: {
      word: 'On the fence',
      translation: 'על הגדר — לא להחליט לאיזה צד לעמוד',
      context_sentence: 'Many voters were on the fence about the new policy until the details were published.',
      context_translation: 'מצביעים רבים לא החליטו לגבי המדיניות החדשה עד שהפרטים פורסמו.',
      correct_answer: 'On the fence',
      common_mistake: 'Means undecided between two clear options — different from "confused" (which implies lack of understanding).',
    },
  },
  {
    id: 'v23',
    type: 'vocabulary',
    difficulty: 600,
    skill: 'vocabulary_idioms',
    tags: ['idioms', 'advanced'],
    data: {
      word: 'Spill the beans',
      translation: 'לשפוך את השעועית — לגלות סוד בטעות',
      context_sentence: 'He accidentally spilled the beans about the surprise party when he mentioned it to her sister.',
      context_translation: 'הוא בטעות גילה את הסוד על מסיבת ההפתעה כשציין זאת בפני אחותה.',
      correct_answer: 'Spill the beans',
      common_mistake: 'Always implies accidental disclosure of secret information. The "spilling" is unintentional.',
    },
  },
  // ── Nature / Adjectives ───────────────────────────────────
  {
    id: 'v24',
    type: 'vocabulary',
    difficulty: 530,
    skill: 'vocabulary_environment',
    tags: ['nature', 'adjectives', 'intermediate'],
    data: {
      word: 'Serene',
      translation: 'שליו / שקט ורגוע',
      context_sentence: 'The lake at dawn was completely serene, with no wind to disturb the surface.',
      context_translation: 'האגם בשחר היה שליו לחלוטין, ללא רוח שתפריע לפני המים.',
      correct_answer: 'Serene',
      common_mistake: '"Serene" implies peaceful calm, often of a place or a person\'s expression — more poetic than just "quiet."',
    },
  },
  {
    id: 'v25',
    type: 'vocabulary',
    difficulty: 580,
    skill: 'vocabulary_academic',
    tags: ['social', 'verbs', 'intermediate'],
    data: {
      word: 'Persuade',
      translation: 'לשכנע',
      context_sentence: 'He tried to persuade his manager to approve the new project proposal by presenting solid data.',
      context_translation: 'הוא ניסה לשכנע את מנהלו לאשר את הצעת הפרויקט החדשה על ידי הצגת נתונים מוצקים.',
      correct_answer: 'Persuade',
      common_mistake: '"Persuade" requires someone to actually change their mind. "Try to persuade" does not guarantee success. Contrast with "convince."',
    },
  },
  {
    id: 'v26',
    type: 'vocabulary',
    difficulty: 460,
    skill: 'vocabulary_business',
    tags: ['business', 'adjectives'],
    data: {
      word: 'Pragmatic',
      translation: 'פרגמטי / מעשי',
      context_sentence: 'A pragmatic leader focuses on what works in practice, not just what sounds good in theory.',
      context_translation: 'מנהיג פרגמטי מתמקד במה שעובד בפועל, לא רק במה שנשמע טוב בתיאוריה.',
      correct_answer: 'Pragmatic',
      common_mistake: '"Pragmatic" is about practical outcomes — not cold or uncaring, just realistic.',
    },
  },
  {
    id: 'v27',
    type: 'vocabulary',
    difficulty: 670,
    skill: 'vocabulary_academic',
    tags: ['academic', 'adjectives', 'advanced'],
    data: {
      word: 'Paradoxical',
      translation: 'פרדוקסלי / סותר את עצמו',
      context_sentence: 'It is paradoxical that the more choices we have, the less satisfied we often feel with our decisions.',
      context_translation: 'זה פרדוקסלי שככל שיש לנו יותר אפשרויות, לעתים קרובות אנו מרגישים פחות מרוצים מהחלטותינו.',
      correct_answer: 'Paradoxical',
      common_mistake: 'A paradox appears self-contradictory but may still be true — do not confuse with "ironic."',
    },
  },
  {
    id: 'v28',
    type: 'vocabulary',
    difficulty: 500,
    skill: 'vocabulary_travel',
    tags: ['travel', 'nouns'],
    data: {
      word: 'Accommodation',
      translation: 'לינה / מקום מגורים זמני',
      context_sentence: 'We booked our accommodation well in advance to get the best price during peak season.',
      context_translation: 'הזמנו את הלינה מראש כדי לקבל את המחיר הטוב ביותר בעונת השיא.',
      correct_answer: 'Accommodation',
      common_mistake: 'Note the spelling: double "c" and double "m". Common misspelling: "acommodation".',
    },
  },
  {
    id: 'v29',
    type: 'vocabulary',
    difficulty: 440,
    skill: 'vocabulary_emotions',
    tags: ['emotions', 'adjectives'],
    data: {
      word: 'Overwhelmed',
      translation: 'מוצף / שקוע יותר מדי',
      context_sentence: 'She felt overwhelmed by the sheer number of emails waiting in her inbox on Monday morning.',
      context_translation: 'היא הרגישה מוצפת מכמות האימיילים שהמתינו בתיבת הדואר שלה בבוקר יום שני.',
      correct_answer: 'Overwhelmed',
      common_mistake: '"Overwhelmed" can be used for both negative situations (stress) and positive ones (overwhelmed with joy).',
    },
  },
  {
    id: 'v30',
    type: 'vocabulary',
    difficulty: 620,
    skill: 'vocabulary_business',
    tags: ['business', 'nouns', 'advanced'],
    data: {
      word: 'Accountability',
      translation: 'אחריותיות / מחויבות לתוצאות',
      context_sentence: "The new manager introduced a culture of accountability where every team member owned their results.",
      context_translation: 'המנהל החדש הכניס תרבות של אחריותיות שבה כל חבר צוות היה אחראי לתוצאותיו.',
      correct_answer: 'Accountability',
      common_mistake: '"Accountability" means being answerable for outcomes, not just being responsible for tasks.',
    },
  },
  // ── Beginner (Tier 1) ─────────────────────────────────────
  {
    id: 'v31',
    type: 'vocabulary',
    difficulty: 350,
    skill: 'vocabulary_travel',
    tags: ['basics', 'beginner'],
    data: {
      word: 'Hello',
      translation: 'שלום',
      context_sentence: 'Hello! My name is Tom.',
      context_translation: 'שלום! קוראים לי טום.',
      correct_answer: 'Hello',
      common_mistake: 'Use "Hello" as a general greeting. "Hi" is informal but also correct in casual settings.',
    },
  },
  {
    id: 'v32',
    type: 'vocabulary',
    difficulty: 360,
    skill: 'vocabulary_travel',
    tags: ['basics', 'beginner'],
    data: {
      word: 'Water',
      translation: 'מים',
      context_sentence: 'Can I have a glass of water, please?',
      context_translation: 'אפשר לקבל כוס מים, בבקשה?',
      correct_answer: 'Water',
      common_mistake: '"Water" is uncountable — say "a glass of water", not "a water".',
    },
  },
  {
    id: 'v33',
    type: 'vocabulary',
    difficulty: 370,
    skill: 'vocabulary_travel',
    tags: ['basics', 'beginner'],
    data: {
      word: 'Book',
      translation: 'ספר',
      context_sentence: 'I read a book every night before bed.',
      context_translation: 'אני קורא ספר כל לילה לפני השינה.',
      correct_answer: 'Book',
      common_mistake: '"Read" is pronounced /riːd/ (present) and /red/ (past) — same spelling, different sound.',
    },
  },
  {
    id: 'v34',
    type: 'vocabulary',
    difficulty: 380,
    skill: 'vocabulary_emotions',
    tags: ['basics', 'beginner'],
    data: {
      word: 'Happy',
      translation: 'שמח / מאושר',
      context_sentence: 'The children are happy because it is their birthday.',
      context_translation: 'הילדים שמחים כי זה יום ההולדת שלהם.',
      correct_answer: 'Happy',
      common_mistake: 'Use "happy" with "be": "I am happy" — not "I have happy".',
    },
  },
  {
    id: 'v35',
    type: 'vocabulary',
    difficulty: 390,
    skill: 'vocabulary_travel',
    tags: ['basics', 'beginner'],
    data: {
      word: 'Friend',
      translation: 'חבר / חברה',
      context_sentence: 'She is my best friend from school.',
      context_translation: 'היא החברה הכי טובה שלי מבית הספר.',
      correct_answer: 'Friend',
      common_mistake: '"Best friend" is one person. For several close friends, say "close friends".',
    },
  },
  // ── Advanced (Tier 9–10) ────────────────────────────────────
  {
    id: 'v36',
    type: 'vocabulary',
    difficulty: 760,
    skill: 'vocabulary_academic',
    tags: ['academic', 'advanced'],
    data: {
      word: 'Ubiquitous',
      translation: 'נמצא בכל מקום / שכיח מאוד',
      context_sentence: 'Smartphones have become ubiquitous in modern society, appearing in nearly every public space.',
      context_translation: 'סמארטפונים הפכו לנפוצים בכל מקום בחברה המודרנית, ומופיעים כמעט בכל מרחב ציבורי.',
      correct_answer: 'Ubiquitous',
      common_mistake: '"Ubiquitous" means present everywhere — stronger than "common" or "popular".',
    },
  },
  {
    id: 'v37',
    type: 'vocabulary',
    difficulty: 810,
    skill: 'vocabulary_academic',
    tags: ['academic', 'advanced'],
    data: {
      word: 'Inscrutable',
      translation: 'בלתי ניתן לפענוח / מסתורי',
      context_sentence: 'The CEO maintained an inscrutable expression throughout the entire press conference.',
      context_translation: 'מנכ"ל החברה שמר על הבעה בלתי ניתנת לפענוח לאורך כל מסיבת העיתונות.',
      correct_answer: 'Inscrutable',
      common_mistake: '"Inscrutable" describes something impossible to read or interpret — often a face or motive.',
    },
  },
  {
    id: 'v38',
    type: 'vocabulary',
    difficulty: 860,
    skill: 'vocabulary_idioms',
    tags: ['advanced', 'formal'],
    data: {
      word: 'Ambivalent',
      translation: 'מעורב רגשות / לא החלטי',
      context_sentence: 'She felt ambivalent about accepting the promotion because it meant relocating abroad.',
      context_translation: 'היא הרגישה מעורבת רגשות לגבי קבלת הקידום כי זה אומר מעבר לחו"ל.',
      correct_answer: 'Ambivalent',
      common_mistake: '"Ambivalent" means having mixed feelings — not the same as "indifferent" (no feelings at all).',
    },
  },
  {
    id: 'v39',
    type: 'vocabulary',
    difficulty: 880,
    skill: 'vocabulary_academic',
    tags: ['academic', 'master'],
    data: {
      word: 'Perspicacious',
      translation: 'חד תבונה / בעל הבנה עמוקה',
      context_sentence: 'The perspicacious analyst predicted the market downturn months before it occurred.',
      context_translation: 'האנליסט החד-תבונה חזה את ירידת השוק חודשים לפני שהיא התרחשה.',
      correct_answer: 'Perspicacious',
      common_mistake: '"Perspicacious" means keenly perceptive — do not confuse with "perspicuous" (clearly expressed).',
    },
  },
]
